VirtoCommerce/vc-frontend

client-app/core/composables/useFetch.ts
client-app/shared/layout/components/header.vue

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/client-app-0.0.0-pr-17-c576eb13.zip

ST-328: logout error. mobile auth menu

---

client-app/main.ts
client-app/pages/403/403.vue
client-app/pages/404/404.vue
client-app/pages/500/500.vue
client-app/router.ts
client-app/shared/account/components/sign-in-form.vue
client-app/shared/layout/components/header.vue
package-lock.json
package.json
tailwind.config.js
vite.config.ts
yarn.lock

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/client-app-0.0.0-pr-18-7df17eb6.zip

fix: layout inaccuracies. hide login error at input event

---

.deployment/storefront-app/argoDeploy.json
.github/workflows/deploy.yml
.github/workflows/main.yml

Updated deployment workflow deploy.yml:
- added step to push Deployment Info to Jira
- changed step for deployment status monitoring
In the main workflow added job for dev environment deployment; job runs on pus for dev branch or when the workflow runs manually
Added ArgoCD deployment config '.deployment.storefront-app.argoDeploy.json'
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/client-app-0.0.1-pr-20-985cdb53.zip

ST-6: Add deployment to storefront-app dev environment

---

client-app/shared/checkout/components/product-card.vue

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/client-app-0.0.1-pr-30-f2a2ee1b.zip

ST-540: fix no image on the checkout page

---

client-app/pages/forgot-password/forgot-password.vue
client-app/pages/reset-password/reset-password.vue
client-app/router.ts
client-app/shared/account/components/forgot-password-form.vue
client-app/shared/account/components/index.ts
client-app/shared/account/components/reset-password-form.vue
client-app/shared/account/components/sign-in-form.vue
client-app/shared/account/composables/useUser.ts
client-app/shared/account/types/index.ts
package-lock.json

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/client-app-0.0.1-pr-33-23c30472.zip

ST-155: Implement the forgot password functionality

---

client-app/pages/account/addresses.vue

Description:
--
QA-test: ST-291
Demo-test: ST-292
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/client-app-0.0.1-pr-39-8a41606d.zip

ST-288: fix property on mobile version

---

client-app/pages/sign-up/sign-up-page.vue
client-app/shared/account/components/index.ts
client-app/shared/account/components/registration-success-dialog.vue

Description:
--
QA-test: ST-422
Demo-test: ST-423

feat: Add popup for successful registration

---

client-app/pages/account/addresses.vue

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/client-app-0.0.1-pr-46-6e8379b4.zip

ST-533: Specify the required city in the address form

---

client-app/components/molecules/card/card.vue
client-app/components/organisms/index.ts
client-app/components/organisms/table/table.vue
client-app/components/types/index.ts
client-app/pages/account/addresses.vue
client-app/pages/account/dashboard.vue
client-app/pages/account/orders.vue
client-app/shared/account/composables/useUserOrders.ts
client-app/shared/checkout/components/shipping-address-dialog.vue

Description:
--
QA-test: ST-944
Demo-test: ST-945
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/client-app-0.0.4-pr-56-fa404852.zip

ST-903: Add vc-table component

---

client-app/components/molecules/input/input.vue
client-app/core/api/graphql/account/queries/getMe/getMeQuery.graphql
client-app/pages/account/profile.vue
client-app/router.ts
client-app/shared/account/components/account-navigation.vue
client-app/shared/account/components/index.ts
client-app/shared/account/components/profile-update-success-dialog.vue
client-app/shared/account/composables/useUser.ts
client-app/shared/account/types/index.ts
client-app/shared/layout/components/header/_internal/mobile-menu-link.vue
client-app/shared/layout/components/header/_internal/mobile-menu.vue
client-app/shared/layout/components/header/_internal/top-header.vue

Description:
--
QA-test: ST-286
Demo-test: ST-287
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/client-app-0.0.4-pr-60-2072825e.zip

ST-283: Add profile page

---

client-app/core/api/graphql/cart/mutations/addItemsToCart/addItemsToCartMutation.graphql
client-app/core/api/graphql/cart/mutations/addItemsToCart/index.ts
client-app/core/api/graphql/catalog/queries/searchProducts/index.ts
client-app/core/api/graphql/catalog/queries/searchProducts/searchProductsQuery.graphql
client-app/pages/account/order-details.vue
client-app/shared/account/components/index.ts
client-app/shared/account/components/product-card-reorder.vue
client-app/shared/account/components/reorder-info.vue
client-app/shared/cart/composables/useCart.ts
client-app/shared/cart/index.ts
client-app/shared/cart/types/index.ts
client-app/shared/catalog/types/search.ts

Description:
--
QA-test: ST-219
Demo-test: ST-967
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/client-app-0.0.4-pr-64-33acfeaf.zip

ST-217: Reorder all

---

client-app/components/organisms/table/_internal/table-mobile-item/table-mobile-item.vue
client-app/components/organisms/table/table.vue
client-app/components/types/index.ts
client-app/pages/account/addresses.vue

Description:
--
QA-test: ST-1030
Demo-test: ST-1031
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/client-app-0.0.4-pr-69-669ab2eb.zip

ST-844: Update swipe actions

---

client-app/core/api/graphql/account/queries/getMyOrders/getMyOrdersQuery.graphql

Description:
--
QA-test: ST-1018
Demo-test: ST-1019
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/client-app-0.0.4-pr-73-36d04126.zip

ST-1016: Show purchased order on orders page

---

client-app/pages/checkout/checkout.vue
client-app/shared/checkout/components/product-card.vue

Description:
--
QA-test: ST-631
Demo-test: ST-632
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/client-app-0.0.4-pr-74-27bb62a8.zip

ST-681: Add error messages for cart items

---

client-app/shared/account/components/product-card-reorder.vue
client-app/shared/account/components/reorder-info.vue

Description:
--
QA-test: ST-1005
Demo-test: ST-1006
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/client-app-0.0.4-pr-72-b2274c45.zip

ST-1003: Add can't purchase cases for reorder

---

client-app/pages/account/addresses.vue

Description:
--
QA-test: ST-684
Demo-test: ST-685
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/client-app-0.0.4-pr-75-c2ac72bf.zip

ST-681: Implement actions for addresses page

---

client-app/pages/checkout/checkout.vue

Description:
--
QA-test: ST-1022
Demo-test: ST-1023
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/client-app-0.0.4-pr-79-8d824173.zip

ST-1020: Add error message for cart

---

client-app/pages/catalog/catalog.vue

Description:
--
QA-test: ST-718
Demo-test: ST-719
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/client-app-0.0.4-pr-82-f62f15e7.zip

ST-1133: Removed text for amount presented product on the page

---

client-app/core/api/graphql/catalog/queries/searchProducts/searchProductsQuery.graphql
client-app/core/api/graphql/graphql-client.ts
client-app/pages/catalog/catalog.vue
client-app/pages/search/search.vue
client-app/shared/catalog/utils/search-utils.ts

Description:
--
QA-test: ST-808
Demo-test: ST-809
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/client-app-0.0.4-pr-78-ffb8675b.zip

fix: facet filter

---

client-app/pages/product/product.vue

Description:
--
QA-test: ST-620
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/client-app-0.0.4-pr-81-7085944c.zip

ST-620: 404 error on Product page

---

.eslintrc.js
client-app/core/api/graphql/account/mutations/deleteMemberAddresses/index.ts
client-app/core/injection-keys.ts
client-app/core/plugins/config.ts
client-app/core/plugins/context.ts
client-app/core/utilities/context/index.ts
client-app/main.ts
client-app/shared/account/components/reorder-info.vue
client-app/shared/account/composables/useUser.ts
client-app/shared/account/composables/useUserAddresses.ts
client-app/shared/cart/composables/useCheckout.ts
client-app/shared/catalog/components/product-properties.vue
client-app/shared/catalog/components/variation-properties.vue
client-app/shared/catalog/composables/useCategories.ts
client-app/vue-shims.d.ts

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/client-app-0.0.4-pr-83-89f25a21.zip

feat(eslint): added "no-shadow" and "no-non-null-assertion" rules

---

client-app/App.vue
client-app/config/menu.ts
client-app/core/api/graphql/types.ts
client-app/core/utilities/helpers/index.ts
client-app/main.ts
client-app/pages/catalog/catalog.vue
client-app/shared/catalog/components/product-card-grid.vue
client-app/shared/catalog/components/product-card-list.vue
client-app/shared/catalog/components/product-details.vue
client-app/shared/compare/components/add-to-compare.vue
client-app/shared/compare/components/index.ts
client-app/shared/compare/composables/index.ts
client-app/shared/compare/composables/useCompareProducts.ts
client-app/shared/compare/index.ts
client-app/shared/layout/components/footer/footer.vue
client-app/shared/layout/components/header/_internal/bottom-header-link.vue
client-app/shared/layout/components/header/_internal/bottom-header.vue
client-app/shared/layout/components/header/_internal/mobile-menu.vue
client-app/shared/notification/components/index.ts
client-app/shared/notification/components/notifications-host.vue
client-app/shared/notification/composables/index.ts
client-app/shared/notification/composables/useNotifications.ts
client-app/shared/notification/index.ts
client-app/shared/notification/types/index.ts
config/settings_data.json
locales/en-US.json

Description:
--
QA-test: ST-498
Demo-test: ST-499
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/client-app-0.0.4-pr-87-ea2558b2.zip

ST-495: Compare products

---

.idea/i18nally.json
.prettierignore
client-app/components/atoms/button/button.vue
client-app/core/api/graphql/fragments/wishlistFields.graphql
client-app/core/api/graphql/wishlists/index.ts
client-app/core/api/graphql/wishlists/mutations/addWishlist/addWishlistMutation.graphql
client-app/core/api/graphql/wishlists/mutations/addWishlist/index.ts
client-app/core/api/graphql/wishlists/mutations/addWishlistItem/addWishlistItemMutation.graphql
client-app/core/api/graphql/wishlists/mutations/addWishlistItem/index.ts
client-app/core/api/graphql/wishlists/mutations/removeWishlistItem/index.ts
client-app/core/api/graphql/wishlists/mutations/removeWishlistItem/removeWishlistItemMutation.graphql
client-app/core/api/graphql/wishlists/queries/getWishlists/getWishlists.graphql
client-app/core/api/graphql/wishlists/queries/getWishlists/index.ts
client-app/core/api/graphql/wishlists/types/index.ts
client-app/router.ts
client-app/shared/catalog/components/product-price-block.vue
client-app/shared/popup/components/popup-host.vue
client-app/shared/popup/composables/usePopup.ts
client-app/shared/popup/types/index.ts
client-app/shared/wishlists/components/add-to-wishlists-dialog.vue
client-app/shared/wishlists/components/added-to-wishlists-dialog.vue
client-app/shared/wishlists/components/index.ts
client-app/shared/wishlists/composables/index.ts
client-app/shared/wishlists/composables/useWishlists.ts
client-app/shared/wishlists/index.ts
locales/en-US.json

Description:
--
QA-test: ST-321
Demo-test: ST-322
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/client-app-0.0.4-pr-90-63813623.zip

ST-318: Add to wish list

---

client-app/core/api/graphql/account/index.ts
client-app/core/api/graphql/account/mutations/createContact/createContact.graphql
client-app/core/api/graphql/account/mutations/createContact/index.ts
client-app/core/api/graphql/account/mutations/createOrganization/createOrganization.graphql
client-app/core/api/graphql/account/mutations/createOrganization/index.ts
client-app/core/api/graphql/account/mutations/createUser/createUser.graphql
client-app/core/api/graphql/account/mutations/createUser/index.ts
client-app/core/api/graphql/account/queries/getMe/getMeQuery.graphql
client-app/core/api/graphql/account/queries/getMe/index.ts
client-app/core/utilities/helpers/index.ts
client-app/pages/sign-up/sign-up-page.vue
client-app/shared/account/components/registration-success-dialog.vue
client-app/shared/account/composables/useUser.ts
client-app/shared/account/types/index.ts
client-app/shared/layout/components/header/_internal/bottom-header.vue
locales/en-US.json

Description:
--
QA-test: ST-936
Demo-test: ST-937
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/client-app-0.0.4-pr-92-071f92f7.zip

feat(ST-933): Implement registration of organization. 

---

.github/CODE_OF_CONDUCT.md

Description:
--
QA-test:
Demo-test:

docs: code of conduct

---

client-app/pages/sign-up/sign-up-page.vue
client-app/shared/account/components/registration-success-dialog.vue
locales/en-US.json

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/client-app-0.0.4-pr-99-45b57f2e.zip

fix: localize radio button labels

---

.deployment/storefront-app/argoDeploy.json
.github/workflows/deploy.yml
.github/workflows/main.yml

Description:
Dev delivery after successful dev branch update.
Demo delivery after successful main (master) branch update.

ST-1259 Implement automated deploy to Demo environment

---

client-app/pages/account/order-details.vue
client-app/pages/checkout/checkout.vue
client-app/shared/account/composables/useUserOrders.ts
client-app/shared/cart/components/add-to-cart.vue
client-app/shared/checkout/components/thank-you.vue
locales/en-US.json

Description:
--
QA-test: ST-1417
Demo-test: ST-1418
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/client-app-0.0.4-pr-97-06e25b91.zip

Fix group of bugs (st-1432,st-1415,st-1436,st-1485,st-1504)

---

client-app/App.vue
client-app/core/types/index.ts
client-app/core/types/language.ts
client-app/core/types/theme-context.ts
client-app/main.ts

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/client-app-0.0.4-pr-101-5fbf8065.zip

feat: use extendted language data from theme context

---

client-app/core/api/graphql/account/index.ts
client-app/core/api/graphql/account/queries/getWishList/getWishlist.graphql
client-app/core/api/graphql/account/queries/getWishList/index.ts
client-app/core/types/index.ts
client-app/pages/account/list-details.vue
client-app/pages/account/lists.vue
client-app/router.ts
client-app/shared/account/components/account-navigation.vue
client-app/shared/wishlists/components/add-or-update-wishlist-dialog.vue
client-app/shared/wishlists/components/delete-wishlist-dialog.vue
client-app/shared/wishlists/components/delete-wishlist-product.vue
client-app/shared/wishlists/components/index.ts
client-app/shared/wishlists/components/unsuccessful-create-list-dialog.vue
client-app/shared/wishlists/components/wishlist-product-item.vue
client-app/shared/wishlists/composables/useWishlists.ts
config/settings_data.json
locales/en-US.json

Description:
--
QA-test: ST-486
Demo-test: ST-487
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/client-app-0.0.4-pr-103-468a6c81.zip

ST-483: Manage wish list

---

client-app/App.vue
client-app/core/api/graphql/cart/index.ts
client-app/core/api/graphql/cart/mutations/mergeCart/index.ts
client-app/core/api/graphql/cart/mutations/mergeCart/mergeCartMutation.graphql
client-app/pages/account/addresses.vue
client-app/shared/account/components/sign-in-form.vue
client-app/shared/account/composables/useUser.ts
client-app/shared/wishlists/components/delete-wishlist-dialog.vue

Description:
--
QA-test: ST-1172
Demo-test: ST-1173
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/client-app-0.0.4-pr-106-f7a4c4dd.zip

ST-1169: Merge anonymous cart after login

---

client-app/components/atoms/section/section.vue
client-app/pages/checkout/checkout.vue
client-app/shared/cart/composables/useCart.ts
client-app/shared/checkout/components/clear-cart-dialog.vue
client-app/shared/checkout/components/index.ts
locales/en-US.json

Description:
--
QA-test: ST-1222
Demo-test: ST-1223
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/client-app-0.0.4-pr-105-9595b997.zip

ST-1219: Add clear cart functionality

---

client-app/pages/checkout/checkout.vue

Description:
--
QA-test:
Demo-test:

ST-1219: Fix clear cart button position

---

client-app/pages/account/order-details.vue
client-app/shared/checkout/components/thank-you.vue

Description:
--
QA-test: ST-1469
Demo-test: ST-1470
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/client-app-0.0.4-pr-111-a5cc3fd9.zip

ST-1467: Fix text-overflow

---

client-app/pages/checkout/checkout.vue

Description:
--
QA-test: ST-1372
Demo-test: ST-1373
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/client-app-0.0.4-pr-110-23ed35aa.zip

ST-1370: Hide error message while order is processing

---

client-app/components/molecules/input/input.vue
client-app/shared/bulk-order/components/manually.vue

Description:
--
QA-test: ST-1756
Demo-test: ST-1757
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/client-app-0.0.4-pr-113-e6e09fd5.zip

fix(ST-1754): fixed VcInput [type="number"]

---

client-app/pages/account/dashboard.vue

Description:
--
QA-test: ST-1455
Demo-test: ST-1456
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/client-app-0.0.4-pr-115-dfd71405.zip

ST-1453: Remove empty column in dashboard

---

locales/en.json

Description:
--
QA-test: ST-1746
Demo-test: ST-1747
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/client-app-0.0.4-pr-116-ae7df266.zip

ST-1714: Fix popup name

---

client-app/pages/compare-products/compare-products.vue

Description:
--
QA-test: ST-1716
Demo-test: ST-1717
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/client-app-0.0.4-pr-114-450a4920.zip

ST-1714: Fix add-to-cart button with filter behaviour

---

client-app/shared/cart/components/add-to-cart.vue
client-app/shared/cart/components/cart-add-info.vue

Description:
--
QA-test: ST-1587
Demo-test: ST-1588
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/client-app-0.0.4-pr-119-563d501a.zip

fix(ST-1585): validation errors in AddToCart component

---

client-app/core/constants.ts
client-app/pages/catalog/catalog.vue
client-app/shared/catalog/composables/useProducts.ts
client-app/shared/catalog/utils/search-utils.ts
locales/de.json
locales/en.json

Description:
--
QA-test: ST-1306
Demo-test: ST-1307
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/client-app-0.0.4-pr-121-492d5db1.zip

ST-1303: Add instock filter

---

client-app/core/api/graphql/account/index.ts
client-app/core/api/graphql/account/queries/checkEmailUniqueness/checkEmailUniquenessQuery.graphql
client-app/core/api/graphql/account/queries/checkEmailUniqueness/index.ts
client-app/core/api/graphql/account/queries/checkUsernameUniqueness/checkUsernameUniquenessQuery.graphql
client-app/core/api/graphql/account/queries/checkUsernameUniqueness/index.ts
client-app/pages/sign-up/sign-up-page.vue

Description:
--
QA-test: ST-1242
Demo-test: ST-1243
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/client-app-0.0.4-pr-122-a9fe579c.zip

ST-1239: Add on fly validation for email and username

---

client-app/components/atoms/button/button.vue
client-app/pages/compare-products/compare-products.vue
client-app/shared/cart/components/add-to-cart.vue
client-app/shared/layout/components/search-bar/search-bar.vue

Description:
--
QA-test: ST-1770
Demo-test: ST-1771
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/client-app-0.0.4-pr-127-eb51721b.zip

fix(ST-1768): fixed UI bugs on compare products page

---

client-app/shared/layout/components/language-selector/language-selector.vue
package.json
yarn.lock

Description:
--
QA-test: ST-1956
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/client-app-0.0.4-pr-132-9e34fd28.zip

ST-1929: replace old package with flags

---

client-app/core/composables/useFetch.ts
client-app/core/constants.ts
client-app/core/utilities/helpers/index.ts
client-app/i18n.ts
client-app/shared/account/composables/useUserAddresses.ts
client-app/shared/account/composables/useUserOrder.ts
client-app/shared/account/composables/useUserOrders.ts
client-app/shared/bulk-order/utils/index.ts
client-app/shared/cart/composables/useCart.ts
client-app/shared/cart/composables/useCheckout.ts
client-app/shared/catalog/composables/useCategories.ts
client-app/shared/catalog/composables/useProducts.ts
client-app/shared/catalog/utils/search-utils.ts
client-app/shared/compare/composables/useCompareProducts.ts
client-app/shared/layout/components/language-selector/language-selector.vue
client-app/shared/layout/components/search-bar/search-bar.vue
client-app/shared/layout/components/сurrency-selector/сurrency-selector.vue
client-app/shared/layout/composables/useNavigations.ts
client-app/shared/layout/composables/useSearchBar.ts
client-app/shared/notification/composables/useNotifications.ts
client-app/shared/popup/composables/usePopup.ts

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/client-app-0.0.4-pr-134-f32d1a98.zip

fix: codesmells

---

client-app/shared/checkout/components/product-card.vue
locales/de.json
locales/en.json

Description:
--
QA-test: ST-1465
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/client-app-0.0.4-pr-140-d2c9bc99.zip

ST-1463: Localize cart item error

---

client-app/shared/catalog/components/product-card-grid.vue
client-app/shared/catalog/components/product-card-list.vue
locales/de.json
locales/en.json

Description:
--
QA-test: ST-1349
Demo-test: ST-1350
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/client-app-0.0.4-pr-142-cdcfcba9.zip

ST-1346: Remove unused block from product card

---

client-app/core/types/index.ts
client-app/shared/layout/components/search-bar/search-bar.vue
config/settings_data.json

Description:
--
QA-test: ST-1317
Demo-test: ST-1319
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.1.0-pr-146-3e370b0a.zip

ST-1315: Add chars limit to search bar

---

.env
client-app/core/api/graphql/graphql-client.ts
package.json
yarn.lock

Description:
--
QA-test: ST-1177
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.1.0-pr-148-129f1c06.zip

feat(ST-1174): Handle session expiration

---

client-app/pages/account/addresses.vue
client-app/pages/checkout/checkout.vue
client-app/shared/checkout/components/checkout-labeled-block.vue
client-app/shared/checkout/components/select-address-dialog.vue

Description:
--
QA-test: ST-861
Demo-test: ST-862
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.1.0-pr-149-7a3a2380.zip

ST-859: Fix broken pop up and addresses view on checkout/addresses page

---

client-app/pages/checkout/checkout.vue
client-app/shared/account/components/profile-update-success-dialog.vue
locales/de.json
locales/en.json

Description:
--
QA-test: ST-1741
Demo-test: ST-1742
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.1.0-pr-151-a046f4ff.zip

ST-1739, ST-1776: Rename buttons, remove redirect after profile update

---

client-app/pages/account/profile.vue

Description:
--
QA-test: ST-2068
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.1.0-pr-153-a2784734.zip

ST-2066: Fix problem with profile update

---

client-app/shared/layout/components/search-bar/search-bar.vue

Description:
--
QA-test: ST-1317
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.1.0-pr-156-239560c7.zip

ST-1315: Change search-bar behaviour

---

client-app/shared/bulk-order/components/manually.vue

Description:
--
QA-test: ST-1786
Demo-test: ST-1787
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.1.0-pr-155-a7235bc2.zip

ST-1784: Change buttons behaviour

---

client-app/builder-preview/pages/blocks/text.vue
client-app/builder-preview/pages/pages.vue
client-app/builder-preview/pages/useTemplate.ts
yarn.lock

Description: small visual changes for text block in pages
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.2.0-pr-160-1cf3de08.zip

feat: layout text block

---

client-app/components/atoms/input/input.vue
client-app/pages/account/profile.vue
client-app/pages/home/home.vue
client-app/pages/sign-up/sign-up-page.vue
client-app/shared/account/components/sign-in-form.vue
client-app/shared/account/composables/useUser.ts

Description:
--
QA-test: ST-2143
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.2.0-pr-162-e8373280.zip

ST-2138, ST-2141, ST-2135, ST-2126: Bug fixes

---

gulpfile.js

Description:
Add "content" folder to deploy
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.2.1-pr-167-90d3fa0e.zip

fix: add content folder to deploy

---

client-app/shared/account/components/sign-in-form.vue

Description:
--
QA-test: ST-1935
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.2.1-pr-175-f9b3e71a.zip

ST-1933: Fixed double validation error messages when login

---

client-app/components/molecules/item-price/vc-item-price.vue
client-app/shared/catalog/components/product-card-grid.vue

Description:
--
QA-test: ST-1909
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.2.1-pr-176-4e9f77fe.zip

ST-1907: Price in product card on the small screen size

---

client-app/components/molecules/item-price/vc-item-price.vue
client-app/shared/account/components/sign-in-form.vue
client-app/shared/catalog/components/product-card-grid.vue
client-app/shared/wishlists/components/added-to-wishlists-dialog.vue

Description:
--
QA-test: ST-1774
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.3.0-pr-177-d9504b16.zip

ST-1772, ST-1933, ST-1907

---

client-app/pages/account/list-details.vue
client-app/pages/account/lists.vue
client-app/pages/account/order-details.vue
locales/de.json
locales/en.json

Description: ST-2033, ST-1480, ST-2308
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.3.0-pr-190-dfe9b8a5.zip

chore: small improvements

---

client-app/i18n.ts
client-app/pages/account/dashboard.vue
client-app/pages/account/order-details.vue
client-app/pages/account/orders.vue

Description:
--
QA-test: ST-2032
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.3.0-pr-188-18504708.zip

ST-2029: Add date localization settings

---

client-app/pages/account/orders.vue
client-app/shared/account/components/index.ts
client-app/shared/account/components/mobile-orders-filter.vue

Description:
--
QA-test: ST-2086
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.3.0-pr-191-737c0cf5.zip

ST-2083: Add new component for mobile orders filtering

---

client-app/core/types/index.ts
client-app/ui-kit/components/atoms/image/vc-image.vue
config/settings_data.json

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.3.0-pr-196-7d5cd336.zip

feat: image tools configurable behavior

---

client-app/core/types/index.ts
client-app/pages/index.vue
config/settings_data.json

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.3.0-pr-197-3fb57087.zip

feat: configurable homepage background

---

client-app/pages/category.vue
client-app/shared/catalog/components/category-selector.vue
client-app/shared/catalog/components/index.ts
client-app/shared/catalog/composables/useCategories.ts
client-app/shared/catalog/composables/useCategoriesRoutes.ts
client-app/shared/catalog/types/index.ts
client-app/shared/catalog/utils/category-utils.ts
client-app/ui-kit/components/atoms/card/vc-card.vue
locales/de.json
locales/en.json

Description:
--
QA-test: ST-1252
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.3.0-pr-194-f0247f4b.zip

feat(ST-1249): [Catalog] Implement Category/Subcategory selector

---

client-app/pages/account/list-details.vue
client-app/pages/account/lists.vue
client-app/shared/catalog/components/product-card-grid.vue
client-app/shared/layout/components/header/_internal/bottom-header.vue

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.3.0-pr-198-220aebb9.zip

fix: fix lint issues

---

client-app/builder-preview/pages/pages.vue
config/schemas/sections/cover-with-image.json
config/schemas/sections/cover-with-variations.json
config/schemas/sections/hero.json
config/schemas/sections/image.json
config/schemas/sections/images.json
config/schemas/sections/latest-news.json
config/schemas/sections/product-details.json
config/schemas/sections/product-info.json
config/schemas/sections/products-list.json
config/schemas/sections/share.json
config/schemas/sections/text.json
config/schemas/sections/video.json

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.4.0-pr-202-589145d0.zip

fix: hide invisible blocks

---

client-app/pages/category.vue

Description:
--
QA-test: ST-2380
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.4.0-pr-204-2e6fb938.zip

fix(ST-2378): fix behavior for seo none mode

---

client-app/shared/layout/components/header/_internal/mobile-header.vue

Description:
--
QA-test: ST-2197
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.4.0-pr-201-c039e84b.zip

ST-2195: Remove scroll behind mobile menu

---

client-app/shared/layout/components/search-bar/search-bar.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-2337
--
QA-test: ST-2339
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.4.0-pr-205-76a13069.zip

ST-2337: fix(search-bar) hideSearchDropdown

---

client-app/ui-kit/components/atoms/input/vc-input.vue

Description:
--
QA-test: ST-2478
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.4.0-pr-208-66b33577.zip

ST-2333: Prevent usage of empty fields

---

client-app/pages/sign-up.vue
client-app/shared/account/components/sign-in-form.vue
client-app/shared/account/types/index.ts
locales/de.json
locales/en.json

Description:
--
QA-test: ST-2219
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.4.0-pr-206-077d63bd.zip

feat(ST-2216): sign in with the email instead of the username

---

client-app/shared/layout/components/search-bar/search-bar.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-2477
--
QA-test: ST-2477
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.4.0-pr-209-fd728ae2.zip

fix(ST-2477): reduce search dropdown products number

---

client-app/shared/account/components/reorder-info.vue
client-app/shared/checkout/components/add-or-update-address-dialog.vue
client-app/shared/checkout/components/select-address-dialog.vue
client-app/shared/wishlists/components/add-to-wishlists-dialog.vue
client-app/ui-kit/components/organisms/popup/vc-popup.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-2206
--
QA-test: ST-2209
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.4.0-pr-207-d6eeb3d8.zip

feat(ST-2206): implement full screen mobile popups

---

client-app/ui-kit/components/atoms/text-area/vc-text-area.vue

Description:
--
QA-test: ST-1402
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.4.0-pr-212-cfb7712a.zip

ST-1400: Change textarea counter

---

client-app/shared/cart/composables/useCheckout.ts

Description:
--
QA-test: ST-1945
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.4.0-pr-215-7c76da05.zip

ST-1943: Resolve cart error on order creation

---

client-app/pages/account/lists.vue
client-app/shared/account/components/account-navigation.vue
client-app/shared/layout/components/header/_internal/bottom-header.vue
client-app/shared/layout/components/header/_internal/catalog-dropdown.vue
client-app/shared/layout/components/header/_internal/mobile-header.vue
client-app/shared/layout/components/header/_internal/mobile-menu.vue
client-app/shared/layout/components/nested-mobile-header/nested-mobile-header.ts
client-app/shared/layout/composables/useNavigations.ts
client-app/shared/layout/types/index.ts
client-app/shared/layout/utils/index.ts
client-app/ui-kit/components/pages/matcher.vue
config/menu.json
locales/de.json
locales/en.json

Description:
--
QA-test: ST-2433
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.4.0-pr-217-aedc85d2.zip

ST-2365, ST-2459, ST-2432: Main menu

---

client-app/pages/account/list-details.vue
client-app/shared/account/components/product-card-reorder.vue
client-app/shared/checkout/components/product-card.vue
client-app/shared/wishlists/components/add-to-wishlists-dialog.vue
client-app/shared/wishlists/components/wishlist-product-item.vue
client-app/shared/wishlists/composables/useWishlists.ts
client-app/xapi/graphql/account/queries/getWishList/getWishlist.graphql
locales/de.json
locales/en.json

Description:
https://virtocommerce.atlassian.net/browse/ST-1889
Also fixed.
https://virtocommerce.atlassian.net/browse/ST-2117
https://virtocommerce.atlassian.net/browse/ST-2474
--
QA-test: ST-2119
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.4.0-pr-216-bb001126.zip

fix(ST-1889,ST-2117,ST-2474): fix error at request list on lists page when list has deleted product

---

locales/en.json

Description:
--
QA-test: ST-2376
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.4.0-pr-219-b620de62.zip

ST-2374: Fix localization for desktop account navigation

---

client-app/pages/account/order-details.vue

Description:
--
QA-test: ST-2349
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.4.0-pr-218-f6c0a074.zip

ST-2347: Hide back button on the last step of checkout

---

locales/de.json
locales/en.json

Description:
--
QA-test: ST-2131
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.4.0-pr-220-9df4363e.zip

ST-2129: Fix localization for empty list view

---

client-app/router/routes/main.ts
client-app/ui-kit/components/pages/matcher.vue
content/pages/page.json

Description:
By slug(permalink) and current culture
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.5.0-pr-232-f9e16182.zip

feat(ST-2696): implement one request logic for seo info and for static content

---

client-app/pages/account/order-details.vue
client-app/shared/account/components/reorder-info.vue

Description:
--
QA-test: ST-2116
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.4.0-pr-223-3f2c1eba.zip

ST-2114: Disable reorder all button until its popup is showing

---

client-app/pages/account/orders.vue
client-app/pages/category.vue

Description:
--
QA-test: ST-2346
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.5.0-pr-238-3a562c7c.zip

fix(#2344): make mobile filters header behavior equals on category page and customer orders page

---

.gitignore
config/schemas/sections/cover-with-image.json
config/schemas/sections/header-settings.json
config/schemas/templates/home.json
content/templates/home.json

add ability to modify template settings
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.5.0-pr-242-e3fab785.zip

feat: add static sections to page builder settings

---

client-app/shared/catalog/components/product-price-block.vue
client-app/ui-kit/components/atoms/button/vc-button.vue
client-app/ui-kit/components/atoms/popover/vc-popover.vue
locales/de.json
locales/en.json

Description:
--
QA-test: ST-2273
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.5.0-pr-239-1c3fd2dd.zip

feat(ST-2270): Implement Send product to email

---

client-app/shared/account/components/sign-in-form.vue
locales/en.json

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.5.0-pr-241-ef4a8518.zip

feat(ST-2224): show the error message if user is locked

---

client-app/xapi/types.ts
config/schemas/sections/cover-with-image.json
config/schemas/templates/page.json
content/templates/home.json
package.json
yarn.lock

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.6.0-pr-248-7062700c.zip

Builder configs

---

client-app/router/index.ts
client-app/router/routes/main.ts
client-app/shared/account/components/account-navigation.vue
client-app/shared/layout/components/header/_internal/mobile-menu.vue
client-app/shims-router.d.ts

Description:
https://virtocommerce.atlassian.net/browse/ST-3046
--
QA-test: ST-3048
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.6.0-pr-251-d7aa5c1f.zip

ST-3046: Corporate block is displayed for the company user

---

client-app/pages/company/members.vue
client-app/router/routes/main.ts
client-app/shared/account/components/index.ts
client-app/shared/account/components/invite-member-dialog.vue
client-app/ui-kit/components/organisms/popup/vc-popup.vue
client-app/xapi/graphql/account/index.ts
client-app/xapi/graphql/account/mutations/inviteUser/index.ts
client-app/xapi/graphql/account/mutations/inviteUser/inviteUserMutation.graphql
locales/de.json
locales/en.json

Description:
https://virtocommerce.atlassian.net/browse/ST-2329
--
QA-test: ST-2331
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.6.0-pr-249-4f1c7510.zip

feat(ST-2329): added "Invite member" dialog

---

client-app/pages/account/lists.vue
client-app/shared/wishlists/components/wishlist-card.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-3066
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.6.0-pr-258-f18a0817.zip

feat(ST-3066): removed "Add to Cart" button from the list of Wish lists

---

locales/en.json

Fixed language in the EN localization file after performing localization testing through demo environment
Description:
Fixed language in the EN localization file after performing localization testing through demo environment
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.6.0-pr-254-bb7e1326.zip

docs: Fix language

---

client-app/core/constants.ts
client-app/pages/confirm-invitation.vue
client-app/pages/sign-up.vue
client-app/router/index.ts
client-app/router/routes/main.ts
client-app/shared/account/components/invite-member-dialog.vue
client-app/shared/account/composables/useUser.ts
client-app/xapi/graphql/account/index.ts
client-app/xapi/graphql/account/mutations/registerByInvitation/index.ts
client-app/xapi/graphql/account/mutations/registerByInvitation/registerByInvitationMutation.graphql
locales/de.json
locales/en.json

Description:
https://virtocommerce.atlassian.net/browse/ST-2963
--
QA-test: ST-2966
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.6.0-pr-256-ec12e846.zip

feat(ST-2963): registration by invitation

---

client-app/shared/fulfillmentCenters/components/branches-dialog.vue

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.6.0-pr-260-7da7083f.zip

fix: branches dialog. save button is disabled

---

client-app/builder-preview/BuilderPreview.ts
client-app/pages/blocks/image.vue
client-app/pages/blocks/text.vue
client-app/pages/static-page.vue
config/schemas/sections/header-settings.json
config/schemas/templates/page.json
templates/preview.liquid

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.6.0-pr-261-6bc93383.zip

feat: use meta data on static pages

---

client-app/pages/account/list-details.vue

Description:
--
QA-test: ST-2644
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.6.0-pr-263-8b2c63aa.zip

fix(wish list): hide "Add all products to cart" button

---

client-app/core/constants.ts

Description:
removed hard coded sorting for default searches (featured). It should be done by provide instead using either boosting or other means.
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.6.0-pr-250-d0b6b0e7.zip

enable for search provide sort

---

client-app/pages/account/list-details.vue
client-app/pages/account/lists.vue
client-app/shared/wishlists/components/delete-wishlist-product.vue
client-app/shared/wishlists/components/index.ts
client-app/shared/wishlists/components/wishlist-product-item-skeleton.vue
client-app/shared/wishlists/components/wishlist-product-item.vue
client-app/shared/wishlists/composables/useWishlists.ts
client-app/xapi/graphql/account/queries/getWishList/getWishlist.graphql
locales/de.json
locales/en.json

Description:
https://virtocommerce.atlassian.net/browse/ST-2738
--
QA-test: ST-2740
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.6.0-pr-264-687762dd.zip

fix(ST-2738): deleted product in the wish list

---

client-app/pages/sign-up.vue
client-app/shared/account/components/sign-in-form.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-2684
--
QA-test: ST-2686
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.6.0-pr-271-471c2c37.zip

fix(ST-2684): registration form

---

client-app/core/utilities/address/index.ts
client-app/pages/checkout.vue
client-app/pages/sign-up.vue
client-app/shared/account/components/sign-in-form.vue
client-app/shared/checkout/components/select-address-dialog.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-3156
--
QA-test: ST-3158
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.6.0-pr-273-0cc81763.zip

fix(ST-3156): selecting addresses on checkout page

---

client-app/builder-preview/BuilderPreview.ts

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.6.0-pr-270-a339d433.zip

feat: preview theme preferences

---

client-app/pages/category.vue
client-app/ui-kit/components/atoms/tooltip/vc-tooltip.vue
locales/de.json
locales/en.json

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.7.0-pr-275-7a4cdfba.zip

feat(st-3134): implement tooltips for in stock and branches filter checkboxes

---

client-app/shared/company/components/invite-member-dialog.vue
locales/de.json
locales/en.json

Description:
--
QA-test: ST-3062
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.7.0-pr-276-c695712e.zip

feat(st-3062): improve validation rules for invite contacts dialog fields

---

client-app/core/utilities/address/index.ts
client-app/pages/checkout.vue
client-app/pages/sign-up.vue
client-app/shared/account/components/sign-in-form.vue
client-app/shared/checkout/components/select-address-dialog.vue

Description:
--
QA-test: ST-3028
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.6.0-pr-274-78590120.zip

Fix: ST-3026, ST-2684, ST-3156

---

client-app/pages/category.vue
client-app/shared/catalog/components/products-filters.vue
locales/de.json
locales/en.json

Description:
--
QA-test: ST-3155
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.7.0-pr-280-17d4f692.zip

feat(ST-3152): align mobile filters according to design

---

client-app/shared/wishlists/components/wishlist-card.vue
locales/de.json
locales/en.json

Description:
https://virtocommerce.atlassian.net/browse/ST-2853
--
QA-test: ST-2855
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.7.0-pr-282-79a8d97d.zip

fix(ST-2853): product count text

---

client-app/router/index.ts

Description:
--
QA-test: ST-2916
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.7.0-pr-283-fcb17511.zip

fix(ST-2914): do not scroll to top after category filter is changed

---

client-app/pages/blocks/index.ts
client-app/pages/static-page.vue

Description:
--
QA-test:
Demo-test:

fix: merge errors

---

client-app/shared/company/components/invite-member-dialog.vue
locales/de.json
locales/en.json

Description:
--
QA-test: ST-3062
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.8.0-pr-291-4a0f99ee.zip

fix(st-3062): change max invite members value to 200

---

client-app/shared/layout/components/search-bar/search-bar.vue

Description:
--
QA-test: ST-3236
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.8.0-pr-294-2c4c695f.zip

fix(st-3234): fix search button behavior

---

client-app/pages/product-template.vue
client-app/pages/static-page.vue

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.8.0-pr-295-c4b04d38.zip

feat: use hidden property to hide blocks

---

client-app/shared/company/components/invite-member-dialog.vue

Description:
--
QA-test: ST-3062
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.8.0-pr-297-9302-93022a18.zip

fix(pt-9051): remove email duplicates from request

---

.idea/codeStyles/Project.xml
client-app/core/composables/index.ts
client-app/core/composables/useIdentityErrorTranslator.ts
client-app/core/utilities/common/index.ts
client-app/pages/confirm-invitation.vue
client-app/pages/sign-up.vue
client-app/shared/account/components/forgot-password-form.vue
client-app/shared/account/components/reset-password-form.vue
client-app/shared/account/composables/useUserOrdersFilter.ts
client-app/shared/account/types/index.ts
client-app/shared/company/components/invite-member-dialog.vue
client-app/xapi/graphql/account/mutations/registerByInvitation/registerByInvitationMutation.graphql
client-app/xapi/graphql/account/queries/checkEmailUniqueness/index.ts
locales/de.json
locales/en.json

Description:
https://virtocommerce.atlassian.net/browse/ST-3284
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.9.0-pr-306-c9d0-c9d0c0b6.zip

ST-3284: Add error translations to the registration and invitation confirmation pages

---

client-app/builder-preview/BuilderPreview.ts
client-app/pages/static-page.vue
client-app/ui-kit/components/pages/matcher.vue
client-app/ui-kit/ui-kit.d.ts

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.9.0-pr-305-d92a-d92a01a4.zip

feat: use get parameter in preview for builder

---

client-app/shared/catalog/components/category-selector.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-2787
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.9.0-pr-308-0e1e-0e1ed9d5.zip

fix: category selector

---

client-app/shared/catalog/components/discount-badge.vue
client-app/shared/catalog/components/product-details-template.vue
client-app/ui-kit/components/molecules/image-gallery/vc-image-gallery.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-3296
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.9.0-pr-309-2ef6-2ef6274e.zip

ST-3296: Fix discount badge

---

client-app/shared/cart/components/add-to-cart.vue
locales/de.json
locales/en.json

Description:
https://virtocommerce.atlassian.net/browse/ST-2763
--
QA-test: ST-2765
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.9.0-pr-310-5f0b-5f0b70db.zip

feat(ST-2763): add localization for min/max quantity

---

client-app/shared/checkout/components/order-summary.vue
client-app/shared/checkout/components/product-card.vue
client-app/xapi/graphql/fragments/lineItemFields.graphql
client-app/xapi/schema.json
client-app/xapi/types.ts

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.9.0-pr-311-dacc-dacc9ae5.zip

ST-3328: Actualize cart and checkout items prices and totals

---

client-app/pages/account/orders.vue
client-app/pages/catalog.vue
client-app/pages/company/members.vue
client-app/shared/account/components/index.ts
client-app/shared/account/components/page-toolbar-block.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-2344
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.9.0-pr-312-3329-332974d6.zip

ST-2344: Add sticky mobile search block on the "Orders" and "Members" pages

---

client-app/shared/checkout/components/product-card.vue

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.9.0-pr-315-deb3-deb39946.zip

ST-2491: Fix order items prices

---

client-app/pages/blocks/subscribe-form.vue
client-app/pages/static-page.vue
client-app/ui-kit/components/atoms/breadcrumbs/vc-breadcrumbs.vue
templates/preview.liquid

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.9.0-pr-316-e93e-e93e84f0.zip

fix: ui bugs in blocks

---

client-app/pages/account/addresses.vue
client-app/pages/account/list-details.vue
client-app/pages/company/info.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-3355
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.9.0-pr-318-3399-3399818a.zip

ST-3355: Adding account addresses after deleting all

---

client-app/shared/account/composables/useUserCheckoutDefaults.ts

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.10.0-pr-320-1fb2-1fb25782.zip

fix(checkout defaults): add migration

---

package.json
vite.config.ts
yarn.lock

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.10.0-pr-324-83cc-83ccab86.zip

build: add a proxy in dev mode to login on behalf

---

client-app/shared/static-content/components/dark-promo-text.vue
client-app/shared/static-content/components/products-block.vue
client-app/shared/static-content/components/text-block.vue
config/schemas/sections/products.json

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.10.0-pr-323-2522-252205ff.zip

fix: fix text block padding after header

---

client-app/shared/static-content/components/dark-promo-text.vue
client-app/shared/static-content/components/products-block.vue
client-app/shared/static-content/components/text-block.vue
config/schemas/sections/products.json

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.10.0-pr-325-91d2-91d26961.zip

fix: text block title

---

client-app/shared/layout/components/currency-selector/currency-selector.vue
client-app/shared/layout/components/header/_internal/bottom-header-link.vue
client-app/shared/layout/components/header/_internal/bottom-header.vue
client-app/shared/layout/components/header/_internal/mobile-menu.vue
client-app/shared/layout/components/language-selector/language-selector.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-3272
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.10.0-pr-328-b23a-b23a77b7.zip

fix: company name in header

---

client-app/core/utilities/address/index.ts
client-app/pages/checkout.vue
client-app/shared/checkout/components/select-address-dialog.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-3258
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.10.0-pr-329-e2bb-e2bb629e.zip

fix: the list of the user's addresses after creating the order

---

client-app/pages/catalog.vue
client-app/shared/catalog/composables/useCategories.ts
client-app/shared/catalog/utils/category-utils.ts
client-app/shared/layout/components/header/_internal/catalog-menu.vue
client-app/xapi/graphql/catalog/queries/searchCategories/index.ts
client-app/xapi/graphql/catalog/queries/searchCategories/searchCategoriesQuery.graphql

Description:
https://virtocommerce.atlassian.net/browse/ST-3146
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.10.0-pr-331-6be9-6be93987.zip

fix: sort categories in the "Catalog" menu

---

client-app/builder-preview/builder-preview.plugin.ts
client-app/core/composables/useThemeContext.ts
client-app/core/types/index.ts
client-app/core/utilities/common/index.ts
client-app/shared/layout/components/header/_internal/bottom-header-link.vue
client-app/shared/layout/components/header/_internal/bottom-header.vue
client-app/shared/layout/components/header/_internal/mobile-header.vue
client-app/shared/layout/components/header/_internal/mobile-menu.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-2926
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.10.0-pr-332-ac0b-ac0b2f0b.zip

fix: counter in mobile menu

---

client-app/core/types/index.ts
client-app/router/routes/account.ts
config/settings_data.json

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.11.0-pr-334-02fd-02fd46b3.zip

feat: add route for quotes

---

.github/workflows/deploy.yml
client-app/public/robots.txt

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.11.0-pr-336-98eb-98eb0104.zip

ci: fix deployment to demo env

---

client-app/pages/account/quotes.vue
client-app/pages/checkout.vue
client-app/router/routes/account.ts

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.11.0-pr-338-b071-b071e1d4.zip

fix: create quote from cart

---

client-app/builder-preview/builder-preview.plugin.ts
config/schemas/shared/title.json
config/schemas/templates/page.json

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.11.0-pr-342-b4fb-b4fb5e9b.zip

feat: add builder messages handlers

---

client-app/ui-kit/components/atoms/input/vc-input.vue

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.11.0-pr-343-5d0a-5d0aa36b.zip

feat: skip show password button focus by tab

---

client-app/pages/reset-password.vue
client-app/shared/account/components/reset-password-form.vue
client-app/shared/company/components/invite-member-dialog.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-3324
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.11.0-pr-344-9c45-9c45d090.zip

feat(invite user dialog, reset password page): add translation of identity errors by code

---

client-app/shared/catalog/components/category-selector.vue

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.11.0-pr-345-15e0-15e0f207.zip

feat: change category tree header background color on hover for desktop

---

client-app/shared/layout/components/currency-selector/currency-selector.vue
client-app/shared/layout/components/language-selector/language-selector.vue

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.11.0-pr-347-ded4-ded4803e.zip

fix: highlight currency/language selector items on hover

---

client-app/pages/company/members.vue

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.12.0-pr-349-259e-259e703c.zip

fix: blocking your own account on mobile view

---

client-app/pages/company/members.vue
client-app/shared/company/composables/useOrganizationContacts.ts
client-app/shared/company/utils/index.ts
client-app/shared/layout/components/header/_internal/mobile-menu-link.vue
client-app/xapi/graphql/organization/index.ts
client-app/xapi/graphql/organization/mutations/removeMemberFromOrganization/index.ts
client-app/xapi/graphql/organization/mutations/removeMemberFromOrganization/removeMemberFromOrganization.graphql
client-app/xapi/types.ts
package.json
tsconfig.json

Description:
https://virtocommerce.atlassian.net/browse/ST-2980
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.13.0-pr-352-4bd4-4bd45de8.zip

feat: add functionality to remove a member from organization

---

client-app/pages/company/info.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-3165
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.13.0-pr-354-d170-d170bf5f.zip

feat: added editing company name for organization maintainer

---

.npmrc
client-app/pages/account/addresses.vue
client-app/shared/checkout/components/add-or-update-address-dialog.vue
client-app/shared/company/components/add-or-update-company-address-dialog.vue
client-app/shared/layout/components/footer/vc-footer.vue
client-app/ui-kit/components/molecules/address-form/vc-address-form.vue
locales/de.json
locales/en.json

Description:
https://virtocommerce.atlassian.net/browse/ST-3225
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.15.0-pr-356-a815-a81556b7.zip

fix: create/edit company address dialog

---

client-app/shared/static-content/components/text-block.vue
config/schemas/sections/text.json

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.15.0-pr-361-2b5c-2b5c7044.zip

feat: change text block content type to markdown

---

client-app/shared/cart/utils/index.ts

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.15.0-pr-363-9bda-9bda488d.zip

fix: reorder deleted product

---

client-app/shared/catalog/components/product-skeleton-grid.vue
client-app/shared/catalog/components/product-skeleton-list.vue

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.15.0-pr-365-c9f9-c9f9667c.zip

feat: implement new design for product card skeletons

---

.idea/codeStyles/Project.xml
.idea/vc-theme-b2b-vue.iml
layout/500.liquid
layout/designer-preview.liquid
layout/theme.liquid
snippets/global-liquid-variables.liquid
snippets/google-tag.liquid
snippets/head-content.liquid
templates/index.liquid
templates/preview.liquid

Description:
https://virtocommerce.atlassian.net/browse/ST-3550
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.16.0-pr-369-c5d4-c5d42671.zip

feat: add Google Analytics script

---

gulpfile.js

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.16.0-pr-370-2008-20087c20.zip

build: add `snippets` folder in artefact

---

client-app/core/composables/index.ts
client-app/core/composables/useAppContext.ts
client-app/core/composables/useGoogleAnalytics.ts
client-app/core/types/app-context.ts
client-app/core/types/index.ts
client-app/pages/account/list-details.vue
client-app/pages/catalog.vue
client-app/pages/compare-products.vue
client-app/pages/product.vue
client-app/shared/layout/components/search-bar/search-bar.vue
client-app/xapi/graphql/account/queries/getWishList/getWishlist.graphql
index.html
layout/500.liquid
package.json
snippets/global-liquid-variables.liquid
snippets/google-tag.liquid
snippets/head-content.liquid
tsconfig.json
vite.config.ts
yarn.lock

Description:
https://virtocommerce.atlassian.net/browse/ST-3586
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.16.0-pr-371-2b71-2b71b845.zip

feat: add Google Analytics `view_item_list` event

---

client-app/core/composables/useGoogleAnalytics.ts
client-app/pages/account/list-details.vue
client-app/pages/catalog.vue
client-app/pages/compare-products.vue
client-app/pages/product.vue
client-app/shared/catalog/components/carousel-product-card.vue
client-app/shared/catalog/components/display-products.vue
client-app/shared/catalog/components/product-card-grid.vue
client-app/shared/catalog/components/product-card-list.vue
client-app/shared/layout/components/search-bar/_internal/search-bar-product-card.vue
client-app/shared/layout/components/search-bar/search-bar.vue
client-app/shared/wishlists/components/wishlist-product-item.vue
client-app/ui-kit/components/atoms/button/vc-button.vue
client-app/xapi/graphql/catalog/queries/getSearchResults/getSearchResultsQuery.graphql
client-app/xapi/graphql/catalog/queries/searchRelatedProducts/searchRelatedProducts.graphql

Description:
https://virtocommerce.atlassian.net/browse/ST-3590
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.16.0-pr-372-505e-505e74b0.zip

feat: add Google Analytics `select_item` event

---

client-app/core/composables/useGoogleAnalytics.ts
client-app/pages/product.vue
client-app/shared/catalog/composables/useBreadcrumbs.ts

Description:
https://virtocommerce.atlassian.net/browse/ST-3594
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.16.0-pr-373-cfdc-cfdcffe4.zip

feat: add Google Analytics `view_item` event

---

client-app/pages/checkout.vue

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.16.0-pr-375-5ace-5acebc9b.zip

fix: redirect to `Order complete` page

---

README.md
package.json

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.16.0-pr-377-bcb8-bcb8584c.zip

docs: update README.md

---

builder-preview.html
client-app/shared/static-content/components/demo-product-list.vue
client-app/shared/static-content/components/index.ts
config/schemas/sections/demo-product-list.json
config/schemas/templates/page.json

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.16.0-pr-376-c792-c7922c07.zip

feat: add control from doc

---

client-app/core/composables/useGoogleAnalytics.ts
client-app/pages/checkout.vue

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.17.0-pr-379-dfce-dfce7dae.zip

feat: add view_cart GA event

---

client-app/pages/sign-in.vue
client-app/router/index.ts
client-app/shared/cart/composables/useCart.ts
client-app/ui-kit/components/atoms/markdown-render/vc-markdown-render.vue
client-app/xapi/client.ts

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.17.0-pr-382-ba2b-ba2bb552.zip

small fixes

---

client-app/core/utilities/common/index.ts
client-app/pages/account/edit-quote.vue
client-app/pages/checkout.vue

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.17.0-pr-386-d68d-d68d7cac.zip

fix: quote request fixes

---

client-app/pages/checkout.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-3683
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.17.0-pr-388-39b6-39b62142.zip

fix: save addresses to quote from cart

---

client-app/builder-preview/builder-preview.plugin.ts
client-app/builder-preview/scroll-to-element.vue

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.17.0-pr-389-2045-2045913b.zip

feat: add scroll to block in preview

---

client-app/core/composables/useGoogleAnalytics.ts
client-app/pages/checkout.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-3618
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.17.0-pr-390-476f-476f6a63.zip

feat: add 'add_shipping_info' Google Analytics event

---

client-app/router/index.ts

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.18.0-pr-394-76c9-76c998dc.zip

fix: remove smooth scrolling for catalog navigation

---

client-app/router/routes/checkout.ts
client-app/router/routes/main.ts
client-app/shared/layout/components/header/_internal/bottom-header.vue
client-app/shared/layout/components/header/_internal/mobile-menu.vue

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.18.0-pr-396-4436-4436b268.zip

fix: cart route id

---

client-app/shared/layout/components/search-bar/search-bar.vue

Description:
Search field reset button is different than in the header
https://virtocommerce.atlassian.net/browse/ST-2826
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.18.0-pr-399-636e-636e0108.zip

Search field reset button

---

client-app/core/utilities/common/index.ts
client-app/pages/account/edit-quote.vue

Description:
Select the same address from the list then one address overwrites the other
https://virtocommerce.atlassian.net/browse/ST-3738
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.18.0-pr-398-cf60-cf60d3d4.zip

Quotes same address issue

---

client-app/core/composables/useGoogleAnalytics.ts
client-app/shared/wishlists/components/add-to-wishlists-dialog.vue

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.18.0-pr-397-d539-d53980eb.zip

feat: add GA add_to_wishlist event

---

client-app/pages/confirm-email.vue

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.18.0-pr-402-4349-434964ff.zip

fix: fix items align on email confirmation page for mobile

---

client-app/core/composables/useGoogleAnalytics.ts
client-app/pages/cart.vue
client-app/xapi/graphql/cart/queries/getMyCart/getMyCartQuery.graphql

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.18.0-pr-405-fe72-fe7298dd.zip

feat: add GA payment info event

---

client-app/pages/account/order-details.vue
client-app/pages/cart.vue
client-app/pages/checkout.vue.temp
client-app/shared/checkout/components/cart-line-items.vue
client-app/xapi/graphql/fragments/lineItemFields.graphql
locales/de.json
locales/en.json

Description:
https://virtocommerce.atlassian.net/browse/ST-3699
1) Add breadcrumbs
2) fix title
3) fix print button position
4) fix lineitems table
5) add group by vendor
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.18.0-pr-403-4289-4289c28f.zip

feat: add group by vendor in cart

---

client-app/shared/company/composables/useOrganizationAddresses.ts

Description:
https://virtocommerce.atlassian.net/browse/ST-3185
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.18.0-pr-407-a674-a674a897.zip

Load all addresses on init

---

client-app/shared/checkout/components/cart-line-items.vue

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.18.0-pr-409-4a90-4a90a142.zip

fix: fix cart informers duplicates

---

locales/de.json

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.18.0-pr-411-e9b0-e9b0417e.zip

fix: update german locale for edit quote page save changes button

---

client-app/pages/account/edit-quote.vue

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.18.0-pr-412-2ec0-2ec0d028.zip

fix: change submit quote button behavior

---

builder-preview.html
client-app/core/types/app-context.ts
client-app/core/types/index.ts
client-app/router/index.ts
index.html
snippets/global-liquid-variables.liquid
snippets/head-content.liquid

Description:
https://virtocommerce.atlassian.net/browse/ST-3648
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.18.0-pr-414-0491-0491de40.zip

feat: setting up anonymous access

---

client-app/shared/wishlists/components/wishlist-line-item.vue

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.19.0-pr-426-8a2e-8a2edebf.zip

fix: wishlist line item mobile price

---

client-app/pages/cart.vue
client-app/pages/checkout/index.vue
client-app/ui-kit/components/atoms/loader/vc-loader.vue
client-app/ui-kit/components/molecules/loader-overlay/vc-loader-overlay.vue

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.19.0-pr-433-fd42-fd42061a.zip

fix: vc-loader-overlay

---

client-app/shared/layout/components/header/vc-header.vue
client-app/shared/layout/components/secure-layout/secure-layout.vue
client-app/ui-kit/components/molecules/layout-with-right-sidebar/vc-layout-with-right-sidebar.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-2751
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.19.0-pr-437-e6f2-e6f20295.zip

style: implement sticky header

---

client-app/core/types/index.ts
client-app/shared/layout/components/search-bar/search-bar.vue
config/settings_data.json

Description:
https://virtocommerce.atlassian.net/browse/ST-3795
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.19.0-pr-435-65fc-65fc1180.zip

feat: add setting for search input chars limit

---

client-app/core/types/line-items.ts
client-app/shared/catalog/components/vendor.vue
client-app/ui-kit/components/molecules/vendor/vc-vendor.vue
client-app/xapi/schema.json
client-app/xapi/types.ts

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.20.0-pr-438-703b-703b5ddc.zip

fix: vendor typing

---

client-app/router/index.ts
client-app/router/routes/account.ts
client-app/router/routes/main.ts
client-app/shared/account/components/account-shell.vue
client-app/shims-router.d.ts

Description:
https://virtocommerce.atlassian.net/browse/ST-3648
https://virtocommerce.atlassian.net/browse/ST-3834
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.20.0-pr-440-ba28-ba2881d0.zip

fix: access to public pages when anonymous access is disabled

---

client-app/core/utilities/line-items/index.ts
client-app/shared/account/components/order-line-items.vue
client-app/shared/cart/components/cart-line-item.vue
client-app/shared/cart/components/cart-line-items.vue
client-app/xapi/graphql/fragments/lineItemFields.graphql
client-app/xapi/graphql/fragments/orderLineItemFields.graphql

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.20.0-pr-443-acf2-acf2596e.zip

fix: deleted product breakes cart logic

---

client-app/pages/account/order-details.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-3759
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.20.0-pr-444-4349-4349d11a.zip

style: implement design && layout fixes to order-details

---

client-app/shared/catalog/components/product-card-list.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-2850
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.20.0-pr-445-92d2-92d2c69c.zip

fix: fix styles for large price on product list view

---

client-app/shared/checkout/composables/useCheckout.ts

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.20.0-pr-447-856a-856a9ed8.zip

feat: ga begin checkout event

---

client-app/shared/cart/components/gifts-section.vue
client-app/shared/checkout/components/accepted-gifts.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-3759
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.20.0-pr-446-5082-50820349.zip

style: implement design to accepted gifts

---

client-app/shared/checkout/composables/useCheckout.ts

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.20.0-pr-449-cfce-cfcee7f2.zip

fix: restore ga events for shipping and payment methods

---

package.json
yarn.lock

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.21.0-pr-453-5624-5624260a.zip

fix: vue-tsc version

---

client-app/ui-kit/components/molecules/select/vc-select.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-4006
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.22.0-pr-454-c9cb-c9cba394.zip

feat: implement readonly mode to VcSelect

---

README.md
client-app/core/composables/index.ts
client-app/core/composables/usePageHead.ts
client-app/core/types/index.ts
client-app/pages/account/edit-quote.vue
client-app/shared/checkout/composables/useCheckout.ts
client-app/shims-vue.d.ts
client-app/vue-router.d.ts
client-app/vue.d.ts
client-app/xapi/graphql/cart/mutations/removeCart/index.ts
client-app/xapi/schema.json
client-app/xapi/types.ts
package.json
tsconfig.json
vite.config.ts
yarn.lock

Description:
https://virtocommerce.atlassian.net/browse/ST-4041
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.22.0-pr-456-64bd-64bd6470.zip

fix: graphQl `removeCart` mutation

---

client-app/core/composables/useGoogleAnalytics.ts
client-app/shared/checkout/composables/useCheckout.ts

Description:
https://virtocommerce.atlassian.net/browse/ST-4027
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.22.0-pr-459-ffd6-ffd6593c.zip

fix: default settings are not applied at checkout

---

layout/500.liquid
layout/designer-preview.liquid
layout/empty.liquid
layout/theme.liquid
snippets/global-liquid-variables.liquid
snippets/global-variables.liquid

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.22.0-pr-460-7e69-7e696375.zip

fix: error if there is no "Google Analytics 4" module

---

client-app/shared/catalog/components/products-filters.vue
client-app/ui-kit/components/atoms/checkbox/vc-checkbox.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-4058
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.23.0-pr-465-b37c-b37c5a32.zip

fix: product filter styles

---

client-app/pages/account/order-payment.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-3959
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.23.0-pr-466-67e7-67e7c7ed.zip

fix: styles on order payment results page

---

client-app/ui-kit/components/atoms/filter-card/vc-filter-card.vue

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.23.0-pr-468-7418-7418b022.zip

fix: catalog filter card styles

---

client-app/pages/account/order-details.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-4044
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.23.0-pr-469-1643-16430d62.zip

feat: remove payment details from order-details

---

client-app/pages/account/order-details.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-2838
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.23.0-pr-470-7d37-7d37faa4.zip

fix: method icons url

---

client-app/shared/cart/components/cart-line-item.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-3978
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.23.0-pr-474-b752-b752d7c4.zip

fix: change empty quantity input behavior

---

.vscode/settings.json
client-app/core/types/index.ts
client-app/shared/checkout/components/select-address-modal.vue
client-app/shared/checkout/composables/useCheckout.ts
client-app/shared/company/composables/useOrganizationAddresses.ts
locales/en.json

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.23.0-pr-473-f5ca-f5ca51c1.zip

feat: show only company addresses for corporate users

---

client-app/shared/cart/components/cart-line-item.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-3978
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.23.0-pr-478-60f9-60f95d10.zip

fix: delay in saving quantity changes

---

client-app/pages/account/checkout-defaults.vue
client-app/pages/account/order-details.vue
client-app/pages/account/order-payment.vue
client-app/pages/checkout/payment.vue
client-app/pages/checkout/review.vue
client-app/shared/checkout/components/billing-details-section.vue
client-app/shared/checkout/components/select-payment-method-modal.vue
client-app/shared/checkout/components/shipping-details-section.vue
client-app/shared/layout/components/search-bar/search-bar.vue
locales/en.json

Description:
https://virtocommerce.atlassian.net/browse/ST-3974
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.23.0-pr-479-d523-d5233416.zip

fix: delete processing of the Empty or whitespace search request

---

client-app/ui-kit/components/molecules/input/vc-input.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-4098
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.23.0-pr-484-1cdc-1cdc245b.zip

fix: input focus outline on firefox

---

client-app/shared/static-content/components/index.ts
client-app/shared/static-content/components/product-assets.vue
config/schemas/blocks/product-assets.json
config/schemas/sections/product-info.json

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.23.0-pr-483-7f99-7f997bdf.zip

feat: add product-assets block

---

client-app/core/types/addresses.ts
client-app/core/utilities/address/index.ts
client-app/pages/account/profile.vue
client-app/pages/company/info.vue
client-app/pages/compare-products.vue
client-app/pages/confirm-invitation.vue
client-app/pages/reset-password.vue
client-app/pages/sign-up.vue
client-app/shared/account/components/forgot-password-form.vue
client-app/shared/account/components/reset-password-form.vue
client-app/shared/account/components/sign-in-form.vue
client-app/shared/account/composables/useUserAddresses.ts
client-app/shared/account/composables/useUserCheckoutDefaults.ts
client-app/shared/cart/components/add-to-cart.vue
client-app/shared/checkout/components/select-address-modal.vue
client-app/shared/company/components/invite-member-dialog.vue
client-app/shared/payment/components/bank-card-form.vue
client-app/shared/wishlists/components/add-or-update-wishlist-modal.vue
client-app/ui-kit/components/molecules/address-form/vc-address-form.vue
locales/en.json
package.json
yarn.lock

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.24.0-pr-485-4ba5-4ba52876.zip

refactor: form validation

---

client-app/pages/account/addresses.vue
client-app/pages/account/edit-quote.vue
client-app/pages/account/order-payment.vue
client-app/shared/checkout/components/index.ts
client-app/shared/checkout/composables/useCheckout.ts
client-app/ui-kit/components/organisms/add-or-update-address-modal/vc-add-or-update-address-modal.vue
client-app/ui-kit/components/organisms/index.ts
locales/en.json

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.24.0-pr-487-c1d7-c1d7b218.zip

feat: add or update address modal on account addresses page

---

client-app/pages/account/orders.vue

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.24.0-pr-488-0d9e-0d9efffc.zip

feat: open order details page in separate tab

---

client-app/shared/cart/components/add-bulk-items-to-cart-results-modal.vue
locales/en.json

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.24.0-pr-489-799f-799f4093.zip

feat: add view cart button on reorder modal

---

client-app/shared/layout/components/header/_internal/mobile-menu.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-2901
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.24.0-pr-496-bce2-bce29d6e.zip

fix: mobile menu break words

---

client-app/pages/index.vue
client-app/shared/catalog/components/product/assets.vue
client-app/ui-kit/components/pages/matcher.vue

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.24.0-pr-498-7eb9-7eb9b8ed.zip

PT-11019: use full path to search seo object

---

client-app/pages/account/dashboard.vue
client-app/ui-kit/components/organisms/table/vc-table.vue

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.25.0-pr-499-5625-5625dfe2.zip

refactor: vc-table

---

client-app/ui-kit/components/atoms/address-line/vc-address-line.vue

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.25.0-pr-503-f289-f2898830.zip

refactor: vc-address-line

---

client-app/ui-kit/components/atoms/button/vc-button.vue

Description:
--
QA-test:
Demo-test:

refactor: vc-button

---

client-app/shared/catalog/components/product/properties.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-4238
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.25.0-pr-514-5f83-5f833192.zip

fix: product details properties

---

client-app/ui-kit/components/atoms/input-details/vc-input-details.stories.ts
client-app/ui-kit/components/atoms/input-details/vc-input-details.vue
client-app/ui-kit/components/molecules/input/vc-input.vue
client-app/ui-kit/components/molecules/select/vc-select.vue
client-app/ui-kit/components/molecules/textarea/vc-textarea.vue
client-app/ui-kit/components/organisms/add-to-cart/vc-add-to-cart.vue

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.25.0-pr-517-84fe-84fef567.zip

refactor: vc-add-to-cart and vc-input

---

client-app/core/composables/index.ts
client-app/core/composables/useCartValidationErrorTranslator.ts
client-app/core/composables/useIdentityErrorTranslator.ts
client-app/core/composables/useValidationErrorTranslator.ts
client-app/shared/cart/components/cart-line-items.vue
locales/en.json

Description:
add validation errors localization
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.26.0-pr-516-8276-82760001.zip

feat: add translations of cart validation errors

---

client-app/ui-kit/components/molecules/address-form/vc-address-form.vue
locales/en.json

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.27.0-pr-523-0c58-0c58e7d4.zip

feat: change email label on address form

---

client-app/core/utilities/line-items/index.ts
client-app/pages/compare-products.vue
client-app/shared/wishlists/utilities/index.ts
client-app/xapi/graphql/account/queries/getWishList/getWishlist.graphql
client-app/xapi/graphql/fragments/orderLineItemFields.graphql
client-app/xapi/graphql/fragments/quoteLineItemFields.graphql

Description:
https://virtocommerce.atlassian.net/browse/ST-4176
https://virtocommerce.atlassian.net/browse/ST-4180
https://virtocommerce.atlassian.net/browse/ST-4184
https://virtocommerce.atlassian.net/browse/ST-4192
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.27.0-pr-524-4612-46126ed8.zip

fix: boolean value of product property on order, quote, wishlist and compare page

---

client-app/core/types/theme-config.ts
client-app/shared/catalog/composables/useProducts.ts
config/settings_data.json

Description:
https://virtocommerce.atlassian.net/browse/ST-4220
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.27.0-pr-525-6470-6470ec1e.zip

feat: add setting for sorting product filters

---

config/settings_data.json

Description:
--
QA-test:
Demo-test:

Multi-step: false

---

config/settings_data.json

Description:
--
QA-test:
Demo-test:

product_filters_sorting - true

---

config/settings_data.json

Description:
--
QA-test:
Demo-test:

"product_filters_sorting_direction": "desc"

---

client-app/pages/checkout/payment.vue
client-app/shared/checkout/composables/useCheckout.ts

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.27.0-pr-530-f270-f2702b3c.zip

fix: fix checkout ui issues

---

client-app/xapi/graphql/account/queries/getWishList/getWishlist.graphql
client-app/xapi/graphql/account/queries/getWishList/index.ts
client-app/xapi/schema.json
client-app/xapi/types.ts
yarn.lock

Description:
https://virtocommerce.atlassian.net/browse/ST-4294
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.27.0-pr-533-f586-f586ec97.zip

fix: localization of product properties in the wish list

---

client-app/shared/layout/components/search-bar/search-bar.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-4287
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.28.0-pr-534-cfeb-cfeb0dc2.zip

fix: search-bar dropdown inner scroll

---

client-app/ui-kit/components/templates/category/vc-category.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-4326
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.28.0-pr-541-663d-663dd523.zip

feat: remove “0 results” text when loading is processed

---

client-app/shared/catalog/components/products-filters.vue
client-app/ui-kit/components/atoms/filter-card/vc-filter-card.vue
client-app/ui-kit/components/templates/category/vc-category.vue

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.28.0-pr-540-ec0e-ec0e8e19.zip

feat: hide catalog sidebar local search

---

client-app/pages/product.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-4314
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.28.0-pr-542-a35c-a35ced31.zip

feat: add catalog link to product breadcrumbs

---

client-app/shared/catalog/utils/search-utils.ts

Description:
https://virtocommerce.atlassian.net/browse/ST-4290
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.28.0-pr-543-d944-d9443290.zip

feat: use filter 'availability:InStock'

---

client-app/pages/catalog.vue
client-app/pages/category.vue
client-app/pages/search.vue
client-app/shared/catalog/components/category.vue
client-app/shared/catalog/components/index.ts
client-app/ui-kit/components/index.ts
client-app/ui-kit/components/templates/index.ts

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.28.0-pr-546-b455-b455518f.zip

refactor(UIKit): move VcCategory component

---

client-app/shared/cart/components/add-to-cart.vue

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.30.0-pr-556-82fd-82fdf6d0.zip

fix: fix add to cart component

---

client-app/core/types/index.ts
client-app/core/types/quote-status.ts
client-app/core/types/theme-config.ts
client-app/pages/account/quotes.vue
client-app/shared/account/components/index.ts
client-app/shared/account/components/quote-status.vue
config/settings_data.json

Description:
https://virtocommerce.atlassian.net/browse/ST-3546
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.31.0-pr-558-724c-724ca3cb.zip

feat: implement quote-status component

---

client-app/pages/account/dashboard.vue

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.31.0-pr-560-75cb-75cba75b.zip

feat: update dashboard orders statuses appearance

---

client-app/pages/account/order-details.vue

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.31.0-pr-561-de5d-de5d681d.zip

feat: change order status badge on account order details page

---

client-app/pages/account/order-details.vue

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.31.0-pr-562-6819-6819248f.zip

feat: change text label from creates date to created date on order details page

---

client-app/pages/account/edit-quote.vue
locales/en.json

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.31.0-pr-563-a193-a193a676.zip

feat: add notification after saving quote changes

---

config/settings_data.json

Description:
--
QA-test:
Demo-test:

Add statuses Processing and New for Quotes

---

client-app/shared/catalog/components/facet-values.vue

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.31.0-pr-565-d656-d656122f.zip

fix: make facet search case insensitive

---

client-app/ui-kit/components/molecules/quantity/vc-quantity.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-4413
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.31.0-pr-567-f706-f7069de1.zip

fix(vc-quantity): forbid e, negative and floating point numbers

---

tsconfig.json

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.31.0-pr-554-1576-15765d3c.zip

fix: tsconfig syntax issue with trailing comma

---

client-app/shared/cart/components/products-section.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-4416
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.31.0-pr-566-7016-7016f659.zip

fix: show mobile clear cart button

---

client-app/shared/cart/components/add-to-cart.vue

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.30.0-pr-557-eec9-eec92dc7.zip

fix: handle blur on add-to-cart

---

client-app/pages/demo-landing.vue
client-app/shared/static-content/components/products-block.vue

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.31.0-pr-571-ecf0-ecf0f328.zip

fix: product cards at home page for mobile

---

client-app/core/types/theme-config.ts
client-app/shared/catalog/components/category.vue
client-app/xapi/graphql/catalog/queries/getCategory/index.ts
config/settings_data.json

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.31.0-pr-572-629b-629be94a.zip

feat: hide empty categories at catalog category selector

---

client-app/pages/compare-products.vue

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.31.0-pr-573-dd1d-dd1d42b6.zip

feat: display digital products in compare list

---

config/settings_data.json

Description:
--
QA-test:
Demo-test:

fix: quote statuses

---

client-app/public/robots.txt

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.32.0-pr-577-a173-a1736209.zip

chore: test CI

---

config/settings_data.json

Description:
--
QA-test:
Demo-test:

 catalog_menu_old logic

---

client-app/core/composables/useNavigations.ts
client-app/core/types/menu.ts
client-app/core/utilities/menu/index.ts
client-app/shared/layout/components/header/_internal/mobile-menu-link.vue
client-app/shared/layout/components/header/_internal/mobile-menu.vue
config/menu.json
locales/en.json

Description:
https://virtocommerce.atlassian.net/browse/ST-3465
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.32.0-pr-578-14e7-14e7a4ec.zip

feat: add link to all products of current category in mobile menu

---

config/settings_data.json

Description:
--
QA-test:
Demo-test:

Link_list_null

---

client-app/pages/account/edit-quote.vue
client-app/shared/account/composables/useUser.ts
client-app/shared/checkout/composables/useCheckout.ts

Description:
https://virtocommerce.atlassian.net/browse/ST-4211
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.32.0-pr-583-cc38-cc3823d7.zip

feat: separate personal and corporate addresses on edit quote page

---

client-app/shared/checkout/components/select-address-modal.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-4433
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.32.0-pr-584-0aac-0aac8aff.zip

feat: make address record readable on select address modal

---

client-app/shared/checkout/components/select-address-modal.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-4433
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.32.0-pr-588-faea-faea5295.zip

fix: personal address appearance

---

client-app/core/composables/useNavigations.ts
client-app/core/utilities/search/facets.ts
client-app/shared/catalog/components/category.vue
client-app/xapi/graphql/catalog/queries/searchProducts/index.ts

Description:
https://virtocommerce.atlassian.net/browse/ST-4456
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.32.0-pr-587-52ae-52aea4ae.zip

fix: hide products with zero price with different currencies

---

client-app/shared/layout/components/footer/vc-footer.vue
client-app/ui-kit/components/molecules/item-price/vc-item-price.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-4423?focusedCommentId=61968
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.32.0-pr-589-de27-de271381.zip

fix: print layout

---

client-app/assets/styles/main.scss
client-app/shared/layout/components/footer/vc-footer.vue
client-app/shared/static-content/components/product-info.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-4487
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.32.0-pr-591-d1dd-d1ddf8ed.zip

fix: a5 printing issue

---

client-app/router/routes/account.ts
client-app/shared/account/components/account-navigation.vue
client-app/shared/layout/components/header/_internal/mobile-menu.vue
config/menu.json

Description:
https://virtocommerce.atlassian.net/browse/ST-3842
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.32.0-pr-593-fccd-fccdacc1.zip

feat: hide account menu addresses item for a corporate customer

---

client-app/pages/account/addresses.vue
client-app/pages/company/info.vue
locales/en.json

Description:
https://virtocommerce.atlassian.net/browse/ST-2597
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.32.0-pr-594-2aa6-2aa65d64.zip

feat: show the theme modal cobfirmation modal on personal address delete

---

client-app/shared/account/components/sign-in-form.vue
locales/en.json

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.32.0-pr-598-217f-217f004b.zip

fix: login form

---

client-app/pages/account/edit-quote.vue
client-app/pages/account/profile.vue
client-app/pages/bulk-order.vue
client-app/pages/cart.vue
client-app/pages/checkout/billing.vue
client-app/pages/checkout/review.vue
client-app/pages/checkout/shipping.vue
client-app/pages/confirm-invitation.vue
client-app/pages/sign-up.vue
client-app/shared/account/components/forgot-password-form.vue
client-app/shared/account/components/quote-line-items.vue
client-app/shared/account/components/reset-password-form.vue
client-app/shared/account/components/sign-in-form.vue
client-app/shared/cart/components/cart-line-items.vue
client-app/shared/company/components/invite-member-dialog.vue
client-app/shared/wishlists/components/wishlist-line-items.vue
client-app/ui-kit/components/atoms/alert/vc-alert.stories.ts
client-app/ui-kit/components/atoms/alert/vc-alert.vue
client-app/ui-kit/components/molecules/line-item/vc-line-item.stories.ts
client-app/ui-kit/components/molecules/line-items/vc-line-items.stories.ts

Description:
https://virtocommerce.atlassian.net/browse/ST-4492
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.32.0-pr-601-80ff-80ff2f2a.zip

feat: implement vc-alert design

---

client-app/pages/account/checkout-defaults.vue
client-app/pages/account/dashboard.vue
client-app/pages/account/lists.vue
client-app/pages/account/orders.vue
client-app/pages/account/profile.vue
client-app/pages/account/quotes.vue
client-app/pages/cart.vue
client-app/pages/checkout/index.vue
client-app/shared/account/components/page-toolbar-block.vue
client-app/shared/wishlists/components/wishlist-card.vue
client-app/ui-kit/components/atoms/container/vc-container.vue
client-app/ui-kit/components/molecules/layout-with-right-sidebar/vc-layout-with-right-sidebar.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-4246
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.32.0-pr-602-c46c-c46c3992.zip

fix: vc-container paddings

---

client-app/shared/account/components/order-line-items.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-3982
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.32.0-pr-604-1f51-1f51b9d7.zip

feat: update order-line-items

---

client-app/ui-kit/components/atoms/button/vc-button.vue
client-app/ui-kit/components/molecules/input/vc-input.vue

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.32.0-pr-607-1fa4-1fa4745e.zip

fix: buttons

---

client-app/ui-kit/components/organisms/popup/vc-popup.vue

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.32.0-pr-609-f500-f5005edd.zip

fix: vc-popup ios issue

---

client-app/ui-kit/components/atoms/input-details/vc-input-details.stories.ts
client-app/ui-kit/components/atoms/label/vc-label.stories.ts
client-app/ui-kit/components/molecules/input/vc-input.stories.ts
client-app/ui-kit/components/molecules/quantity/vc-quantity.stories.ts
client-app/ui-kit/components/molecules/select/vc-select.stories.ts

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.32.0-pr-610-b556-b5562a78.zip

fix: stories names sonar issues

---

client-app/ui-kit/components/molecules/quantity/vc-quantity.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-4471
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.32.0-pr-612-26a6-26a678dd.zip

fix: prevent exponent input for cart items quantity fields

---

client-app/shared/cart/components/add-bulk-items-to-cart-results-modal.vue
locales/en.json

Description:
https://virtocommerce.atlassian.net/browse/ST-3454
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.32.0-pr-613-d5ca-d5cac947.zip

feat: print from add-bulk-items-to-cart-results-modal

---

client-app/App.vue
client-app/broadcast.ts
client-app/core/api/graphql/client.ts
client-app/core/utilities/common/index.ts
client-app/pages/sign-in.vue
client-app/router/index.ts
client-app/shared/account/composables/useUser.ts
client-app/shared/broadcast/composables/index.ts
client-app/shared/broadcast/composables/useBroadcast.ts
client-app/shared/broadcast/index.ts
client-app/shared/broadcast/types/index.ts
client-app/shared/broadcast/utils/events.ts
client-app/shared/broadcast/utils/index.ts
client-app/shared/company/composables/useOrganization.ts

Description:
https://virtocommerce.atlassian.net/browse/ST-4526
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.32.0-pr-614-17fa-17fa5db5.zip

feat: add synchronization of browser tabs when authenticating

---

client-app/pages/account/order-details.vue

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.33.0-pr-621-77eb-77eba03b.zip

fix(order-details): reorder list print

---

client-app/shared/static-content/components/products-block.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-4377
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.33.0-pr-623-e353-e353810a.zip

fix: duplicated fetchProducts query

---

client-app/shared/catalog/components/product-price-block.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-4156
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.33.0-pr-626-5150-5150ba5e.zip

fix(Product): add to wishlist

---

client-app/pages/account/edit-quote.vue

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.33.0-pr-628-74be-74be604c.zip

fix: edit quote save changes

---

client-app/pages/account/edit-quote.vue

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.33.0-pr-630-c916-c916ef08.zip

fix: quote form validation

---

client-app/core/types/theme-config.ts
client-app/pages/matcher.vue
client-app/shared/builder-io/components/index.ts
client-app/shared/builder-io/components/landing-page.vue
client-app/shared/builder-io/components/landing.vue
client-app/shared/builder-io/index.ts
client-app/shared/layout/components/footer/vc-footer.vue
client-app/vue-builder-io.d.ts
config/settings_data.json
locales/en.json
package.json
yarn.lock

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.34.0-pr-629-8a64-8a640423.zip

feat: add builder.io support

---

client-app/pages/account/order-payment.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-4566
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.34.0-pr-637-0630-0630a783.zip

fix: show payment success buttons on mobile

---

client-app/core/api/graphql/account/index.ts
client-app/core/api/graphql/account/mutations/addWishlistBulkItem/addWishlistBulkItem.graphql
client-app/core/api/graphql/account/mutations/addWishlistBulkItem/index.ts
client-app/shared/wishlists/components/add-to-wishlists-modal.vue
client-app/shared/wishlists/composables/useWishlists.ts

Description:
https://virtocommerce.atlassian.net/browse/ST-4467
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.34.0-pr-639-545b-545b4c4e.zip

feat: implement single request for add to wishlists

---

client-app/shared/catalog/components/facet-filter.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-4348?focusedCommentId=62455
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.34.0-pr-641-aedb-aedb7bc5.zip

fix: hide show all while search

---

client-app/shared/wishlists/components/add-to-wishlists-modal.vue
client-app/shared/wishlists/composables/useWishlists.ts

Description:
https://virtocommerce.atlassian.net/browse/ST-4682
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.34.0-pr-642-1ead-1eadb71c.zip

fix: reduce requests number on create new wishlists

---

client-app/shared/broadcast/composables/useBroadcast.ts
client-app/shared/catalog/components/product-price-block.vue
client-app/shared/wishlists/components/add-to-list.vue

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.34.0-pr-640-609d-609d87bc.zip

refactor: broadcast

---

client-app/broadcast.ts
client-app/pages/change-password.vue
client-app/shared/broadcast/utils/events.ts

Description:
https://virtocommerce.atlassian.net/browse/ST-4727
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.35.0-pr-644-ae32-ae3215e0.zip

feat: open return url in other tabs after password change

---

client-app/shared/catalog/components/category.vue
client-app/shared/catalog/components/display-products.vue
client-app/shared/catalog/components/product-card-grid.vue
client-app/shared/catalog/components/product-card-list.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-4684
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.35.0-pr-648-a79d-a79de178.zip

feat: open category/search product details page in a new tab

---

scripts/generate-routes.ts

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.35.0-pr-650-0f7f-0f7f3915.zip

fix: generate routes hangs up

---

client-app/core/plugins/config.plugin.ts

Description:
https://virtocommerce.atlassian.net/browse/ST-4702
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.35.0-pr-646-54c3-54c3b64d.zip

fix: place css variables in style tag

---

client-app/core/plugins/config.plugin.ts

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.35.0-pr-651-f8f0-f8f09ff7.zip

fix: color generation

---

client-app/shared/account/components/sign-in-form.vue
locales/en.json

Description:
https://virtocommerce.atlassian.net/browse/ST-4736
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.35.0-pr-652-4ffe-4ffe775b.zip

fix: remove error alert in sign in form

---

client-app/pages/account/order-payment.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-4563
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.35.0-pr-655-8a56-8a56082b.zip

fix: top elements side space

---

client-app/pages/account/profile.vue
client-app/shared/account/components/change-password-form.vue
client-app/shared/account/composables/useUser.ts
locales/en.json

Description:
https://virtocommerce.atlassian.net/browse/ST-4732
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.35.0-pr-653-ed44-ed440b69.zip

refactor: change password method

---

client-app/pages/company/members.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-4546
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.35.0-pr-662-024b-024b3732.zip

fix: members page styles

---

client-app/shared/wishlists/components/wishlist-line-items.vue
client-app/ui-kit/components/atoms/button/vc-button.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-4579
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.35.0-pr-661-e832-e8327156.zip

fix: untrackable wishlist item add to cart component behavior

---

client-app/pages/account/order-details.vue

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.35.0-pr-664-ea07-ea07ab9e.zip

feat: show pay now button for payment required status

---

client-app/pages/account/edit-quote.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-4299
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.35.0-pr-666-2168-21680d16.zip

fix: edit-quote save changes button condition

---

client-app/pages/sign-up.vue
client-app/shared/account/components/sign-in-form.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-4530
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.35.0-pr-667-62b0-62b00d9c.zip

fix: behavior of sign in and sign up form

---

client-app/pages/welcome.vue
client-app/router/routes/main.ts

Description:
https://virtocommerce.atlassian.net/browse/ST-4739
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.35.0-pr-669-0451-0451c8be.zip

fix: make welcome page public

---

client-app/shared/account/composables/useUserOrders.ts

Description:
https://virtocommerce.atlassian.net/browse/ST-4751
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.36.0-pr-672-7b69-7b699427.zip

fix: filter by status "payment required"

---

client-app/shared/wishlists/composables/useWishlists.ts

Description:
https://virtocommerce.atlassian.net/browse/ST-4775
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.37.0-pr-673-27a3-27a3b1f4.zip

fix: fetch wish lists after add default one

---

client-app/shared/account/composables/useUserOrders.ts

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.37.0-pr-681-be50-be50e69b.zip

fix: fix quotes on order filtering by status

---

tsconfig.app.json
tsconfig.json
tsconfig.node.json

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.37.0-pr-684-ded2-ded2e4db.zip

fix: tsconfig

---

client-app/shared/account/components/change-password-form.vue

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.37.0-pr-687-6767-67674a53.zip

fix: change password form errors localization

---

client-app/shared/account/components/reset-password-form.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-4688
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.37.0-pr-683-97ff-97ffa407.zip

fix: add alert margin

---

client-app/pages/account/list-details.vue
client-app/shared/wishlists/composables/useWishlists.ts
locales/en.json

Description:
https://virtocommerce.atlassian.net/browse/ST-3339
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.37.0-pr-685-5360-53603d24.zip

feat: ask to save wishlist changes when user leave

---

client-app/shared/wishlists/components/add-to-wishlists-modal.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-4791
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.37.0-pr-689-831b-831b5678.zip

fix: support min quantity when add to wishlist

---

client-app/pages/index.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-4855
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.37.0-pr-688-ab21-ab2185e2.zip

feat: add space between header and footer while loading

---

client-app/core/utilities/properties/index.ts
client-app/shared/catalog/components/product-property.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-2669
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.37.0-pr-691-09ca-09ca6c44.zip

fix: format product date properties

---

client-app/pages/account/order-payment.vue
client-app/pages/account/view-quote.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-4637
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.37.0-pr-692-7dd0-7dd0aa23.zip

fix: format order and quote created date

---

client-app/shared/catalog/components/product-card-grid.vue
client-app/shared/catalog/components/product-card-list.vue

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.37.0-pr-690-23f4-23f47661.zip

fix: add lazy loading default value

---

client-app/pages/account/list-details.vue

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.37.0-pr-693-0f1a-0f1a1d47.zip

fix: call save changes dialog if other list opens

---

client-app/pages/account/list-details.vue

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.37.0-pr-694-2b6e-2b6ed2dc.zip

fix: add await for save changes

---

.vscode/settings.json

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.38.0-pr-696-3707-3707f63e.zip

fix: remove trailing comma in settings.json

---

client-app/core/composables/useGoogleAnalytics.ts
client-app/pages/checkout/review.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-4805
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.38.0-pr-697-f3f0-f3f04418.zip

feat: add GA place_order event

---

client-app/core/composables/useGoogleAnalytics.ts
client-app/shared/cart/composables/useCart.ts

Description:
https://virtocommerce.atlassian.net/browse/ST-4809
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.38.0-pr-698-0662-0662da76.zip

feat: add clear cart event

---

.vscode/extensions.json

Description:
Recommend https://marketplace.visualstudio.com/items?itemName=Lokalise.i18n-ally for VS Code
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.38.0-pr-701-df48-df48a1fd.zip

feat: recommend i18n ally

---

locales/en.json

Description:
https://virtocommerce.atlassian.net/browse/ST-4865
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.38.0-pr-699-ca35-ca35cadf.zip

fix: English locale

---

config/schemas/sections/slider.json

Description:
https://virtocommerce.atlassian.net/browse/ST-4850
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.38.0-pr-703-1360-13604020.zip

feat: add height settings for slider in page builder 

---

client-app/pages/account/dashboard.vue
client-app/pages/account/order-details.vue
client-app/pages/account/orders.vue
client-app/shared/account/components/order-status.vue
client-app/ui-kit/components/atoms/badge/vc-badge.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-4889
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.38.0-pr-704-dd8b-dd8b4437.zip

fix: implement order-status tooltip

---

content/pages/homepage.page

Description:
Updated settings for the main page
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.38.0-pr-707-5e27-5e2734db.zip

feat: add height settings to the main page

---

client-app/shared/checkout/composables/useCheckout.ts
locales/en.json

Description:
https://virtocommerce.atlassian.net/browse/ST-4721
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.38.0-pr-708-456a-456a409c.zip

fix: add billing address if shipping address is empty

---

client-app/App.vue
client-app/assets/styles/main.scss

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.38.0-pr-715-59e8-59e8b740.zip

style: fix paths for app styles

---

.vscode/settings.json

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.38.0-pr-714-3c13-3c13d74c.zip

chore: support postcss with tailwind in vs code

---

.github/workflows/deploy.yml

Description:
--
QA-test:
Demo-test:

ci: upgrade deployments

---

.github/workflows/deploy.yml

Description:
--
QA-test:
Demo-test:

ci: fix environment name for deployment

---

client-app/pages/account/quotes.vue
client-app/shared/account/components/orders.vue
client-app/shared/account/components/quote-status.vue

Description:
fix https://virtocommerce.atlassian.net/browse/ST-4889
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.38.0-pr-721-e886-e8868bf0.zip

fix: order & quote statuses width in tables

---

client-app/core/utilities/properties/index.ts
client-app/pages/compare-products.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-4856
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.39.0-pr-732-1c18-1c18955e.zip

fix: format product properties according to selected locale

---

client-app/ui-kit/components/molecules/image-gallery/vc-image-gallery.vue
package.json
tailwind.config.ts
yarn.lock

Description:
https://virtocommerce.atlassian.net/jira/software/projects/ST/issues/ST-4951?jql=project%20%3D%20%22ST%22%20AND%20assignee%20%3D%20%225f8da9890b07fb006f187e77%22%20ORDER%20BY%20created%20DESC
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.39.0-pr-729-e4a8-e4a89446.zip

feat: add full screen image preview

---

client-app/app-runner.ts
client-app/core/composables/useLanguages.ts
client-app/i18n.ts
locales/de.json
locales/fr.json

Description:
https://virtocommerce.atlassian.net/browse/ST-4913
--
Also fix edit language from the platform
Fix performance issue with separate language load
Before:
After:
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.39.0-pr-731-fc17-fc172326.zip

Partially added support for French and German

---

client-app/core/composables/useLanguages.ts

Description:
https://virtocommerce.atlassian.net/browse/ST-4913
Return old locale loading method
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.39.0-pr-733-66dc-66dc695d.zip

fix: rollback dynamic load

---

client-app/shared/catalog/components/discount-badge.vue
client-app/shared/company/components/invite-member-modal.vue
client-app/shared/wishlists/components/add-or-update-wishlist-modal.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-4573
https://virtocommerce.atlassian.net/browse/ST-5014
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.39.0-pr-735-7ad9-7ad9a991.zip

fix: adding space in some inputs

---

client-app/router/index.ts

Description:
https://virtocommerce.atlassian.net/browse/ST-4947
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.39.0-pr-738-c382-c382ad8f.zip

feat: open catalog page by default

---

locales/en.json

Description:
https://virtocommerce.atlassian.net/browse/ST-4900
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.39.0-pr-740-4df1-4df1e942.zip

feat: rephrase emails label

---

client-app/pages/static-page.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-5004
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.39.0-pr-739-2122-2122dbea.zip

fix: breadcrumbs don't hide on the home page

---

client-app/shared/layout/components/header/_internal/bottom-header.vue
client-app/shared/layout/components/header/_internal/mobile-menu.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-4604
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.39.0-pr-736-25b0-25b08322.zip

fix: navigation semantic structure

---

client-app/shared/catalog/components/product-variation-card.vue
client-app/shared/layout/components/search-bar/_internal/search-bar-product-card.vue
client-app/shared/layout/components/secure-layout/secure-layout.vue
locales/en.json

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.39.0-pr-746-2571-25713605.zip

fix: sticky header and localization on print

---

client-app/ui-kit/components/molecules/line-item/vc-line-item.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-5024
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.39.0-pr-748-5ced-5ced1cf7.zip

fix(line-item): remove button layout

---

client-app/shared/bulk-order/components/manually.vue
locales/en.json

Description:
https://virtocommerce.atlassian.net/browse/ST-5027
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.39.0-pr-749-3b1d-3b1d2926.zip

fix bulk order locale

---

client-app/pages/company/info.vue
client-app/shared/company/components/company-info-dropdown-menu.vue
client-app/shared/company/components/index.ts
client-app/ui-kit/components/atoms/action-dropdown-menu/vc-action-dropdown-menu.vue
client-app/ui-kit/components/atoms/types.d.ts
tailwind.config.ts

Description:
https://virtocommerce.atlassian.net/browse/ST-4661
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.39.0-pr-720-fcb2-fcb2ca3f.zip

feat(company-info): implement new settings dropdown design

---

client-app/ui-kit/components/molecules/item-price-catalog/vc-item-price-catalog.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-4826
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.40.0-pr-753-7703-7703a98f.zip

fix: restore actual price for catalog items

---

client-app/ui-kit/components/molecules/image-gallery/vc-image-gallery.vue
package.json
tsconfig.node.json
vite.config.ts
yarn.lock

Description:
https://virtocommerce.atlassian.net/browse/ST-5051
Also:
* Scripts updated to reuse already defined scripts (to prevent missed commands and arguments)
* Fixed issue with typescript incremental build
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.40.0-pr-754-899e-899e28ff.zip

fix: generate routes.json

---

client-app/core/api/graphql/catalog/queries/getSearchResults/getSearchResultsQuery.graphql
client-app/core/api/graphql/catalog/queries/searchProducts/searchProductsQuery.graphql
client-app/shared/catalog/components/product-card-grid.vue
client-app/shared/catalog/components/product-card-list.vue
client-app/shared/layout/components/search-bar/_internal/search-bar-product-card.vue
client-app/ui-kit/components/molecules/item-price-catalog/vc-item-price-catalog.vue
client-app/ui-kit/components/molecules/item-price/vc-item-price.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-1341
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.40.0-pr-757-9549-9549f14c.zip

feat: show min variation price for product with variations at catalog page

---

client-app/shared/cart/composables/useCart.ts

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.40.0-pr-758-63ee-63eef092.zip

fix: select for checkout multiple vendor groups

---

client-app/core/api/graphql/fragments/fullCartFields.graphql
client-app/pages/cart.vue
client-app/pages/checkout/review.vue
client-app/shared/cart/composables/useCart.ts
client-app/shared/checkout/composables/useCheckout.ts

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.40.0-pr-759-8190-81903eb2.zip

fix: select items after order creation

---

client-app/shared/cart/components/add-to-cart.vue
client-app/shared/cart/composables/useCart.ts

Description:
https://virtocommerce.atlassian.net/browse/ST-4989
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.40.0-pr-755-cef2-cef278ba.zip

fix: error notification in cart

---

client-app/pages/account/list-details.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-4854
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.40.0-pr-762-5715-5715891e.zip

refactor(list-details): remove duplicate buttons

---

client-app/shared/wishlists/components/wishlist-line-items.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-4966
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.40.0-pr-761-3901-39012147.zip

fix(wishlist-line-items): add-to-cart style

---

client-app/shared/static-content/components/call-to-action-with-image.vue
config/schemas/sections/call-to-action-with-image.json
content/pages/test_demo_landing.en-US.page

Description:
https://virtocommerce.atlassian.net/browse/ST-5033
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.40.0-pr-760-fa96-fa963117.zip

PageBuilder. Add "alt" attribute to the "Call to action with image" section

---

client-app/core/utilities/common/index.ts
client-app/shared/payment/components/bank-card-form.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-4969
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.40.0-pr-763-e573-e573778e.zip

fix: make errors in payment card component upper cased

---

client-app/pages/account/list-details.vue
client-app/shared/wishlists/components/wishlist-line-items.vue

Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.40.0-pr-773-0696-0696d073.zip

fix: remove line item from wishlish

---

client-app/broadcast.ts
client-app/core/api/graphql/client.ts
client-app/pages/company/members.vue
client-app/shared/account/composables/useUserOrder.ts
client-app/shared/broadcast/utils/events.ts
locales/en.json

Description:
https://virtocommerce.atlassian.net/browse/ST-4870
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.40.0-pr-768-0f5b-0f5b24f9.zip

fix: handle forbidden error

---

client-app/pages/demo-landing.vue
client-app/shared/static-content/components/call-to-action-with-image.vue
client-app/shared/static-content/components/call-to-action.vue
client-app/shared/static-content/utils/index.ts
content/pages/test_demo_landing.en-US.page
tsconfig.app.json

Description:
https://virtocommerce.atlassian.net/browse/ST-5110
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.41.0-pr-766-392f-392f02e5.zip

fix: absolute link in CTA

---

client-app/core/api/graphql/catalog/queries/searchRelatedProducts/searchRelatedProducts.graphql
client-app/shared/cart/components/add-to-cart.vue
client-app/shared/catalog/components/product-card-related.vue
client-app/shared/static-content/components/related-products.vue
client-app/ui-kit/components/organisms/product-image/vc-product-image.vue

Description:
Story: 
https://virtocommerce.atlassian.net/browse/ST-4931
Subtasks:
https://virtocommerce.atlassian.net/browse/ST-5157
https://virtocommerce.atlassian.net/browse/ST-5158
https://virtocommerce.atlassian.net/browse/ST-5162
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.41.0-pr-780-0bed-0bed0b63.zip

fix: related products

---

client-app/shared/cart/components/cart-line-items.vue
client-app/shared/wishlists/components/wishlist-line-items.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-5106
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.41.0-pr-777-fb4d-fb4d5d3b.zip

fix: product availability status in cart

---

client-app/core/enums/identity-errors.enum.ts
client-app/shared/account/components/sign-in-form.vue
locales/en.json

Description:
https://virtocommerce.atlassian.net/browse/ST-4919
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.41.0-pr-774-1141-1141021d.zip

feat: add detailed sign in error messages

---

client-app/ui-kit/components/organisms/product-image/vc-product-image.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-4931
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.41.0-pr-782-c2f6-c2f66b1d.zip

fix: vc-product-image fix for Safari

---

client-app/shared/catalog/components/product-card-related.vue
client-app/shared/wishlists/components/add-to-list.vue
client-app/ui-kit/components/organisms/product-image/vc-product-image.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-5162
--
QA-test:
Demo-test:
Artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.41.0-pr-784-b2d3-b2d39515.zip

fix: related products images & tooltips

---

client-app/shared/wishlists/components/wishlist-line-items.vue
client-app/ui-kit/components/molecules/line-items/vc-line-items.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-4929
--
QA-test:
Demo-test:
Artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.41.0-pr-783-04be-04bef9f7.zip

fix: remove quantity header in wishlist

---

client-app/pages/account/edit-quote.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-4788
--
QA-test:
Demo-test:
Artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.41.0-pr-786-baa2-baa27bc6.zip

fix: save quote if changed comment or items

---

.github/workflows/deploy-cloud.yml
.github/workflows/storybook-ci.yml

also typo fixed
Description:
--
QA-test:
Demo-test:

ci: update jira deployment status

---

.github/pull_request_template.md

It will look like that. Based on platform & modules PR template and CI requirements (`Artifact URL:` string)

ci: update pull request template

---

client-app/core/api/graphql/fragments/shortCartFields.graphql
client-app/shared/cart/components/add-to-cart.vue
client-app/shared/cart/composables/useCart.ts
client-app/shared/cart/enums/index.ts
locales/en.json

Description:
https://virtocommerce.atlassian.net/browse/ST-4925
--
QA-test:
Demo-test:
Artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.41.0-pr-785-4f6d-4f6d225c.zip

refactor: add to cart validation

---

client-app/core/api/graphql/catalog/queries/searchRelatedProducts/searchRelatedProducts.graphql
client-app/shared/catalog/components/product-card-related.vue
client-app/ui-kit/components/molecules/product-price/vc-product-price.stories.ts
client-app/ui-kit/components/molecules/product-price/vc-product-price.vue

Description:
https://virtocommerce.atlassian.net/browse/ST-5215
https://virtocommerce.atlassian.net/browse/ST-5216
--
QA-test:
Demo-test:
Artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.41.0-pr-788-288a-288a1d89.zip

fix: product card related variations number & price

---

.github/workflows/deploy-cloud.yml

ci: use different token for deploy

---

client-app/core/api/graphql/catalog/queries/searchRelatedProducts/searchRelatedProducts.graphql
client-app/shared/catalog/components/product-card-related.vue

https://virtocommerce.atlassian.net/browse/ST-4931

fix: variations min price in related products

---

client-app/pages/account/list-details.vue

https://virtocommerce.atlassian.net/browse/ST-5151

fix: redirect to 403 if wishlist not exist
