VirtoCommerce/vc-frontend

- client-app/App.vue
- client-app/shared/context/composables/index.ts
- client-app/shared/context/composables/useContext.ts
- client-app/shared/context/index.ts
- client-app/shared/context/types/index.ts
https://virtocommerce.atlassian.net/browse/ST-393
usage 
```js
import { useContext } from "@/shared/context";
const { themeContext } = useContext();
....
themeContext.catalogId
```
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/client-app-0.0.1-pr-23-f057be46.zip
> feat: add the logic for loading storefront context

- client-app/pages/account/orders.vue
- client-app/pages/company/members.vue
- client-app/pages/index.vue
- client-app/shared/catalog/components/products-filters.vue
- client-app/shared/layout/components/header/_internal/mobile-header.vue
- client-app/shared/layout/components/search-bar/search-bar.vue
- client-app/ui-kit/components/atoms/action-input/vc-action-input.vue
- client-app/ui-kit/components/atoms/input/vc-input.vue
Description:
Find all input elements without VcInput component usage. 
use VcInput if it is possible.
use the ‘trim’ modifier in other cases. 
Fix VcInput. Don’t use trimming to type 'password'
check the trimming algoritm on possible improvements 
--
QA-test:  ST-2709
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.8.0-pr-285-6ac1dc97.zip
> fix(ST-2707): trim text inputs value. use VcInput everywhere it posible

- package.json
- vite.config.ts
- yarn.lock
After merging this PR:
* At first `yarn dev` or `yarn dev-expose`, `mkcert` will show request to install locally-generated self-signed `Trusted Root Certificate Authority (Root CA)` (**it will be shared** with other projects which use `mkcert`)
* At every next `yarn dev` or `yarn dev expose` new certificate will be generated (if missed) or updated (if outdated) for the `localhost` and `127.0.0.1` addresses for `vc-theme-b2b-vue` (**it will not be shared**), signed by `Root CA`
* When you will open theme through `https` you will no longer see warning about incorrect `https` certificate
* Also a little bit refactored code for storefront https connection support to be consistent with other projects
**TD;LR**
--
QA-test:
Demo-test: …
> fix: support self-signed locally trusted certs

- client-app/pages/company/info.vue
- locales/de.json
- locales/en.json
Description:
https://virtocommerce.atlassian.net/browse/ST-3189
Exclude address info from the popup.
the txt shall be “Address has been successfully saved.“
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.17.0-pr-392-6b78-6b783e46.zip
> fix: remove company address info from notification popup

- client-app/shared/catalog/composables/useBreadcrumbs.ts
Description:
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.19.0-pr-422-7885-7885f4b5.zip
> fix: url without initial slash in breadcrumbs

- client-app/shared/layout/components/header/_internal/mobile-menu-link.vue
Description:
https://virtocommerce.atlassian.net/browse/ST-2901
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.24.0-pr-492-1623-1623c384.zip
> fix: mobile-menu-link break-words

- client-app/core/constants/images.ts
- client-app/core/constants/index.ts
- client-app/core/constants/tailwind.ts
- client-app/shared/catalog/components/category.vue
- client-app/shared/catalog/components/display-products.vue
- client-app/shared/catalog/components/product-card-grid.vue
- client-app/shared/catalog/components/product-card-list.vue
- client-app/shared/static-content/components/slider.vue
- client-app/shims-vueuse.d.ts
- client-app/ui-kit/components/atoms/image/vc-image.vue
- tailwind.config.ts
Description:
https://virtocommerce.atlassian.net/browse/ST-4743
After this PR will be merged, use `BREAKPOINTS` from `import { BREAKPOINTS } from "@/core/constants"` instead of `breakpointsTailwind` from `import { breakpointsTailwind } from "@vueuse/core"`.
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.37.0-pr-677-ac8c-ac8ce4b7.zip
> fix: remove lazy for large content paint images

- .vscode/extensions.json
- README.md
- graphql.config.json
Description:
https://github.com/JetBrains/js-graphql-intellij-plugin/releases/tag/4.0.0
https://marketplace.visualstudio.com/items?itemName=GraphQL.vscode-graphql
Both now is using graphql config v3 and drops support of v2
--
QA-test:
Demo-test:
Download artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.39.0-pr-737-5132-5132467c.zip
> fix: upgrade graphql config to v3

- client-app/shared/payment/components/bank-card-form.vue
Description:
https://virtocommerce.atlassian.net/browse/ST-4980
Now:
* Validates only after month
* Label is correctly displayed
--
QA-test:
Demo-test:
Artifact URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.41.0-pr-789-b5b1-b5b138f2.zip
> fix: bank card expiration year validation

- client-app/shared/cart/composables/useCart.ts
Proceed to the checkout payment step when only digital products are selected at mixed cart (contains digital and physical products)
https://virtocommerce.atlassian.net/browse/ST-5085
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.42.0-pr-824-3afc-3afcd34f.zip
> fix: proceed to payment step when selected only digital products at mixed cart

- client-app/pages/cart.vue
Make "Add cart items to quote" button width same as "Place order" button
https://virtocommerce.atlassian.net/browse/ST-5114
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.42.0-pr-825-b4be-b4be2676.zip
> fix: make create quote button width same as palce order button

- client-app/pages/account/list-details.vue
The Save Changes feature does not work for wish lists that have deleted products. After this fix items with deleted products will no linger involve in the save operation
https://virtocommerce.atlassian.net/browse/ST-5077
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.42.0-pr-827-c4d4-c4d4fa49.zip
> fix: save wishlist with deleted products

- client-app/App.vue
[Print Order] The empty page is added if there are 2 vendor sections and 4 items in Order
https://virtocommerce.atlassian.net/browse/ST-5131
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.42.0-pr-834-34b3-34b3e440.zip
> fix: remove empty page in print mode

- .husky/commit-msg
- .husky/post-checkout
- .husky/pre-commit
- package.json
* Added git hook (via husky) to cleanup cache after checkout. Should help for linter false-positives when switch between branches
* Other hooks moved to use yarn without temporary packages installation (will took package from `node_modules`). Should a little bit speed up commit linting
> chore: cleanup cache on checkout & run hooks with yarn

- client-app/shared/layout/components/search-bar/search-bar.vue
Now when we click on a product in the list, we send a select_item event and put the product there.
In such situations, marketers are asked to add the phrase by which this product was found.
https://virtocommerce.atlassian.net/browse/ST-5421
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.43.0-pr-854-fc36-fc36249b.zip
> feat: Google Analytics. Add related search term to "select_item" event in search bar item

- .eslintrc.cjs
Since the `@apollo/client` depends on React and include React hooks, you should never import it and instead import sub packages `@apollo/client/*` or use composables from `@vue/apollo-composable`
https://virtocommerce.atlassian.net/browse/ST-5488
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.44.0-pr-870-28dc-28dcba82.zip
> chore: add linter rules for apollo

- client-app/shared/company/types/index.ts
- client-app/shared/company/utils/index.ts
Show "Invite sent" status at company members page for Invited xapi contact status
https://virtocommerce.atlassian.net/browse/ST-5568
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.45.0-pr-889-668f-668fc902.zip
> fix: show Invite sent status for Invited xapi contact status

- client-app/shared/account/components/orders.vue
Fix latest orders padding on dashboard
https://virtocommerce.atlassian.net/browse/ST-5386
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.47.0-pr-923-53f5-53f542e0.zip
> fix: latest orders padding on dashboard

- client-app/core/utilities/properties/index.ts
- client-app/pages/compare-products.vue
Show unexisting or empty properties values as dashes at compare products page
https://virtocommerce.atlassian.net/browse/ST-5355
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.48.0-pr-927-475d-475da834.zip
> fix: show unexisting or empty properties values as dashes at compare products page

- .vscode/extensions.json
- README.md
Use [Volar Takeover mode](https://vuejs.org/guide/typescript/overview#volar-takeover-mode) instead
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.48.0-pr-935-6691-6691c5a0.zip
> chore: use takeover mode instead of vue typescript plugin

- package.json
- yarn.lock
`marked: "^11.2.0"` now has their own types
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.50.0-pr-952-99c4-99c40e43.zip
> chore: remove @types/marked

- .husky/pre-commit
Before this PR linter run at merge conflicts and may cause unexpected changes if for some reason not all files in project was linted.
https://virtocommerce.atlassian.net/browse/VCST-465
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.50.0-pr-956-5ed4-5ed4f284.zip
> chore: don't run linter on merge commits

- client-app/shared/files/composables/useFiles.ts
- locales/en.json
Support case-insensitive file extensions on file upload
https://virtocommerce.atlassian.net/browse/VCST-537
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.52.0-pr-973-5303-530355f2.zip
> feat: support case-insensitive file extensions on file upload

- client-app/shared/files/composables/useFiles.ts
- client-app/ui-kit/index.ts
Composables, constants & utils import of `ui-kit/index.ts` may cause build failures like [this](https://github.com/VirtoCommerce/vc-theme-b2b-vue/actions/runs/8060523377/job/22017841531) because of `routes.json` generation.
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.52.0-pr-991-dd49-dd49a01b.zip
> fix: don't reexport from ui-kit

- .dependency-graph.cjs
- package.json
How to use:
```bash
yarn generate:dependency-graph FROM TO
```
For example, to see why `add-to-wishlist-modal.vue` is added to main bundle, use this:
```
yarn generate:dependency-graph client-app/main.ts client-app/shared/wishlists/components/add-to-wishlists-modal.vue
```
Current dev:
[dev.zip](https://github.com/VirtoCommerce/vc-theme-b2b-vue/files/14454808/dev.zip)
After some refactoring:
[refactoring.zip](https://github.com/VirtoCommerce/vc-theme-b2b-vue/files/14454812/refactoring.zip)
Useful with #989: just look from `client-app/main.ts` to largest files included to bundle and replace imports via `index.ts` by direct imports.
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.52.0-pr-990-feae-feae036b.zip
> chore: visualize dependency graph from X to Y

- client-app/ui-kit/components/molecules/file-uploader/vc-file-uploader.vue
Prevent file upload or opening if file limit exceeded on drag and drop
https://virtocommerce.atlassian.net/browse/VCST-462
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.54.0-pr-983-010b-010b54b9.zip
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.52.0-pr-983-8051-80516b6c.zip
> fix: prevent drag and drop file opening if file limit exceeded

- client-app/core/api/graphql/schema.json
- graphql-codegen.schema.config.ts
- graphql-codegen.types.config.ts
You can generate graphql types using already downloaded schema via `yarn generate:graphql:types`. It didn't work before because url was used instead of downloaded file. This is usable when you need to re-generate types for existing queries/mutations and don't want to add new types available (may be temporary) on dev.
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.54.0-pr-1011-7530-75309481.zip
> chore: generate graphql types from downloaded schema

- client-app/pages/company/members.vue
Keep selected filters values on popup on click outside on company members page
https://virtocommerce.atlassian.net/browse/VCST-1229
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.60.0-pr-1130-3751-37510e67.zip
> fix: keep selected filters values on popup on click outside on company members page

- client-app/shared/wishlists/components/wishlist-line-items.vue
Show product name as plain text for deleted product at list details page
https://virtocommerce.atlassian.net/browse/VCST-1281
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.60.0-pr-1129-2632-2632992f.zip
> fix: show product name as plain text for deleted product at list details page

- client-app/core/api/graphql/client.ts
- client-app/core/api/graphql/config/links.ts
We can safely use `link` instead of `deprecatedLink`, because the first one differs by having cartLink and condition use `wsLink` for subscriptions and `httpLink` for others.
Cart link has a defined list of operations it will be applied for. So it doesn't influence anything else.
The second also works perfectly well, because all subscriptions should use wsLink (actually we have only one which already use our "new" client.
https://virtocommerce.atlassian.net/browse/VCST-1706
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.4.0-pr-1272-548b-548ba682.zip
> chore: use common links in both apollo clients

- client-app/core/composables/useNavigations.ts
https://virtocommerce.atlassian.net/browse/VCST-1919
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.6.0-pr-1348-f460-f46060b8.zip
> fix: `mobile menu` after switch `shallowRef` to `ref`

- .eslintrc.cjs
[This rule](https://typescript-eslint.io/rules/unbound-method/) is a part of ["plugin:@typescript-eslint/recommended-type-checked"](https://typescript-eslint.io/users/configs#recommended-type-checked). To turn it on need just delete it.
Before:
Now:
If you really need it:
https://virtocommerce.atlassian.net/browse/VCST-1894
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.7.0-pr-1365-f3ce-f3cee35c.zip
> chore: turn on unbound-method

- client-app/core/composables/useHistoricalEvents.ts
- client-app/core/constants/modules.ts
- client-app/pages/cart.vue
fix: do not send recently browsed request if module is not installed or disabled
https://virtocommerce.atlassian.net/browse/VCST-2175
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.9.0-pr-1422-785e-785ee930.zip
> fix: don't send recentlyBrowsed request if module is not installed/enabled

- client-app/ui-kit/components/molecules/file/vc-file.vue
This is a "better version" of #1311: this PR fixes case with file names without a link (for example, if file was removed from backend) and makes remove button centered, so it doesn't look weird
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.9.0-pr-1413-4966-49660592.zip
> fix: long file name

- client-app/modules/quotes/locales/en.json
Localization key used for quote metadata was missed because of previous refactoring
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.9.0-pr-1414-776d-776d4bf6.zip
> fix: missed quote metadata localization key

- client-app/config/settings_data.json
- client-app/core/types/theme-config.ts
- client-app/modules/quotes/constants.ts
- client-app/modules/quotes/index.ts
- client-app/modules/quotes/pages/edit-quote.vue
- client-app/shared/account/constants/index.ts
- client-app/shared/account/index.ts
Removed settings quotes_enabled and quotes_files_scope from settings_data.json
This part is configurable from the platform now 
Comparable with the Platform v 3.861.0 and vc-module-quote 3.818.0
https://virtocommerce.atlassian.net/browse/VCST-1868
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.9.0-pr-1432-3904-39042c13.zip
> feat: get Quote module file scope from the Platform

- client-app/modules/quotes/components/quote-line-items.vue
1. Create a quote
2. Update quote line item price from admin
Price will be updated on frontend too
Price remains the same
https://virtocommerce.atlassian.net/browse/VCST-2211
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.9.0-pr-1415-888a-888a791b.zip
> fix: quote price isn't updated after negotiation with seller

- client-app/pages/matcher/builderIo/builder-io.vue
- package.json
- yarn.lock
Removed cache settings
https://github.com/BuilderIO/builder/blob/83f46fd6adbd181a2c7c2011b8d0bd3909ab3332/packages/core/src/builder.class.ts#L326
Braking change:
https://github.com/BuilderIO/builder/releases/tag/%40builder.io%2Fsdk-vue%402.0.0
https://github.com/BuilderIO/builder/releases/tag/%40builder.io%2Fsdk-vue%403.0.0
https://virtocommerce.atlassian.net/browse/VCST-2322
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.10.0-pr-1469-5433-5433c5f1.zip
> chore: update builder.io/sdk-vue ^1.0.36 -> ^3.0.0

- client-app/core/api/graphql/utils.ts
https://virtocommerce.atlassian.net/browse/VCST-2340
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.11.0-pr-1485-e84a-e84ab87c.zip
> fix: abort controller errors in safari

- client-app/broadcast.ts
Show single alert data changed on another tab
https://virtocommerce.atlassian.net/browse/VCST-2508
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.12.0-pr-1517-bb05-bb059570.zip
> fix: show single alert data changed on another tab

- client-app/ui-kit/components/atoms/icon/vc-icon.vue
- client-app/ui-kit/components/molecules/shape/vc-shape.vue
In some environments there is an issue with absolute path resolving in dynamic import
https://virtocommerce.atlassian.net/browse/VCST-2527
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.13.0-pr-1521-3376-3376aaf5.zip
> fix: replace path to relative in vc-shape and vc-icon

- client-app/shared/account/components/mobile-orders-filter.vue
- client-app/shared/account/components/orders-filter.vue
Hide order status selector label on filters popup for empty orders list
https://virtocommerce.atlassian.net/browse/VCST-2864
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.17.0-pr-1627-1faf-1faf00cd.zip
> fix: hide order status selector label on filters popup for empty orders list

- client-app/core/composables/useBreadcrumbs.test.ts
- client-app/core/utilities/breadcrumbs/index.test.ts
- client-app/core/utilities/breadcrumbs/index.ts
fix: "/undefined" in breadcrumbs
https://virtocommerce.atlassian.net/browse/VCST-2762
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.19.0-pr-1665-8a1c-8a1ca0e9.zip
> chore: add test for utilities/breadcrumbs/ and useBreadcrumbs

- client-app/ui-kit/components/organisms/product-image/vc-product-image.vue
Before:
After:
https://virtocommerce.atlassian.net/browse/VCST-3145
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.20.0-pr-1696-041d-041d438f.zip
> fix: actions buttons for related products with multiple images

- client-app/core/types/analytics.ts
- client-app/pages/account/list-details.vue
- client-app/pages/cart.vue
- client-app/pages/compare-products.vue
- client-app/pages/product.vue
- client-app/shared/cart/components/cart-line-items.vue
- client-app/shared/cart/components/products-section.vue
- client-app/shared/catalog/components/category.vue
- client-app/shared/catalog/components/product/variations.vue
- client-app/shared/catalog/components/recently-browsed-products.vue
- client-app/shared/layout/components/search-bar/search-bar.vue
- client-app/shared/static-content/components/recommended-products.vue
- client-app/shared/static-content/components/related-products.vue
- client-app/shared/wishlists/components/wishlist-line-items.vue
- client-app/ui-kit/components/molecules/line-item/vc-line-item.vue
- client-app/ui-kit/components/molecules/line-items/vc-line-items.vue
https://virtocommerce.atlassian.net/browse/VCST-3128
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.21.0-pr-1703-51bd-51bd261d.zip
> feat: analytics events view_item_list, select_item
