- client-app/shared/checkout/components/select-payment-method-modal.vue
https://virtocommerce.atlassian.net/browse/ST-4921
> fix: select-payment-method-modal icon size

- client-app/core/composables/usePageHead.ts
- client-app/core/constants/tailwind.ts
- client-app/core/types/search/entity.ts
- client-app/core/types/theme-config.ts
- client-app/pages/account/profile.vue
- client-app/pages/company/members.vue
- client-app/shared/account/composables/useUserQuote.ts
- client-app/shared/broadcast/composables/useBroadcast.ts
- client-app/shared/bulk-order/components/manually.vue
- client-app/shared/catalog/components/display-products.vue
- client-app/shared/catalog/components/product-card-grid.vue
- client-app/shared/catalog/components/product-card-list.vue
- client-app/shared/catalog/components/product-card-related.vue
- client-app/shared/company/components/edit-customer-role-modal.vue
- client-app/ui-kit/components/atoms/badge/vc-badge.types.d.ts
- client-app/ui-kit/components/molecules/chip/vc-chip.types.d.ts
- client-app/ui-kit/components/organisms/add-to-cart/vc-add-to-cart.vue
- graphql-codegen.schema.config.ts
- graphql-codegen.types.config.ts
Issues fixed here will throw typescript or eslint errors after upgrade
> refactor: fix typing or suppress compiler warning temporarely

- client-app/app-runner.ts
- client-app/core/composables/useLanguages.ts
- client-app/core/utilities/address/index.ts
- client-app/shared/company/components/invite-member-modal.vue
- client-app/shared/popup/types/index.ts
- client-app/shared/static-content/types/index.ts
- client-app/ui-kit/components/atoms/checkbox/vc-checkbox.vue
- client-app/ui-kit/components/atoms/tabs/vc-tabs.vue
- client-app/ui-kit/components/molecules/carousel/vc-carousel.vue
- client-app/ui-kit/components/molecules/select/vc-select.vue
- client-app/ui-kit/components/organisms/sliding-actions/vc-sliding-actions.vue
- client-app/ui-kit/types/index.d.ts
Issues fixed here will throw typescript or eslint errors after upgrade
> refactor: fix or suppress explicit any

- client-app/shared/account/composables/useUser.ts
User specific password expiration notification
https://virtocommerce.atlassian.net/browse/ST-5111
> fix: make password expiration notification user specific

- .eslintrc.cjs
- .github/workflows/storybook-ci.yml
- .github/workflows/theme-ci.yml
- .vscode/settings.json
- client-app/core/api/graphql/schema.json
- client-app/core/api/graphql/types.ts
- graphql-codegen.types.config.ts
- sonar-project.properties
- tsconfig.node.json
> ci: run sonarqube scan

- .github/workflows/storybook-ci.yml
- .github/workflows/theme-ci.yml
> ci: fix release artifact name

- .deployment/theme/cloudDeploy.json
- .github/pull_request_template.md
- .github/workflows/deploy-cloud.yml
- .github/workflows/storybook-ci.yml
- .github/workflows/theme-ci.yml
- README.md
https://virtocommerce.atlassian.net/browse/ST-5192
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.42.0-pr-821-2445-2445e983.zip
> ci: move deployment to vc-deploy-dev

- client-app/core/api/graphql/catalog/queries/getCategory/index.ts
- client-app/shared/catalog/components/category.vue
Add Open Graph SEO info for category image URL
https://virtocommerce.atlassian.net/browse/ST-5238
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.42.0-pr-833-3d8f-3d8f2b1a.zip
> fix: add open graph info for category image url

- client-app/ui-kit/components/molecules/select/vc-select.vue
https://virtocommerce.atlassian.net/browse/ST-5304
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.42.0-pr-837-9be2-9be223ac.zip
> fix: open vc-select dropdown on icon click

- .github/workflows/theme-ci.yml
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.43.0-pr-840-57ff-57ff9671.zip
> ci: fix local asset path for release

- client-app/shared/cart/components/add-to-cart.vue
Fix add to cart component padding for mobile devices
https://virtocommerce.atlassian.net/browse/ST-5226
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.43.0-pr-843-667d-667d0ea8.zip
> fix: add to cart components paddings for mobile

- client-app/assets/styles/print/molecules/vc-line-items.scss
- client-app/assets/styles/print/molecules/vc-select.scss
- client-app/pages/checkout/review.vue
https://virtocommerce.atlassian.net/browse/ST-5251
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.42.0-pr-839-126f-126fb1f2.zip
> fix: avoid page breaks on print

- client-app/ui-kit/components/molecules/alert/vc-alert.vue
https://virtocommerce.atlassian.net/browse/ST-5359
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.43.0-pr-841-269c-269cc1b7.zip
> fix: vc-alert close button

- client-app/pages/account/list-details.vue
- client-app/shared/wishlists/components/index.ts
- client-app/shared/wishlists/components/save-wishlist-changes-modal.vue
Save wishlist changes modal behavior
https://virtocommerce.atlassian.net/browse/ST-5282
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.43.0-pr-847-ba67-ba674426.zip
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.43.0-pr-847-8b19-8b1959f3.zip
> feat: save wishlist changes modal behavior

- client-app/ui-kit/mocks/money.mock.ts
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.43.0-pr-852-dd5b-dd5b95c0.zip
> fix: exception in money mock for storybook

- client-app/ui-kit/components/molecules/chip/vc-chip.vue
https://virtocommerce.atlassian.net/browse/ST-5322
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.43.0-pr-851-4c49-4c491a55.zip
> fix: vc-chip styles

- client-app/shared/common/components/contact-administrator-link.vue
- client-app/shared/layout/components/footer/vc-footer.vue
- client-app/shared/layout/components/header/_internal/top-header.vue
- client-app/shared/static-content/components/text-block.vue
- config/menu.json
- content/pages/contacts.en-US.page
Contacts page by Page Builder
https://virtocommerce.atlassian.net/browse/ST-5009
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.43.0-pr-845-31fb-31fb53e8.zip
> feat: add contacts page

- .eslintrc.cjs
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.43.0-pr-856-05cc-05ccfec6.zip
> chore: configure linting for unit tests

- locales/en.json
https://virtocommerce.atlassian.net/browse/ST-5442
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.43.0-pr-860-9e61-9e61fcee.zip
> fix: update password is about to expire title

- client-app/broadcast.ts
- client-app/core/api/graphql/client.ts
- client-app/core/api/graphql/enums.ts
- client-app/shared/account/composables/useUser.ts
- client-app/shared/broadcast/utils/events.ts
Handle "PasswordExpired" in useUser.ts and in client.ts
https://virtocommerce.atlassian.net/browse/ST-5262
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.43.0-pr-861-0464-04646a58.zip
> fix: handle xapi "PasswordExpired" error

- .husky/post-checkout
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.44.0-pr-864-5ee1-5ee13a50.zip
> chore: fix post-checkout fail if cache folder already removed

- client-app/shared/cart/composables/useCoupon.ts
Remove spaces from coupons.
https://virtocommerce.atlassian.net/browse/ST-5134
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.44.0-pr-866-44d5-44d51146.zip
> fix: add trim for coupon

- client-app/pages/index.vue
- client-app/pages/matcher.vue
- client-app/router/routes/checkout.ts
* All checkout routes made lazy
* Product, Category components was imported both statically and dynamically, changed to dynamic
* StaticPage component changed to dynamic import
https://virtocommerce.atlassian.net/browse/ST-5178
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.45.0-pr-874-558c-558ca862.zip
> fix: replace static routes with lazy

- client-app/core/utilities/search/facets.test.ts
- client-app/core/utilities/search/facets.ts
Add zero in "includeFrom" facet
https://virtocommerce.atlassian.net/browse/ST-5315
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.44.0-pr-872-f2aa-f2aac4da.zip
> fix: "under 10" facet not checked

- client-app/ui-kit/components/molecules/index.ts
- client-app/ui-kit/components/molecules/types.d.ts
- client-app/ui-kit/components/molecules/widget-skeleton/vc-widget-skeleton.stories.ts
- client-app/ui-kit/components/molecules/widget-skeleton/vc-widget-skeleton.vue
https://virtocommerce.atlassian.net/browse/ST-5462
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.45.0-pr-881-dd0b-dd0bc9aa.zip
> feat: implement vc-widget-skeleton component

- client-app/core/constants/products.ts
- client-app/core/enums/index.ts
- client-app/core/enums/validation-error-object-type.enum.ts
- client-app/shared/cart/components/add-to-cart.vue
- client-app/shared/cart/composables/useCart.ts
Prevent checkout/place order only for selected items with validation errors
https://virtocommerce.atlassian.net/browse/ST-5453
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.45.0-pr-884-e91d-e91de3b4.zip
> fix: prevent checkout/place order only for selected cart items with validation errors

- client-app/shared/layout/components/search-bar/search-bar.vue
https://virtocommerce.atlassian.net/browse/ST-5463
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.45.0-pr-886-15f1-15f1a2e6.zip
> fix: remove trim from user input

- client-app/ui-kit/components/atoms/popover/vc-popover.vue
- client-app/ui-kit/components/molecules/dropdown-menu/vc-dropdown-menu.vue
https://virtocommerce.atlassian.net/browse/ST-5506
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.45.0-pr-890-7938-7938f9fa.zip
> fix: drop-down menu overlaps a sticky header

- client-app/pages/account/quotes.vue
- client-app/shared/account/components/orders.vue
https://virtocommerce.atlassian.net/browse/ST-5534
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.45.0-pr-891-ca77-ca77f91b.zip
> fix(orders): open order on mobile view

- client-app/pages/account/lists.vue
- client-app/shared/wishlists/components/wishlist-card.vue
- client-app/shared/wishlists/components/wishlist-dropdown-menu.vue
- client-app/ui-kit/components/molecules/menu-item/vc-menu-item.vue
- locales/en.json
https://virtocommerce.atlassian.net/browse/ST-5430
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.45.0-pr-883-a92d-a92d51e6.zip
> feat: implement wishlist-card new design

- locales/en.json
https://virtocommerce.atlassian.net/browse/ST-5565
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.46.0-pr-895-ad41-ad41935f.zip
> fix: typo in registration completed message

- client-app/shared/layout/components/search-bar/search-bar.vue
https://virtocommerce.atlassian.net/browse/ST-5457
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.45.0-pr-888-0f8d-0f8d73f8.zip
> fix: "show all" button send GA "search" event

- client-app/shared/wishlists/components/add-or-update-wishlist-modal.vue
https://virtocommerce.atlassian.net/browse/ST-5554
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.46.0-pr-896-2a7d-2a7d5efb.zip
> fix: add description limit in "create wishlist" form

- client-app/pages/account/list-details.vue
- client-app/pages/account/order-details.vue
- client-app/pages/bulk-order.vue
- client-app/shared/cart/components/add-bulk-items-to-cart-results-modal.vue
- client-app/shared/cart/components/add-to-cart.vue
- client-app/shared/cart/composables/useCart.ts
- client-app/shared/cart/types/index.ts
- client-app/shared/cart/utils/index.ts
https://virtocommerce.atlassian.net/browse/ST-5524
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.46.0-pr-894-d72b-d72bc721.zip
> fix: use product ID instead of SKU on validation errors in cart

- client-app/core/api/graphql/catalog/queries/childCategories/index.ts
- client-app/core/api/graphql/catalog/queries/getCategory/index.ts
- client-app/core/api/graphql/schema.json
- client-app/core/api/graphql/types.ts
- client-app/shared/catalog/components/category.vue
- client-app/shared/catalog/composables/useCategory.ts
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.46.0-pr-898-5931-5931d8da.zip
> chore: generate new schema with storeId required

- client-app/ui-kit/components/molecules/input/vc-input.vue
- client-app/ui-kit/components/molecules/quantity/vc-quantity.vue
https://virtocommerce.atlassian.net/browse/ST-4173
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.46.0-pr-897-00d1-00d1c4ff.zip
> fix: don't show zero if quantity is cleared

- client-app/pages/account/quotes.vue
Due to moving to a new "Sort" instrument
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.46.0-pr-903-e97d-e97df3b5.zip
> refactor: replace deprecated sort logic in quotes.vue

- client-app/core/utilities/line-items/index.ts
Show dynamic discount info for line items
https://virtocommerce.atlassian.net/browse/ST-5374
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.47.0-pr-911-8261-8261cc56.zip
> fix: show dynamic discount for line items

- client-app/core/api/graphql/catalog/queries/getProduct/index.ts
- client-app/core/utilities/product/index.ts
- client-app/pages/product.vue
- client-app/shared/catalog/components/product-card-grid.vue
- client-app/shared/catalog/components/product-card-list.vue
- client-app/shared/catalog/components/product-price-block.vue
- client-app/shared/catalog/composables/useProduct.ts
Fix price block for product page and catalog grid/list views for product with disabled variations
https://virtocommerce.atlassian.net/browse/ST-5233
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.47.0-pr-910-bb56-bb5695a8.zip
> fix: price block for product with disabled variations

- client-app/shared/catalog/components/category.vue
- client-app/shared/catalog/components/index.ts
- client-app/shared/catalog/components/products-filters.vue
- locales/en.json
https://virtocommerce.atlassian.net/browse/ST-5638
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.46.0-pr-908-84b5-84b57161.zip
> refactor: remove keyword search in products filters

- client-app/pages/account/profile.vue
https://virtocommerce.atlassian.net/browse/ST-5639
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.46.0-pr-913-16f1-16f1b131.zip
> refactor: remove deprecated useIdentityErrorTranslator from profile.vue

- client-app/core/api/graphql/schema.json
- client-app/core/api/graphql/types.ts
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.47.0-pr-915-e5e1-e5e10a90.zip
> chore: generate gql types

- client-app/pages/account/addresses.vue
- client-app/pages/account/quotes.vue
- client-app/pages/company/info.vue
- client-app/pages/company/members.vue
- client-app/shared/account/components/orders.vue
- client-app/shared/checkout/components/select-address-modal.vue
- client-app/ui-kit/components/organisms/table/vc-table.vue
- locales/en.json
https://virtocommerce.atlassian.net/browse/ST-5509
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.46.0-pr-901-813d-813ded1a.zip
> refactor: add table description for accessibility

- client-app/shared/layout/components/header/_internal/mobile-menu.vue
https://virtocommerce.atlassian.net/browse/ST-5329
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.46.0-pr-907-bdb6-bdb634fa.zip
> fix: mobile-menu scroll

- client-app/core/api/graphql/account/queries/getWishList/getWishlist.graphql
- client-app/core/api/graphql/account/queries/getWishlists/getWishlists.graphql
- client-app/core/api/graphql/types.ts
- client-app/shared/wishlists/components/wishlist-card.vue
https://virtocommerce.atlassian.net/browse/ST-5580
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.47.0-pr-916-b410-b4106fa1.zip
> feat: add saved date for wishlists

- client-app/pages/account/list-details.vue
- client-app/shared/wishlists/composables/useWishlists.ts
Eliminate empty list page blinking on list loading
https://virtocommerce.atlassian.net/browse/ST-5493
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.47.0-pr-909-6027-60275004.zip
> fix: eliminate empty list page blinking on list loading

- client-app/pages/account/list-details.vue
Reset shopping list items pagination on change route
https://virtocommerce.atlassian.net/browse/ST-5614
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.47.0-pr-919-0410-0410d864.zip
> fix: reset shopping list items pagination on change route

- client-app/ui-kit/components/molecules/line-items/vc-line-items.vue
Fix shopping list items background
https://virtocommerce.atlassian.net/browse/ST-5640
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.47.0-pr-920-25a2-25a20364.zip
> fix: wishlist items background

- client-app/ui-kit/components/molecules/line-item/vc-line-item.vue
Open product of line item in separate tab
https://virtocommerce.atlassian.net/browse/ST-4630
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.47.0-pr-921-47d0-47d038e1.zip
> fix: open product of line item in separate tab

- client-app/shared/account/components/account-navigation.vue
https://virtocommerce.atlassian.net/browse/ST-5659
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.47.0-pr-925-9bcb-9bcb382e.zip
> fix: make current wishlist navigation link bold

- client-app/pages/account/list-details.vue
Delete wishlist item as a change without immediate mutation
https://virtocommerce.atlassian.net/browse/ST-5279
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.47.0-pr-926-15ce-15ce896f.zip
> fix: delete wishlist item as a change without immediate mutation

- client-app/core/utilities/properties/index.ts
Check for undefined property values
https://virtocommerce.atlassian.net/browse/VCST-188
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.48.0-pr-930-77ba-77bab2f7.zip
> fix: check for undefined property values

- client-app/ui-kit/components/atoms/tooltip/vc-tooltip.vue
Add extra class for trigger block as component property;
OPUS REQUEST
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.48.0-pr-933-8534-8534f6db.zip
> feat: add possibility to extend tooltip classes

- client-app/builder-preview/builder-preview.plugin.ts
- client-app/shared/static-content/composables/useStaticPage.ts
- client-app/shared/static-content/types/index.ts
https://virtocommerce.atlassian.net/browse/VCST-214
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.48.0-pr-924-aacd-aacdc7c3.zip
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.47.0-pr-924-0118-01187b12.zip
> VCST-214: fix 404 when preview template

- client-app/shared/payment/components/payment-processing-authorize-net.vue
Prevent incorrect bank card form validation on payment process
https://virtocommerce.atlassian.net/browse/VCST-142
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.49.0-pr-934-0809-08090cec.zip
> fix: prevent incorrect bank card form validation on payment process

- .deployment/theme/cloudDeploy.json
- client-app/ui-kit/mocks/line-item.mock.ts
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.49.0-pr-936-acbb-acbb9a7c.zip
> fix: environment urls

- client-app/core/api/graphql/orders/queries/getOrders/getOrdersQuery.graphql
- client-app/core/api/graphql/schema.json
- client-app/core/api/graphql/types.ts
- client-app/core/constants/index.ts
- client-app/core/constants/orders.ts
- client-app/shared/account/components/account-navigation.vue
- client-app/shared/account/components/mobile-orders-filter.vue
- client-app/shared/account/components/orders-filter.vue
- client-app/shared/account/components/orders.vue
- client-app/shared/account/composables/useUserOrders.ts
Dynamic order statuses
https://virtocommerce.atlassian.net/browse/VCST-130
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.49.0-pr-941-1377-1377018e.zip
> feat: dynamic order statuses

- client-app/pages/company/info.vue
https://virtocommerce.atlassian.net/browse/VCST-170
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.49.0-pr-943-e7b9-e7b9aa14.zip
> fix(company-info): company name Save button styles

- client-app/pages/checkout/completed.vue
- client-app/ui-kit/components/molecules/button/vc-button.vue
https://virtocommerce.atlassian.net/browse/VCST-151
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.49.0-pr-944-c46d-c46dbc69.zip
> fix: vc-button icon alignment

- client-app/ui-kit/components/molecules/line-item/vc-line-item.vue
https://virtocommerce.atlassian.net/browse/VCST-453
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.50.0-pr-954-6d97-6d97a91e.zip
> fix(line-item): image styles

- client-app/shared/catalog/components/product-card-list.vue
https://virtocommerce.atlassian.net/browse/VCST-333
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.49.0-pr-946-1564-156422ee.zip
> fix(product-card-list): product name styles

- client-app/shared/notification/composables/useNotifications.ts
https://virtocommerce.atlassian.net/browse/VCST-411
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.50.0-pr-959-ab25-ab25e637.zip
> fix: notifications stack update

- config/settings_data.json
Turn off builder.io connection by default
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.50.0-pr-962-2315-23153601.zip
> refactor: opt-in builder.io

- client-app/core/composables/useThemeContext.ts
- client-app/core/types/theme-context.ts
https://virtocommerce.atlassian.net/browse/VCST-445
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.50.0-pr-951-1011-10116cb1.zip
> fix: load settings from server

- client-app/router/routes/checkout.ts
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.51.0-pr-967-b374-b3743169.zip
> fix: missed slash in payment status

- .vscode/extensions.json
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.51.0-pr-969-0639-0639c07b.zip
> chore: correct vitest recommendation in VS Code

- client-app/router/routes/checkout.ts
https://virtocommerce.atlassian.net/browse/VCST-493
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.51.0-pr-968-23d8-23d82246.zip
> fix:  don't redirect to cart at "payment details" click on failed payment

- client-app/shared/catalog/components/view-mode.vue
https://virtocommerce.atlassian.net/browse/VCST-513
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.51.0-pr-966-954f-954f8d8f.zip
> fix: view mode selector colors on category page

- client-app/core/api/common/composables/useAxios.ts
- client-app/router/routes/checkout.ts
- client-app/shared/files/composables/useFiles.ts
- client-app/ui-kit/components/molecules/file/vc-file.vue
- locales/en.json
- package.json
- yarn.lock
https://virtocommerce.atlassian.net/browse/VCST-342
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.52.0-pr-971-ecd7-ecd74b41.zip
> feat: display file upload progress

- client-app/core/api/graphql/catalog/fragments/property.graphql
- client-app/core/api/graphql/config/cache.ts
https://virtocommerce.atlassian.net/browse/VCST-588
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.52.0-pr-975-8698-8698ae68.zip
> fix: product properties in line item share value

- client-app/shared/catalog/components/product/assets.vue
https://virtocommerce.atlassian.net/browse/VCST-259
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.52.0-pr-980-604d-604d3db5.zip
> fix: product assets layout

- client-app/core/api/graphql/schema.json
- client-app/core/api/graphql/store/queries/getStore/getStore.graphql
- client-app/core/api/graphql/types.ts
- client-app/core/types/theme-context.ts
- client-app/pages/confirm-invitation.vue
- client-app/pages/sign-up.vue
- client-app/shared/account/components/change-password-form.vue
- client-app/shared/account/components/reset-password-form.vue
- client-app/shared/account/composables/usePasswordRequirements.ts
Fetch password requirements from store settings
https://virtocommerce.atlassian.net/browse/VCST-564
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.52.0-pr-982-24b0-24b05c45.zip
> feat: fetch password requirements from store settings

- client-app/shared/catalog/components/category.vue
https://virtocommerce.atlassian.net/browse/VCST-368
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.52.0-pr-992-0bb3-0bb3f271.zip
> fix: catalog margin

- client-app/core/api/graphql/config/cache.ts
- client-app/shared/cart/composables/useCart.ts
- client-app/shared/checkout/composables/useCheckout.ts
- vite.config.ts
https://virtocommerce.atlassian.net/browse/VCST-645
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.52.0-pr-988-617e-617e3af0.zip
> fix: shipment & payment duplication

- client-app/shared/catalog/components/product-card-grid.vue
- client-app/shared/catalog/components/product-card-list.vue
https://virtocommerce.atlassian.net/browse/VCST-632
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.52.0-pr-985-0c73-0c73d5a3.zip
> fix: tooltip styles on product-cards

- README.md
- client-app/ui-kit/components/atoms/types.d.ts
- client-app/ui-kit/components/molecules/types.d.ts
- client-app/ui-kit/components/organisms/types.d.ts
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.54.0-pr-996-f05c-f05c5f66.zip
> chore: changes after vue dev tools upgrade

- client-app/core/api/graphql/catalog/queries/childCategories/index.ts
https://virtocommerce.atlassian.net/browse/VCST-312
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.55.0-pr-1023-d4b3-d4b3900a.zip
> fix: storeId required in ChildCategories query

- README.md
- client-app/core/api/graphql/push-messages/mutations/clearAllPushMessages/index.ts
- client-app/core/api/graphql/push-messages/mutations/markAllPushMessagesRead/index.ts
- client-app/core/api/graphql/push-messages/mutations/markAllPushMessagesUnread/index.ts
- client-app/core/api/graphql/push-messages/mutations/markPushMessageRead/index.ts
- client-app/core/api/graphql/push-messages/mutations/markPushMessageUnread/index.ts
- client-app/core/types/theme-config.ts
- client-app/shared/layout/components/header/_internal/bottom-header.vue
- client-app/shared/layout/components/header/_internal/mobile-header.vue
- client-app/ui-kit/components/organisms/push-messages/vc-push-messages.vue
- config/settings_data.json
https://virtocommerce.atlassian.net/browse/VCST-473
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.55.0-pr-1030-b4ca-b4ca26e3.zip
> refactor: push messages feature flag, fixes & docs

- client-app/shared/company/composables/useOrganizationContactsFilterFacets.ts
https://virtocommerce.atlassian.net/browse/VCST-309
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.55.0-pr-1029-4226-4226ba9d.zip
> fix: status filter for invited company users

- client-app/shared/catalog/components/category.vue
https://virtocommerce.atlassian.net/browse/VCST-837
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.56.0-pr-1038-8800-8800efae.zip
> fix: category sidebar filter stuck

- client-app/pages/account/edit-quote.vue
- client-app/shared/files/index.ts
- client-app/shared/files/utils/index.ts
- client-app/ui-kit/components/molecules/file-uploader/vc-file-uploader.vue
- client-app/ui-kit/components/molecules/file/vc-file.vue
The token is not passed when user downloading the file from quote
https://virtocommerce.atlassian.net/browse/VCST-931
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.56.0-pr-1042-751e-751e3d06.zip
> fix: add headers for file download

- client-app/ui-kit/components/molecules/line-item/vc-line-item.vue
https://virtocommerce.atlassian.net/browse/VCST-924
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.56.0-pr-1044-d13c-d13c85c8.zip
> fix: vc-line-item button & bg colors

- .storybook/preview-head.html
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.57.0-pr-1050-6bc0-6bc07c16.zip
> fix: storybook styles

- locales/en.json
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.57.0-pr-1053-7ca5-7ca5305b.zip
> feat: rename notifications options

- client-app/pages/account/view-quote.vue
https://virtocommerce.atlassian.net/browse/VCST-1121
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.57.0-pr-1057-7f91-7f91378c.zip
> fix: quote status

- client-app/ui-kit/components/atoms/switch/vc-switch.stories.ts
- client-app/ui-kit/components/atoms/switch/vc-switch.vue
- client-app/ui-kit/components/organisms/push-messages/vc-push-messages.vue
https://virtocommerce.atlassian.net/browse/VCST-1088
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.57.0-pr-1055-4bdf-4bdfda57.zip
> fix: vc-switch click on firefox

- client-app/assets/styles/print/atoms/vc-widget.scss
- client-app/pages/cart.vue
- client-app/shared/checkout/components/order-summary.vue
https://virtocommerce.atlassian.net/browse/VCST-911
also removed bottom shadow
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.57.0-pr-1056-23c7-23c73d25.zip
> fix: print styles

- client-app/shared/account/components/orders.vue
https://virtocommerce.atlassian.net/browse/VCST-1151
https://virtocommerce.atlassian.net/browse/VCST-1153
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.58.0-pr-1062-900d-900d018c.zip
> fix: orders filters behavior

- config/settings_data.json
https://virtocommerce.atlassian.net/browse/VCST-967
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.58.0-pr-1075-fbb7-fbb7d065.zip
> feat: add Declined quote status

- client-app/shared/cart/components/add-bulk-items-to-cart-results-modal.vue
- client-app/shared/cart/types/index.ts
- client-app/shared/cart/utils/index.ts
Show deleted product title without link at adding products from shopping list to cart result modal
https://virtocommerce.atlassian.net/browse/VCST-813
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.58.0-pr-1077-5f5d-5f5d3b9c.zip
> fix: deleted product title at adding products from shopping list to cart result modal

- client-app/core/types/addresses.ts
- client-app/shared/checkout/components/select-address-modal.vue
Indicate favorite addresses at checkout
https://virtocommerce.atlassian.net/browse/VCST-1117
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.58.0-pr-1076-0dfc-0dfcd286.zip
> feat: indicate favorite addresses at checkout

- client-app/core/api/graphql/cart/composables/useCartVariables.ts
https://virtocommerce.atlassian.net/browse/VCST-1179
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.58.0-pr-1081-fc11-fc11f72c.zip
> fix: useCartQueryVariables should return computed

- client-app/pages/company/members.vue
https://virtocommerce.atlassian.net/browse/VCST-912
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.58.0-pr-1093-fcb4-fcb40f80.zip
> fix: mobile members block/unblock user button

- client-app/core/composables/useGoogleAnalytics.ts
- client-app/pages/checkout/billing.vue
- client-app/pages/checkout/shipping.vue
- client-app/shared/checkout/composables/useCheckout.ts
https://virtocommerce.atlassian.net/browse/VCST-1247
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.59.0-pr-1109-3e1a-3e1a3c87.zip
> feat: change Google Analytics events flow for sales funnel 

- client-app/ui-kit/components/atoms/markdown-render/vc-markdown-render.vue
https://virtocommerce.atlassian.net/browse/VCST-1084
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.58.0-pr-1092-a260-a26003d4.zip
> fix: vc-markdown-render margins

- client-app/pages/compare-products.vue
- client-app/shared/catalog/components/product-card-compare.vue
https://virtocommerce.atlassian.net/browse/VCST-1234
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.59.0-pr-1104-7784-7784876e.zip
> fix: compare-products styles

- client-app/shared/static-content/components/product-info.vue
https://virtocommerce.atlassian.net/browse/VCST-1242
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.59.0-pr-1105-33f9-33f9ced7.zip
> fix: product details print styles

- client-app/pages/account/order-payment.vue
- client-app/shared/checkout/components/billing-details-section.vue
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.59.0-pr-1114-7a15-7a15b7dc.zip
> fix: show stub if no payment method in order

- client-app/shared/checkout/composables/useCheckout.ts
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.59.0-pr-1115-f557-f557c548.zip
> fix: comment caching

- client-app/pages/account/view-quote.vue
- locales/de.json
- locales/fr.json
Approve/decline buttons width on view quote page
https://virtocommerce.atlassian.net/browse/VCST-1210
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.59.0-pr-1113-36af-36af0b94.zip
> fix: approve/decline buttons width on view quote page

- client-app/shared/builder-io/components/landing-page.vue
- client-app/shared/static-content/components/index.ts
- client-app/shared/static-content/components/products-block.vue
- client-app/shared/static-content/components/slider.vue
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.59.0-pr-1117-e448-e448c0bb.zip
> feat: slider for builder.io

- client-app/core/api/graphql/orders/mutations/createOrderFromCart/index.ts
- client-app/core/composables/useGoogleAnalytics.ts
- client-app/shared/checkout/composables/useCheckout.ts
- client-app/shared/layout/components/search-bar/search-bar.vue
- package.json
- yarn.lock
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.60.0-pr-1126-5310-5310f019.zip
> feat: improve Google Analytics

- client-app/shared/payment/components/payment-processing-skyflow.vue
https://virtocommerce.atlassian.net/browse/VCST-1254
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.60.0-pr-1138-afd2-afd22f6a.zip
> fix: disable `pay now` button

- client-app/core/composables/useGoogleAnalytics.ts
- client-app/pages/account/list-details.vue
https://virtocommerce.atlassian.net/browse/VCST-1373
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.60.0-pr-1140-532b-532b2f3a.zip
> fix: ga crash on add all from wishlist

- client-app/pages/demo-landing.vue
https://virtocommerce.atlassian.net/browse/VCST-1161
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.61.0-pr-1150-fd5f-fd5f6439.zip
> fix: demo landing styles

- client-app/pages/account/order-payment.vue
https://virtocommerce.atlassian.net/browse/VCST-1263
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.61.0-pr-1143-7339-733945bf.zip
> fix: update billing address in order payment page

- client-app/pages/company/members.vue
https://virtocommerce.atlassian.net/browse/VCST-1321
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.61.0-pr-1142-add8-add89bf1.zip
> fix: [mobile] member-list - hide settings dropdown from themselves

- client-app/core/api/graphql/catalog/queries/searchRelatedProducts/searchRelatedProducts.graphql
https://virtocommerce.atlassian.net/browse/VCST-1381
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.61.0-pr-1153-62e0-62e04daa.zip
> fix: min-max validation for related products

- locales/fr.json
https://virtocommerce.atlassian.net/browse/VCST-1357
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.61.0-pr-1151-5d6d-5d6d2344.zip
> fix: add french localization for mobile menu item corporate

- locales/de.json
- locales/fr.json
https://virtocommerce.atlassian.net/browse/VCST-1388
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.61.0-pr-1154-4110-4110eebb.zip
> fix: add french and deutsch localization for validation messages

- client-app/shared/layout/components/header/_internal/mobile-menu.vue
- client-app/ui-kit/components/atoms/radio-button/vc-radio-button.vue
https://virtocommerce.atlassian.net/browse/VCST-1349
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.62.0-pr-1160-cdd0-cdd00578.zip
> feat: different size support for vc-radio-button

- client-app/core/constants/search.ts
- client-app/core/types/search/sorting/sort-info.ts
- client-app/core/utilities/search/sorting.ts
- client-app/shared/account/composables/useUserAddresses.ts
- client-app/shared/account/composables/useUserOrders.ts
- client-app/shared/account/composables/useUserQuotes.ts
- client-app/shared/company/composables/useOrganizationAddresses.ts
- client-app/shared/company/composables/useOrganizationContacts.ts
- client-app/ui-kit/components/organisms/table/vc-table.vue
- client-app/ui-kit/types/index.d.ts
Remove deprecated code related to sorting
Refactor vc-table to generic items
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.62.0-pr-1169-821b-821bf52b.zip
> feat: remove deprecated sort

- client-app/assets/styles/_colors.scss
- client-app/shared/layout/components/header/_internal/mobile-header.vue
https://virtocommerce.atlassian.net/browse/VCST-1245
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.62.0-pr-1167-4667-466772b9.zip
> fix: mobile search bar bg color

- client-app/broadcast.ts
- client-app/core/types/theme-config.ts
- client-app/shared/layout/components/header/_internal/bottom-header.vue
- client-app/shared/layout/components/header/_internal/mobile-header.vue
- config/settings_data.json
https://virtocommerce.atlassian.net/browse/VCST-1417
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.62.0-pr-1165-a231-a231ff3a.zip
> feat: add default return url setting

- client-app/core/api/graphql/index.ts
- client-app/pages/account/edit-quote.vue
- client-app/pages/account/quotes.vue
- client-app/pages/account/view-quote.vue
- client-app/pages/cart.vue
- client-app/shared/account/composables/index.ts
- client-app/shared/account/composables/useUserQuote.ts
- client-app/shared/cart/composables/useCart.ts
1. Decrease main bundle size
2. Move quotes to separate chunk
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.62.0-pr-1171-c553-c5536201.zip
> chore: refactor quotes chunk

- client-app/pages/welcome.vue
https://virtocommerce.atlassian.net/browse/VCST-1481
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.62.0-pr-1172-c2f9-c2f967e1.zip
> fix: missing home page button on the succesful registration page

- client-app/shared/layout/components/search-bar/search-bar.vue
https://virtocommerce.atlassian.net/browse/VCST-1233
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.62.0-pr-1168-171c-171c5bc7.zip
> fix: search dropdown width

- client-app/shared/catalog/components/in-stock.vue
https://virtocommerce.atlassian.net/browse/VCST-1409
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.1.0-pr-1177-5e6f-5e6f5c54.zip
> fix: in-stock text margin

- client-app/app-runner.ts
- client-app/builder-preview/builder-preview.plugin.ts
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.1.0-pr-1183-5d8f-5d8f98a1.zip
> VCST-1499: fix interaction with page builder

- client-app/shared/catalog/components/product-price-block.vue
https://virtocommerce.atlassian.net/browse/VCST-1410
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.1.0-pr-1186-1b73-1b73d256.zip
> fix: delete share popup arrow

- client-app/core/composables/useGoogleAnalytics.ts
https://virtocommerce.atlassian.net/browse/VCST-860
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.1.0-pr-1191-d7fc-d7fcd7e3.zip
> fix: calling ga methods while the module not initialized causes errors

- .github/workflows/storybook-ci.yml
https://virtocommerce.atlassian.net/browse/VCST-1513
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.1.0-pr-1195-1f9c-1f9c843e.zip
> chore: turn off auto storybook build on pull request

- client-app/shared/catalog/components/image-gallery.vue
https://virtocommerce.atlassian.net/browse/VCST-1531
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.1.0-pr-1196-9ad6-9ad60dbb.zip
**Before:**
**After:**
> chore: reduce bundle size

- client-app/pages/matcher/priorityManager.test.ts
- client-app/pages/matcher/priorityManager.ts
https://virtocommerce.atlassian.net/browse/VCST-1533
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.1.0-pr-1198-e562-e5629742.zip
> fix: loader shown instead of 404

- client-app/pages/matcher/internal.vue
https://virtocommerce.atlassian.net/browse/VCST-1533
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.1.0-pr-1200-b8fc-b8fccd72.zip
> fix: loader show instead of 404

- client-app/public/firebase-messaging-sw.js
https://virtocommerce.atlassian.net/browse/VCST-1536
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.2.0-pr-1202-3cb4-3cb44432.zip
> feat: open all notifications page on push message click

- client-app/pages/branch.vue
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.2.0-pr-1206-f057-f0577dc1.zip
> feat: rollback branch.vue

- client-app/core/types/theme-config.ts
- client-app/pages/matcher/internal.vue
- client-app/pages/matcher/matcher.vue
- client-app/public/config/settings_data.json
- client-app/shared/layout/components/login-form-section/login-form-section.vue
https://virtocommerce.atlassian.net/browse/VCST-1542
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.2.0-pr-1207-0c2d-0c2dd9db.zip
> feat: remove login form from main page when signed in

- client-app/shared/layout/components/language-selector/language-selector.vue
https://virtocommerce.atlassian.net/browse/VCST-1509
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.2.0-pr-1204-9439-9439171d.zip
> fix: mobile language-selector

- client-app/pages/matcher/builderIo/customComponents.ts
- client-app/shared/catalog/components/category.vue
- client-app/shared/static-content/components/slider.vue
- client-app/ui-kit/components/atoms/container/vc-container.vue
https://virtocommerce.atlassian.net/browse/VCST-1565
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.2.0-pr-1209-8108-81080020.zip
> feat: add transparent prop to builder.io components

- .eslintrc.cjs
- client-app/core/composables/useRouteQueryParam.ts
- tsconfig.node.json
remove some TODO
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.1.0-pr-1199-eedd-eedddf4a.zip
> chore: update eslint config

- client-app/ui-kit/components/atoms/checkbox/vc-checkbox.vue
https://virtocommerce.atlassian.net/browse/VCST-1137
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.2.0-pr-1215-ee1b-ee1ba1a9.zip
> fix: make checkbox visible when print

- client-app/core/constants/modules.ts
- client-app/router/routes/account.ts
- client-app/shared/account/components/account-navigation.vue
- client-app/shared/layout/components/header/_internal/bottom-header.vue
- client-app/shared/layout/components/header/_internal/mobile-header.vue
- client-app/shared/push-messages/composables/usePushMessages.ts
- client-app/shared/push-messages/composables/useWebPushNotifications/index.ts
- client-app/shared/push-messages/composables/useWebPushNotifications/useWebPushNotificationsModule.ts
https://virtocommerce.atlassian.net/browse/VCST-1538
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.2.0-pr-1219-ce71-ce716167.zip
> feat: application can run without push messages module

- client-app/shared/notification/components/notifications-host.vue
- client-app/shared/notification/composables/useNotifications.ts
- client-app/shared/notification/types/index.ts
- client-app/ui-kit/components/molecules/alert/vc-alert.vue
https://virtocommerce.atlassian.net/browse/VCST-1556
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.2.0-pr-1214-ed50-ed50272f.zip
> feat: redesign notification-host

- client-app/shared/catalog/composables/useProductsFilters.ts
Fix for category page
https://virtocommerce.atlassian.net/browse/VCST-1475
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.2.0-pr-1222-34bc-34bc6a5b.zip
> fix: temporary fix for category page in-stock, branches and sorting

- client-app/shared/push-messages/composables/usePushMessages.ts
https://virtocommerce.atlassian.net/browse/VCST-1538
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.2.0-pr-1224-c6e7-c6e71bb6.zip
> fix: application can run without push messages module

- client-app/builder-preview/builder-preview.plugin.ts
* handle swap event  in builder preview
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.2.0-pr-1218-6eae-6eaea1b2.zip
> VCST-1576: update preview when blocks were swapped

- client-app/pages/matcher/matcher.vue
- client-app/pages/matcher/slug-content.vue
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.2.0-pr-1211-cce6-cce684b6.zip
> VCST-1452: remove homepage slug alias

- client-app/pages/product.vue
- client-app/shared/catalog/components/category.vue
- client-app/shared/catalog/composables/useProductsFilters.ts
https://virtocommerce.atlassian.net/browse/VCST-1351
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.2.0-pr-1225-5d66-5d66415d.zip
> fix: custom facets

- client-app/public/content/pages/homepage.page
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.2.0-pr-1226-d8ba-d8ba454f.zip
> fix: remove reserved permalink

- client-app/ui-kit/components/organisms/confirmation-modal/vc-confirmation-modal.vue
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.2.0-pr-1230-9f2c-9f2c187c.zip
> fix: vc-confirmation-modal icon color

- client-app/pages/matcher/internal.vue
- client-app/pages/matcher/priorityManager.test.ts
- client-app/pages/matcher/priorityManager.ts
https://virtocommerce.atlassian.net/browse/VCST-1601
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.2.0-pr-1233-3d3c-3d3cd128.zip
> fix: internal previewer status detection

- client-app/pages/account/notifications.vue
https://virtocommerce.atlassian.net/browse/VCST-1600
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.2.0-pr-1232-59b4-59b4e4b3.zip
> fix: notifications popup width

- client-app/shared/catalog/components/category.vue
- client-app/shared/catalog/composables/useProductsFilters.ts
https://virtocommerce.atlassian.net/browse/VCST-1500
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.3.0-pr-1234-3347-33470a46.zip
> fix: category filter

- client-app/shared/checkout/components/billing-details-section.vue
- client-app/shared/checkout/components/proceed-to.vue
- client-app/shared/checkout/components/shipping-details-section.vue
- client-app/shared/notification/components/notifications-host.vue
- client-app/shared/payment/components/bank-card-form.vue
- client-app/shared/payment/components/payment-processing-authorize-net.vue
- client-app/shared/payment/components/payment-processing-skyflow.vue
- client-app/ui-kit/components/atoms/checkbox/vc-checkbox.vue
- client-app/ui-kit/components/molecules/address-selection/vc-address-selection.vue
- client-app/ui-kit/components/molecules/button/vc-button.vue
- client-app/ui-kit/components/molecules/input/vc-input.vue
- client-app/ui-kit/components/molecules/line-item/vc-line-item.vue
- client-app/ui-kit/components/molecules/line-items/vc-line-items.vue
- client-app/ui-kit/components/molecules/quantity/vc-quantity.vue
- client-app/ui-kit/components/molecules/select/vc-select.vue
https://virtocommerce.atlassian.net/jira/software/projects/VCST/boards/126?selectedIssue=VCST-1480
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.3.0-pr-1237-239e-239ef016.zip
> feat: add test markup

- client-app/pages/product.vue
https://virtocommerce.atlassian.net/browse/VCST-1648
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.3.0-pr-1242-fc71-fc71b732.zip
> chore: update product variations query

- client-app/shared/catalog/components/facet-filter.vue
https://virtocommerce.atlassian.net/browse/VCST-1644
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.3.0-pr-1240-1487-1487209a.zip
> feat: facets count separator

- README.md
https://virtocommerce.atlassian.net/browse/VCST-1535
> docs: dependency analysis

- client-app/app-runner.ts
https://virtocommerce.atlassian.net/browse/VCST-1215
> feat: add alert if store not found

- package.json
Allow to run the built artifact in the local environment
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.3.0-pr-1249-8dc4-8dc4d71d.zip
> feat: add preview command

- client-app/shared/payment/components/payment-processing-skyflow.vue
- package.json
- yarn.lock
https://virtocommerce.atlassian.net/browse/VCST-1570
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.3.0-pr-1241-5efe-5efe9064.zip
> feat: card icon for skyflow payment method

- client-app/shared/push-messages/composables/usePushMessages.ts
Notifications page has an error in the console and render the blank page.
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.4.0-pr-1255-df11-df11bdb0.zip
> fix: notifications page

- package.json
> chore: revert release version flag

- package.json
- yarn.lock
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.3.0-pr-1251-5a72-5a72f1cc.zip
> chore: upgrade yarn to 4.4.0

- client-app/pages/account/quotes.vue
- client-app/pages/company/members.vue
- client-app/pages/confirm-invitation.vue
- client-app/pages/sign-up.vue
- client-app/shared/account/components/orders.vue
https://virtocommerce.atlassian.net/browse/VCST-95
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.3.0-pr-1243-6b50-6b501c86.zip
> fix: stop autoremoving space

- client-app/shared/catalog/composables/useProducts.ts
https://virtocommerce.atlassian.net/browse/VCST-1637
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.3.0-pr-1254-4470-4470fe43.zip
> fix: facets order reactivity

- .github/workflows/storybook-ci.yml
- .github/workflows/theme-ci.yml
https://virtocommerce.atlassian.net/browse/VCST-1573
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.4.0-pr-1261-c11f-c11f3f52.zip
> chore: ci auto deploy

- .github/workflows/storybook-ci.yml
- .github/workflows/theme-ci.yml
https://virtocommerce.atlassian.net/jira/software/projects/VCST/boards/126?assignee=621c47c0302c6b006af0a1cd&selectedIssue=VCST-1573
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.4.0-pr-1268-b5c3-b5c38c77.zip
> chore: trigger theme and storebook deploy only for `dev` branch

- README.md
Skyflow module is required to install on dev machine / environment, otherwise GraphQL types generation will fail because of lacking `getSkyflowCards` query and `deleteSkyflowCard` mutation
> docs: add info about required skyflow module

- client-app/core/api/graphql/whiteLabeling/queries/index.ts
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.4.0-pr-1271-5bee-5beeb749.zip
> feat: store level whitelabeling

- .github/workflows/theme-ci.yml
Replaces the process of deploying to the cloud with creating a commit or PR in the deploy repo
https://virtocommerce.atlassian.net/jira/software/projects/VCST/boards/126?assignee=621c47c0302c6b006af0a1cd&selectedIssue=VCST-1573
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.4.0-pr-1270-8caf-8cafbe9e.zip
> chore: code delivery optimization

- client-app/shared/push-messages/composables/usePushMessages.ts
https://virtocommerce.atlassian.net/browse/VCST-1662
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.4.0-pr-1276-6e61-6e6160a2.zip
> fix: remove circular dependency

- client-app/pages/account/list-details.vue
https://virtocommerce.atlassian.net/browse/VCST-1494
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.4.0-pr-1275-2cff-2cffb6e5.zip
> fix: forbidden access to list opens 403 page

- client-app/shared/layout/components/search-bar/_internal/search-bar-product-card.vue
https://virtocommerce.atlassian.net/browse/VCST-1719
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.4.0-pr-1278-3a29-3a292390.zip
> fix: search dropdown minVariationPrice

- client-app/pages/product.vue
- client-app/shared/catalog/components/product/variations.vue
- client-app/ui-kit/components/atoms/container/vc-container.vue
https://virtocommerce.atlassian.net/browse/VCST-1588
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.5.0-pr-1280-dcc3-dcc3e4e8.zip
> feat: add a button to expand variations table

- client-app/core/api/graphql/account/queries/getMe/getMeQuery.graphql
- client-app/core/api/graphql/account/queries/getMe/index.ts
- client-app/core/api/graphql/push-messages/types.ts
- client-app/core/api/graphql/schema.json
- client-app/core/api/graphql/types.ts
- client-app/core/constants/local-storage-keys.ts
- client-app/shared/account/composables/useSignMeIn.ts
- client-app/shared/account/composables/useSignMeOut.ts
- client-app/shared/account/composables/useUser.ts
https://virtocommerce.atlassian.net/browse/VCST-1763
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.5.0-pr-1283-19fe-19fe5e66.zip
> feat: ensure persistence of anonymous user

- .github/workflows/storybook-ci.yml
- .github/workflows/theme-ci.yml
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.5.0-pr-1287-cd1e-cd1e9c57.zip
> feat: enable deppoy PR creation on PR for theme and storybook

- client-app/pages/auth/callback.vue
- client-app/shared/account/components/sign-in-form.vue
- client-app/shared/account/composables/useSignMeIn.ts
- client-app/shared/account/types/index.ts
https://virtocommerce.atlassian.net/browse/VCST-1739
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.5.0-pr-1291-3ae7-3ae7d626.zip
> feat: add merge cart during authorization callback handling

- locales/de.json
- locales/fr.json
Add German and French locales for product page
https://virtocommerce.atlassian.net/browse/VCST-1718
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.5.0-pr-1296-5e98-5e98f6ab.zip
> feat: add german and french locales for product page

- client-app/shared/catalog/composables/useProduct.ts
- client-app/shared/catalog/composables/useProducts.ts
https://virtocommerce.atlassian.net/browse/VCST-1650
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.5.0-pr-1297-a2d4-a2d4e1ad.zip
> chore: remove workaround for shollowRef

- client-app/shared/catalog/components/category.vue
https://virtocommerce.atlassian.net/browse/VCST-1782
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.5.0-pr-1304-2aeb-2aeb6219.zip
> fix: catalog pagination

- client-app/core/utilities/categories/index.test.ts
https://virtocommerce.atlassian.net/browse/VCST-1796
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.6.0-pr-1308-7503-750378f1.zip
> chore: add unit tests for categories utilites

- client-app/core/utilities/address/index.test.ts
- client-app/core/utilities/address/index.ts
https://virtocommerce.atlassian.net/browse/VCST-1795
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.6.0-pr-1307-d102-d102586f.zip
> chore: add unit tests for address utilites

- client-app/ui-kit/components/molecules/file/vc-file.vue
https://virtocommerce.atlassian.net/browse/VCST-1816
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.6.0-pr-1311-db30-db300b02.zip
> fix: long file name

- client-app/shared/catalog/components/category-selector.vue
https://virtocommerce.atlassian.net/browse/VCST-1764
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.6.0-pr-1310-dece-dece0aa3.zip
> fix: hide widget if catalog is empty

- client-app/core/utilities/common/index.test.ts
- client-app/core/utilities/common/index.ts
- client-app/modules/quotes/pages/edit-quote.vue
- client-app/modules/quotes/useUserQuote.ts
https://virtocommerce.atlassian.net/browse/VCST-1798
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.6.0-pr-1315-4e3a-4e3ae86c.zip
> chore: add unit tests for common utilities

- client-app/shared/layout/components/header/_internal/bottom-header.vue
- client-app/shared/layout/components/header/_internal/mobile-header.vue
- client-app/shared/layout/composables/index.ts
- client-app/shared/layout/composables/useDeferShortCart.ts
https://virtocommerce.atlassian.net/browse/VCST-1782
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.6.0-pr-1303-a1fd-a1fd5880.zip
> fix: cart infinity loading

- client-app/shared/catalog/components/product-price-block.vue
- client-app/shared/compare/components/add-to-compare-catalog.vue
- client-app/shared/wishlists/components/add-to-list.vue
https://virtocommerce.atlassian.net/browse/VCST-1821
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.6.0-pr-1312-c62b-c62bf5a5.zip
> fix: replace tooltip by title on add-to-list & add-to-compare-catalog

- client-app/ui-kit/components/atoms/markdown-render/vc-markdown-render.vue
https://virtocommerce.atlassian.net/browse/VCST-1841
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.6.0-pr-1316-eb84-eb846071.zip
> fix: vc-markdown-render table styles

- client-app/shared/cart/components/add-bulk-items-to-cart-results-modal.vue
https://virtocommerce.atlassian.net/browse/VCST-1864
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.6.0-pr-1326-0181-0181e2db.zip
> fix: add-bulk-items-to-cart-results-modal styles

- client-app/shared/cart/components/add-bulk-items-to-cart-results-modal.vue
- client-app/shared/catalog/components/facet-filter.vue
- client-app/shared/sign-in/components/identity-provider.vue
https://virtocommerce.atlassian.net/browse/VCST-1862
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.6.0-pr-1325-5b21-5b2117bb.zip
> fix: facet-filter fade click styles

- client-app/shared/catalog/components/facet-filter.vue
- client-app/ui-kit/components/atoms/checkbox/vc-checkbox.vue
- client-app/ui-kit/components/molecules/menu-item/vc-menu-item.vue
https://virtocommerce.atlassian.net/browse/VCST-1838
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.6.0-pr-1317-fffe-fffed6bc.zip
> fix: update facet-filter

- client-app/ui-kit/components/molecules/address-form/vc-address-form.vue
https://virtocommerce.atlassian.net/browse/VCST-1878
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.6.0-pr-1328-b456-b45662fd.zip
> fix: vc-address-form input cut

- client-app/shared/catalog/components/product-card-list.vue
- client-app/shared/catalog/components/product-price-block.vue
- client-app/shared/compare/components/add-to-compare-catalog.vue
- client-app/shared/wishlists/components/add-to-list.vue
https://virtocommerce.atlassian.net/browse/VCST-1879
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.6.0-pr-1329-8adb-8adb5336.zip
> fix: add-to-compare-catalog wrong highlight

- client-app/shared/catalog/composables/useCategory.ts
https://virtocommerce.atlassian.net/browse/VCST-1683
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.6.0-pr-1327-1bba-1bbaa4b2.zip
> chore: refactor use category

- client-app/builder-preview/builder-preview.plugin.ts
* add events to handle in builder preview
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.6.0-pr-1340-061a-061a3c3a.zip
> VCST-1896: update preview when block was deleted

- client-app/core/composables/useModuleSettings.ts
- client-app/core/composables/useNavigations.ts
- client-app/core/composables/usePageHead.ts
- client-app/core/constants/modules.ts
- client-app/core/types/theme-config.ts
- client-app/public/config/settings_data.json
- client-app/shared/catalog/components/category.vue
- client-app/shared/layout/components/header/_internal/mobile-header.vue
- client-app/shared/layout/components/header/_internal/top-header.vue
- client-app/shared/layout/components/search-bar/search-bar.vue
- scripts/check-yarn-version.js
https://virtocommerce.atlassian.net/browse/VCST-1584
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.6.0-pr-1332-4a42-4a42b0ef.zip
> feat: get some settings from store

- .eslintrc.cjs
TODO transformed to tasks
https://virtocommerce.atlassian.net/browse/VCST-1888
https://virtocommerce.atlassian.net/browse/VCST-1889
https://virtocommerce.atlassian.net/browse/VCST-1890
https://virtocommerce.atlassian.net/browse/VCST-1891
https://virtocommerce.atlassian.net/browse/VCST-1892
https://virtocommerce.atlassian.net/browse/VCST-1893
https://virtocommerce.atlassian.net/browse/VCST-1894
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.6.0-pr-1338-5bef-5befdc68.zip
> chore: remove todo from eslint

- .github/workflows/theme-ci.yml
[](https://virtocommerce.atlassian.net/jira/software/projects/VCST/boards/126?assignee=621c47c0302c6b006af0a1cd&selectedIssue=VCST-1927)
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.7.0-pr-1350-586d-586dd3a3.zip
> VCST-1927: Set project type

- .github/workflows/storybook-ci.yml
https://virtocommerce.atlassian.net/jira/software/projects/VCST/boards/126?assignee=621c47c0302c6b006af0a1cd&selectedIssue=VCST-1792
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.6.0-pr-1347-7a63-7a63c19b.zip
> chore: remove GitHub warnings during build

- client-app/shared/catalog/components/facet-filter.vue
- client-app/shared/catalog/components/products-filters.vue
https://virtocommerce.atlassian.net/browse/VCST-1902
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.6.0-pr-1343-9143-91435e24.zip
> fix: facet-filters console warnings

- client-app/shared/fulfillmentCenters/components/branch-item.vue
- client-app/shared/fulfillmentCenters/components/branches-modal.vue
- client-app/shared/wishlists/components/add-to-wishlists-modal.vue
https://virtocommerce.atlassian.net/browse/VCST-1840
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.7.0-pr-1354-3674-367495c9.zip
> fix: decrease paddings in branch-modal & add-to-wishlists-modal

- client-app/ui-kit/components/molecules/address-form/vc-address-form.vue
https://virtocommerce.atlassian.net/browse/VCST-1900
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.7.0-pr-1355-1bf7-1bf7de69.zip
> fix: address form validation

- client-app/shared/sign-in/components/identity-providers.vue
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.7.0-pr-1362-1e1f-1e1f1f4d.zip
> fix: dynamic import with variable

- client-app/core/composables/useNavigations.ts
https://virtocommerce.atlassian.net/browse/VCST-1932
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.7.0-pr-1352-1658-16583c6a.zip
> feat: add empty string check for catalog_menu_link_list_name

- .eslintrc.cjs
https://virtocommerce.atlassian.net/browse/VCST-1890
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.7.0-pr-1366-b710-b710246b.zip
> feat: switch to error vue/no-setup-props-reactivity-loss

- .eslintrc.cjs
Reverts VirtoCommerce/vc-frontend#1366
Artifact URL:
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.7.0-pr-1371-9bf0-9bf05767.zip
> Revert "feat: switch to error vue/no-setup-props-reactivity-loss"

- .eslintrc.cjs
Reverts VirtoCommerce/vc-frontend#1365
Artifact URL:
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.7.0-pr-1372-86c6-86c62205.zip
> Revert "chore: turn on unbound-method"

- .eslintrc.cjs
- client-app/pages/branch.vue
- client-app/shared/account/components/account-navigation-link.vue
- client-app/shared/catalog/components/facet-filter.vue
- client-app/shared/catalog/components/product-card-recently-browsed.vue
- client-app/shared/company/components/filter-facet.vue
- client-app/ui-kit/components/molecules/collapsible-content/vc-collapsible-content.vue
- client-app/ui-kit/components/organisms/add-to-cart/vc-add-to-cart.vue
https://virtocommerce.atlassian.net/browse/VCST-1890
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.7.0-pr-1374-7f81-7f81fa1a.zip
> chore: switch `vue/no-setup-props-reactivity-loss` to error

- client-app/shared/catalog/components/category.vue
- client-app/ui-kit/components/molecules/chip/vc-chip.vue
https://virtocommerce.atlassian.net/browse/VCST-1976
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.7.0-pr-1363-8eb5-8eb5c5c1.zip
> fix: category layout improvements & chip width

- client-app/shared/catalog/components/facet-filter.vue
- client-app/ui-kit/components/molecules/menu-item/vc-menu-item.vue
https://virtocommerce.atlassian.net/browse/VCST-1965
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.7.0-pr-1368-69aa-69aaa337.zip
> fix: vc-menu-item items align top

- client-app/ui-kit/components/atoms/icon/vc-icon.vue
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.7.0-pr-1375-9a01-9a01107b.zip
> fix: icons color

- client-app/ui-kit/components/organisms/add-to-cart/vc-add-to-cart.vue
https://virtocommerce.atlassian.net/browse/VCST-2026
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.7.0-pr-1382-06a0-06a0ce1d.zip
> fix: cart item quantity limit

- client-app/pages/product.vue
- client-app/shared/catalog/components/category.vue
- client-app/shared/catalog/components/category/filters-popup-sidebar.vue
- client-app/shared/catalog/composables/useProducts.ts
https://virtocommerce.atlassian.net/browse/VCST-2025
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.7.0-pr-1381-2639-2639604d.zip
> fix: apply branches filter

- .eslintrc.cjs
- client-app/core/composables/useErrorsTranslator.ts
- client-app/core/types/options.ts
Before
After
https://virtocommerce.atlassian.net/browse/VCST-1894
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.7.0-pr-1376-ec21-ec21bff3.zip
> chore: turn on unbound-method rule

- package.json
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.8.0-pr-1384-69f4-69f4538d.zip
> fix: version in package.json

- tailwind.config.ts
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.8.0-pr-1391-4531-45316da1.zip
> fix: tw-elements colors overriding issue

- client-app/ui-kit/components/molecules/input/vc-input.stories.ts
- client-app/ui-kit/components/molecules/input/vc-input.vue
- client-app/ui-kit/components/molecules/menu-item/vc-menu-item.vue
- client-app/ui-kit/components/molecules/select/vc-select.stories.ts
- client-app/ui-kit/components/molecules/select/vc-select.vue
https://virtocommerce.atlassian.net/browse/VCST-468
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.7.0-pr-1377-86c0-86c0e9d5.zip
> feat: implement xs size for VcSelect

- client-app/core/api/graphql/push-messages/types.ts
- client-app/core/api/graphql/schema.json
- client-app/core/api/graphql/types.ts
- client-app/modules/customer-reviews/api/graphql/types.ts
- client-app/modules/quotes/api/graphql/types.ts
- client-app/shared/catalog/components/product/variations-default.vue
- client-app/shared/catalog/components/product/variations-table.vue
- package.json
- yarn.lock
Also changed type in variation-table
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.8.0-pr-1403-b781-b781a999.zip
> chore: update graphql types

- client-app/ui-kit/components/molecules/address-form/vc-address-form.vue
https://virtocommerce.atlassian.net/browse/VCST-2137
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.8.0-pr-1410-2d70-2d70131a.zip
> fix: vc-address-form divider styles

- client-app/app-runner.ts
- client-app/modules/push-messages/composables/usePushMessages.ts
- client-app/modules/push-messages/constants/index.ts
- client-app/modules/push-messages/index.ts
- client-app/router/routes/account.ts
- client-app/router/routes/main.ts
https://virtocommerce.atlassian.net/browse/VCST-2163
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.9.0-pr-1421-28e0-28e0ef3a.zip
> fix: push messages module feature flags

- client-app/ui-kit/composables/useQuantityValidationSchema.test.ts
https://virtocommerce.atlassian.net/browse/VCST-2190
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.9.0-pr-1423-da05-da05cd83.zip
> fix: enhance useQuantityValidationSchema unit test to contain error type

- client-app/ui-kit/components/atoms/address-line/vc-address-line.vue
- client-app/ui-kit/types/index.d.ts
https://virtocommerce.atlassian.net/browse/VCST-1865
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.9.0-pr-1426-17ab-17ab6b7e.zip
> chore: decouple ui kit address type from core

- README.md
Frontend requirements in README updated to correspond current status.
> docs: update requirements

- .vscode/settings.json
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.9.0-pr-1408-a44e-a44ea32f.zip
> chore: add modules localization support for i18n ally (recommended IDE extension)

- client-app/pages/catalog.vue
https://virtocommerce.atlassian.net/browse/VCST-2238
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.9.0-pr-1438-6b5f-6b5fcfe8.zip
> fix: catalog title

- client-app/shared/catalog/components/facet-filter.vue
https://virtocommerce.atlassian.net/browse/VCST-2232
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.10.0-pr-1441-66de-66decdbe.zip
> fix: facet-filter fade styles

- client-app/core/api/graphql/schema.json
- client-app/core/api/graphql/types.ts
- client-app/modules/customer-reviews/api/graphql/types.ts
- client-app/modules/push-messages/api/graphql/types.ts
- client-app/modules/quotes/api/graphql/types.ts
- client-app/shared/cart/composables/useCart.ts
https://virtocommerce.atlassian.net/browse/VCST-2157
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.10.0-pr-1445-5ca4-5ca498be.zip
> fix: graphql schema mismatch

- .storybook/preview.ts
Set English as the default language for the UI Kit Storybook
https://virtocommerce.atlassian.net/browse/VCST-2231
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.10.0-pr-1455-1225-12259a4f.zip
> fix: storybook locale messages

- .github/CODEOWNERS
Combined with [auto assignment](https://docs.github.com/en/organizations/organizing-members-into-teams/managing-code-review-settings-for-your-team#about-auto-assignment) configuration in team settings it will will automatically assign all team members as a reviewers (configuration is flexiable and can be customized to exclude or include specific people and files)
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.10.0-pr-1449-05c2-05c252e4.zip
> chore: add CODEOWNERS file to automatically request review

- client-app/ui-kit/components/atoms/radio-button/vc-radio-button.vue
- client-app/ui-kit/components/organisms/add-to-cart/vc-add-to-cart.vue
- client-app/ui-kit/enums/index.ts
https://virtocommerce.atlassian.net/browse/VCST-2255
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.10.0-pr-1457-796d-796d1105.zip
> feat: change ui components to implement configurable products feature

- .storybook/preview.ts
- client-app/app-runner.ts
- client-app/core/composables/useLanguages.ts
- client-app/modules/customer-reviews/index.ts
- client-app/modules/push-messages/index.ts
- client-app/modules/quotes/index.ts
- client-app/modules/utils.ts
- client-app/ui-kit/locales/de.json
- client-app/ui-kit/locales/en.json
- client-app/ui-kit/locales/fr.json
- client-app/ui-kit/utilities/getLocales.ts
- locales/de.json
- locales/en.json
- locales/fr.json
https://virtocommerce.atlassian.net/browse/VCST-2277
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.10.0-pr-1459-a61b-a61b50d9.zip
> chore: separate UI kit locales

- client-app/shared/catalog/components/product/variations-table.vue
https://virtocommerce.atlassian.net/browse/VCST-2275
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.10.0-pr-1461-00da-00daf226.zip
> fix: variations-table header styles

- client-app/shared/layout/components/header/_internal/bottom-header.vue
https://virtocommerce.atlassian.net/browse/VCST-2133
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.10.0-pr-1468-8881-8881ac3f.zip
> fix: catalog menu remains open on route change

- client-app/shared/checkout/components/select-address-modal.vue
https://virtocommerce.atlassian.net/browse/VCST-2332
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.10.0-pr-1470-96a0-96a0f7e6.zip
> fix: select-address-modal buttons

- client-app/shared/catalog/components/image-gallery.vue
https://virtocommerce.atlassian.net/browse/VCST-2326
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.10.0-pr-1471-e281-e28114da.zip
> fix: image-gallery thumbs border

- client-app/core/api/graphql/schema.json
- client-app/core/api/graphql/types.ts
- client-app/modules/customer-reviews/api/graphql/types.ts
- client-app/modules/push-messages/api/graphql/types.ts
- client-app/modules/quotes/api/graphql/types.ts
Generate types based on the latest platform updates
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.10.0-pr-1473-0c7a-0c7a768d.zip
> chore: generate types

- client-app/modules/customer-reviews/constants.ts
- client-app/modules/customer-reviews/useCustomerReviews.ts
- client-app/pages/product.vue
- client-app/shared/catalog/components/display-products.vue
- client-app/shared/catalog/components/product/properties.vue
Removed the dependency on useCustomerReviews in the Core project to improve module separation.
https://virtocommerce.atlassian.net/browse/VCST-2281
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.10.0-pr-1462-3cad-3cada9ea.zip
> chore: refactor CustomerReviews settings

- package.json
Revert new tag due to bug fix
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.10.0-pr-1480-c53b-c53bcc25.zip
> chore: revert 2.11.0

- client-app/pages/matcher/matcher.vue
- client-app/pages/matcher/slug-content.vue
- client-app/pages/matcher/virto-pages/virto-pages.vue
- client-app/shared/common/composables/useSlugInfo.ts
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.11.0-pr-1479-44aa-44aa1a5b.zip
> fix: trigger SlugInfo request when a category is selected

- client-app/core/api/common/utils/to-server-error.ts
- client-app/core/composables/useAuth.ts
- client-app/core/composables/useLanguages.ts
- client-app/core/composables/useMutationBatcher.test.ts
- client-app/core/composables/useMutationBatcher.ts
- client-app/core/composables/useSyncMutationBatchers.test.ts
- client-app/shared/catalog/composables/useConfigurableProduct.test.ts
- client-app/ui-kit/components/molecules/carousel/vc-carousel.vue
- client-app/ui-kit/components/molecules/select/vc-select.stories.ts
- client-app/ui-kit/types/index.d.ts
https://virtocommerce.atlassian.net/browse/VCST-1994
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.10.0-pr-1472-c933-c9336ed8.zip
> fix: eslint typescript issues

- client-app/pages/company/info.vue
https://virtocommerce.atlassian.net/browse/VCST-2287
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.11.0-pr-1476-7fdf-7fdfffa8.zip
> fix: company info button

- client-app/shared/common/composables/useSlugInfo.ts
- client-app/shared/layout/components/header/_internal/mobile-header.vue
- client-app/ui-kit/components/molecules/input/vc-input.vue
https://virtocommerce.atlassian.net/browse/VCST-2329
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.11.0-pr-1481-6a07-6a074f47.zip
> fix: search input on mobile

- client-app/modules/quotes/pages/view-quote.vue
- client-app/pages/account/order-details.vue
- client-app/pages/product.vue
- client-app/shared/checkout/components/order-summary.vue
- client-app/ui-kit/components/atoms/layout/vc-layout.vue
https://virtocommerce.atlassian.net/browse/VCST-2415
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.11.0-pr-1487-3cf3-3cf3de30.zip
> fix: vc-layout styles

- client-app/ui-kit/components/atoms/typography/vc-typography.vue
https://virtocommerce.atlassian.net/browse/VCST-2202
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.11.0-pr-1488-c3da-c3dafda8.zip
> feat: extend vc-typography

- client-app/pages/cart.vue
- client-app/ui-kit/components/atoms/action-input/vc-action-input.vue
https://virtocommerce.atlassian.net/browse/VCST-2283
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.11.0-pr-1477-0bb1-0bb1360e.zip
> fix: replace Remove Selected button with Proceed to checkout

- client-app/ui-kit/components/atoms/typography/vc-typography.vue
This reverts commit ad319483b592645856f4a434aafafdb056acf9bd.
https://virtocommerce.atlassian.net/browse/VCST-2202
> Revert "feat: extend vc-typography (#1488)"

- client-app/ui-kit/composables/useStickySidebar.ts
https://virtocommerce.atlassian.net/browse/VCST-2430
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.11.0-pr-1491-d071-d071048e.zip
> fix: useStickySidebar

- client-app/core/utilities/index.ts
- client-app/core/utilities/tests/index.ts
- client-app/shared/cart/components/add-to-cart.vue
- client-app/ui-kit/components/organisms/add-to-cart/vc-add-to-cart.test.ts
- client-app/ui-kit/components/organisms/add-to-cart/vc-add-to-cart.vue
https://virtocommerce.atlassian.net/browse/VCST-2431
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.12.0-pr-1493-23b2-23b2de37.zip
> fix: vc-add-to-cart unit tests

- client-app/pages/cart.vue
- client-app/shared/layout/components/footer/_internal/footer-link.vue
- client-app/shared/layout/components/footer/_internal/footer-links.vue
- client-app/shared/layout/components/footer/vc-footer.vue
- client-app/shared/layout/components/main-layout/main-layout.vue
- client-app/ui-kit/components/molecules/widget/vc-widget.stories.ts
- client-app/ui-kit/components/molecules/widget/vc-widget.vue
- client-app/ui-kit/composables/useStickySidebar.ts
https://virtocommerce.atlassian.net/browse/VCST-1937
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.12.0-pr-1494-0abd-0abd0928.zip
> feat: implement new footer design

- client-app/assets/styles/preflight.scss
- client-app/assets/styles/vendors.scss
- client-app/assets/styles/vendors/_builder-io.scss
https://virtocommerce.atlassian.net/browse/VCST-2202
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.12.0-pr-1497-3ed4-3ed492d7.zip
> feat: implement header styles for builder-io

- client-app/core/utilities/common/index.test.ts
- client-app/core/utilities/common/index.ts
https://virtocommerce.atlassian.net/browse/VCST-2467
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.12.0-pr-1509-ffb6-ffb60af3.zip
> fix: open redirect

- client-app/shared/layout/components/currency-selector/currency-selector.vue
https://virtocommerce.atlassian.net/browse/VCST-2352
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.12.0-pr-1514-d494-d494c483.zip
> fix: currency-selector

- client-app/ui-kit/components/molecules/line-items/vc-line-items.vue
https://virtocommerce.atlassian.net/browse/VCST-2428
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.12.0-pr-1513-c91b-c91b58b4.zip
> fix: change vc-line-items buttons color

- client-app/shared/layout/components/header/_internal/mobile-menu/menus/settings-menu.vue
- client-app/shared/layout/components/header/_internal/mobile-menu/mobile-menu.vue
Fix merge cart issue on currency change
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.13.0-pr-1519-af5c-af5c37a9.zip
> fix: merge cart issue on currency change at mobile view

- client-app/core/api/graphql/catalog/queries/getProduct/index.ts
- client-app/pages/product.vue
- client-app/shared/catalog/composables/useProduct.ts
https://virtocommerce.atlassian.net/browse/VCST-1935
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.13.0-pr-1522-cefb-cefb2d0c.zip
> fix: product type

- client-app/shared/catalog/components/category/category-products.vue
- client-app/ui-kit/components/atoms/infinity-scroll-loader/vc-infinity-scroll-loader.vue
Fix end of items list message for endless scroll
https://virtocommerce.atlassian.net/browse/VCST-2135
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.13.0-pr-1526-332d-332dce82.zip
> fix: end of items list message for endless scroll

- client-app/pages/product.vue
https://virtocommerce.atlassian.net/browse/VCST-2450
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.13.0-pr-1528-7beb-7bebc99c.zip
> fix: hide extra sort filter for product variations

- client-app/shared/catalog/components/category.vue
https://github.com/user-attachments/assets/9f3dda58-6e23-483b-a938-ac38812f1f0b
https://virtocommerce.atlassian.net/browse/VCST-2438
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.13.0-pr-1529-ec7b-ec7b5794.zip
> fix: infinity scroll after changing filters

- client-app/pages/matcher/matcher.vue
- client-app/shared/layout/components/main-layout/main-layout.vue
https://virtocommerce.atlassian.net/browse/VCST-2505
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.13.0-pr-1530-2ba7-2ba740d9.zip
> feat: update main-layout styles

- README.md
https://virtocommerce.atlassian.net/browse/VCST-2549
> docs: update repository url and backend url example

- client-app/shared/layout/components/language-selector/language-selector.vue
https://virtocommerce.atlassian.net/browse/VCST-2561
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.14.0-pr-1543-4af7-4af79248.zip
> fix: capitalize language menu names

- client-app/modules/quotes/pages/edit-quote.vue
https://github.com/user-attachments/assets/d3c04465-85fc-446d-9ecd-9061664ebac3
https://virtocommerce.atlassian.net/browse/VCST-2225
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.14.0-pr-1548-ffe7-ffe759fc.zip
> feat: show confirmation when leave quote page with unsaved changes

- client-app/ui-kit/composables/useStickySidebar.ts
https://virtocommerce.atlassian.net/browse/VCST-2610
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.14.0-pr-1552-2deb-2deb570b.zip
> fix: useStickySidebar exclamation mark

- package.json
- yarn.lock
https://virtocommerce.atlassian.net/browse/VCST-2611
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.14.0-pr-1553-85ff-85ff144e.zip
> chore: upgrade skyflow

- client-app/shared/account/components/account-navigation-link-components/link-orders.vue
- client-app/shared/catalog/components/product-videos.vue
- client-app/shared/fulfillmentCenters/components/branches-modal.vue
https://virtocommerce.atlassian.net/browse/VCST-2392
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.15.0-pr-1556-ff13-ff136f62.zip
> feat: refactor role to button

- client-app/modules/purchase-requests/README.md
https://virtocommerce.atlassian.net/browse/VCST-2571
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.15.0-pr-1558-34ba-34baecfd.zip
> docs: add support contacts in the Purchase Requests module

- client-app/app-runner.ts
- package.json
- yarn.lock
https://virtocommerce.atlassian.net/browse/VCST-2619
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.15.0-pr-1562-1d77-1d77dcfa.zip
> chore: remove builder.io warnings

- client-app/modules/back-in-stock/index.ts
- client-app/modules/push-messages/index.ts
- client-app/pages/matcher/matcher.vue
- client-app/shared/common/composables/useCustomProductComponents.ts
- client-app/shared/layout/composables/useCustomAccountLinkComponents.ts
- client-app/shared/layout/composables/useCustomHeaderLinkComponents.ts
- client-app/shared/layout/composables/useCustomMobileHeaderComponents.ts
- client-app/shared/layout/composables/useCustomMobileMenuLinkComponents.ts
Remove warnings:
https://virtocommerce.atlassian.net/browse/VCST-2623
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.15.0-pr-1565-116b-116ba008.zip
> chore: remove warnings

- client-app/core/api/graphql/types.ts
- client-app/core/utilities/search/facets.test.ts
- client-app/core/utilities/search/facets.ts
[](https://virtocommerce.atlassian.net/browse/VCST-2608)
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.15.0-pr-1568-a9b0-a9b061aa.zip
> fix: change range facet bounds to nullable decimal

- client-app/pages/company/members.vue
https://github.com/user-attachments/assets/00719244-f909-40ad-b34a-07e59735fba6
https://virtocommerce.atlassian.net/browse/VCST-2342
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.15.0-pr-1560-6407-640713ac.zip
> fix: add break-words rule in Company members page

- client-app/pages/account/profile.vue
Keep cart items on change language on profile page
https://virtocommerce.atlassian.net/browse/VCST-2658
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.15.0-pr-1572-1b0b-1b0bd927.zip
> fix: keep cart items on change language on profile page

- client-app/shared/catalog/components/category/category-products.vue
- client-app/shared/catalog/composables/useProducts.ts
- client-app/ui-kit/components/atoms/infinity-scroll-loader/vc-infinity-scroll-loader.vue
https://github.com/user-attachments/assets/d3a6bc46-20a2-494c-a091-ed9f12eb8629
https://virtocommerce.atlassian.net/browse/VCST-2660
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.15.0-pr-1571-cb67-cb678d75.zip
> fix: infinity scroll in catalog

- client-app/pages/company/info.vue
https://virtocommerce.atlassian.net/browse/VCST-2665
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.15.0-pr-1573-c424-c424f301.zip
> fix: permissions check

- client-app/shared/common/components/address-selection.vue
Button size ar address selection component
https://virtocommerce.atlassian.net/browse/VCST-2666
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.15.0-pr-1574-e6c7-e6c7d727.zip
> fix: button size ar address selection component

- client-app/ui-kit/utilities/images.ts
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.16.0-pr-1580-ed14-ed14c1b2.zip
> fix: ui kit images import

- locales/ru.json
Ru localization corrections
https://virtocommerce.atlassian.net/browse/VCST-2479
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.14.0-pr-1536-2f07-2f0796c2.zip
> Ru localization corrections

- client-app/shared/catalog/components/category.vue
https://virtocommerce.atlassian.net/browse/VCST-2353
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.15.0-pr-1570-4b01-4b01465d.zip
> feat:  add numbers formating

- client-app/pages/account/list-details.vue
https://virtocommerce.atlassian.net/browse/VCST-2581
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.16.0-pr-1584-bd81-bd816531.zip
> fix: wishlist add all results popup

- client-app/ui-kit/components/molecules/input/vc-input.vue
https://virtocommerce.atlassian.net/browse/VCST-2615
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.16.0-pr-1587-0091-0091bfcb.zip
> fix: vc-input unfocus on tab keyboard event

- .github/workflows/theme-ci.yml
Update sonar workflow
https://virtocommerce.atlassian.net/browse/VCST-2476
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.16.0-pr-1596-233e-233e0c89.zip
> fix: update sonar workflow

- .storybook/preview.ts
https://virtocommerce.atlassian.net/browse/VCST-2034
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.16.0-pr-1593-3784-3784cc79.zip
> fix: storybook color preset

- locales/en.json
https://virtocommerce.atlassian.net/browse/VCST-2627
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.16.0-pr-1599-54a0-54a0fdf9.zip
> fix: logo changed en locale

- client-app/pages/account/order-payment.vue
- client-app/shared/cart/composables/useCart.ts
1. Check payment method availability
2. Show error if method selection failed 
Also fixed console warning
https://virtocommerce.atlassian.net/browse/VCST-2621
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.16.0-pr-1590-808b-808b2284.zip
> fix: add isPaymentAvailable check

- client-app/pages/matcher/builderIo/customComponents.ts
- client-app/shared/static-content/components/slider.vue
https://virtocommerce.atlassian.net/browse/VCST-2637
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.16.0-pr-1583-706f-706fa85e.zip
> feat: slider links

- client-app/ui-kit/components/molecules/shape/vc-shape.stories.ts
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.17.0-pr-1605-31a7-31a735ce.zip
> feat: add rating stories for vc-shape

- client-app/app-runner.ts
- client-app/core/composables/useNavigations.ts
- client-app/core/composables/useThemeContext.ts
- client-app/core/types/theme-config.ts
- client-app/core/types/theme-context.ts
Before: five intervals
After: two intervals
https://virtocommerce.atlassian.net/browse/VCST-2830
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.17.0-pr-1608-7d04-7d042d7c.zip
> feat: optimize initial request order

- vite.config.ts
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.12.0-pr-1515-2589-2589104e.zip
> change vite config to solve cors problem

- client-app/shared/layout/components/skip-to-links/skip-to-links.vue
https://virtocommerce.atlassian.net/browse/VCST-2456
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.17.0-pr-1617-5199-5199fce8.zip
> fix: "skip to" links overlap top menu

- client-app/core/api/graphql/types.ts
- client-app/modules/quotes/api/graphql/types.ts
- client-app/shared/catalog/components/product/properties.vue
https://virtocommerce.atlassian.net/browse/VCST-2794
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.17.0-pr-1613-2b0b-2b0b76e2.zip
> feat: Added support for HTML in product property

- client-app/shared/payment/components/payment-processing-cyber-source.vue
https://virtocommerce.atlassian.net/browse/VCST-2833
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.17.0-pr-1618-30d7-30d7ae6d.zip
> feat: add placeholder to cybersource

- client-app/shared/account/components/orders.vue
- locales/de.json
- locales/en.json
- locales/es.json
- locales/fr.json
- locales/it.json
- locales/ja.json
- locales/pl.json
- locales/pt.json
- locales/ru.json
- locales/zh.json
Orders scope buttons alignment
https://virtocommerce.atlassian.net/browse/VCST-2620
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.17.0-pr-1624-2195-2195613e.zip
> fix: orders scope buttons alignment

- client-app/ui-kit/components/molecules/widget/vc-widget.vue
https://virtocommerce.atlassian.net/browse/VCST-2831
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.17.0-pr-1628-9fed-9fedd18c.zip
> fix: vc-widget styles

- client-app/app-runner.ts
> fix: sonar issue

- client-app/app-runner.ts
- client-app/pages/matcher/builderIo/consoleWarnings.ts
- client-app/shared/payment/components/payment-processing-cyber-source.vue
- client-app/ui-kit/index.ts
- client-app/ui-kit/utilities/images.ts
https://virtocommerce.atlassian.net/browse/VCST-2494
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.17.0-pr-1625-a56e-a56e0b9b.zip
> chore: add ui kit global settings

- client-app/app-runner.ts
- client-app/pages/matcher/builderIo/consoleWarnings.ts
- client-app/ui-kit/index.ts
- client-app/ui-kit/utilities/images.ts
Reverts VirtoCommerce/vc-frontend#1625
Artifact URL:
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.18.0-pr-1634-3af0-3af0e14e.zip
> Revert "chore: add ui kit global settings"

- client-app/app-runner.ts
https://virtocommerce.atlassian.net/browse/VCST-2937
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.18.0-pr-1642-a7cf-a7cffc8b.zip
> fix: wrong culture name

- client-app/core/composables/useHistoricalEvents.ts
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.18.0-pr-1643-def0-def0b89c.zip
> fix: circular dependencies

- client-app/shared/catalog/components/product/properties.vue
https://virtocommerce.atlassian.net/browse/VCST-2802
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.18.0-pr-1641-3b54-3b548282.zip
> feat: show product details property value on hover

- client-app/config/settings_data.json
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.18.0-pr-1648-170f-170f8f85.zip
> feat: set isCVVinSkyflowRequired to true by default

- client-app/modules/push-messages/components/push-message.vue
- client-app/modules/push-messages/components/push-messages.vue
- client-app/modules/push-messages/components/vc-push-messages.vue
https://virtocommerce.atlassian.net/browse/VCST-2956
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.18.0-pr-1649-a11b-a11b7111.zip
> fix: click on push message closed popup

- client-app/modules/push-messages/components/vc-push-messages.vue
- client-app/shared/cart/components/clear-cart-modal.vue
- client-app/ui-kit/components/molecules/dialog-footer/vc-dialog-footer.vue
https://virtocommerce.atlassian.net/browse/VCST-2955
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.18.0-pr-1650-f3c2-f3c2f8d0.zip
> fix: vc-dialog-footer fixes

- client-app/core/api/graphql/types.ts
This reverts commit aa45c6bda3dce1b82e142dcbf71fe395cbd648a3.
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.18.0-pr-1652-4c1a-4c1a7e45.zip
> Revert "chore: generate types (#1651)"

- client-app/core/utilities/date/index.test.ts
https://virtocommerce.atlassian.net/browse/VCST-2763
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.19.0-pr-1654-5c58-5c582b63.zip
> chore: add unit tests for date utilites

- client-app/assets/styles/_print.scss
- client-app/assets/styles/print/molecules/vc-alert.scss
- client-app/ui-kit/components/molecules/alert/vc-alert.vue
https://virtocommerce.atlassian.net/browse/VCST-2817
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.18.0-pr-1632-06c0-06c078c9.zip
> fix: hide notification during printing

- client-app/core/utilities/search/facets.test.ts
- client-app/core/utilities/search/facets.ts
- client-app/core/utilities/search/filter.test.ts
- client-app/core/utilities/search/filter.ts
- client-app/core/utilities/search/sorting.test.ts
- client-app/core/utilities/search/sorting.ts
https://virtocommerce.atlassian.net/browse/VCST-2761
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.19.0-pr-1663-2112-21123eda.zip
> chore: add tests for search utils

- client-app/app-runner.ts
- client-app/assets/presets/index.ts
- client-app/core/composables/useThemeContext.ts
https://virtocommerce.atlassian.net/browse/VCST-2814
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.19.0-pr-1661-a6d1-a6d1010f.zip
> chore: make color preset setup synchronous

- client-app/core/utilities/line-items/index.test.ts
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.19.0-pr-1671-6586-65863a00.zip
> fix: line-item utilities test mock data

- .github/workflows/release.yml
> fix: bump release flow version

- client-app/shared/layout/components/header/_internal/mobile-header.vue
- client-app/shared/ship-to-location/components/ship-to-selector.vue
https://virtocommerce.atlassian.net/browse/VCST-3104
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.20.0-pr-1679-ac50-ac501944.zip
> fix: ship-to-selector styles & layout

- client-app/pages/sign-in.vue
https://virtocommerce.atlassian.net/browse/VCST-3024
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.20.0-pr-1680-68ef-68ef935b.zip
> fix: sign-in styles

- package.json
- yarn.lock
Still have warnings
https://virtocommerce.atlassian.net/browse/VCST-3011
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.20.0-pr-1686-83df-83df2e05.zip
> chore: update @builder.io/sdk-vue

- .storybook/main.ts
- .storybook/preview.ts
- client-app/builder-preview/register-components.ts
- client-app/core/utilities/common/index.ts
- client-app/i18n.ts
- client-app/modules/customer-reviews/index.ts
- client-app/pages/checkout/payment.vue
- client-app/pages/matcher/virto-pages/vp-builder-io.vue
- yarn.lock
https://virtocommerce.atlassian.net/browse/VCST-2968
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.20.0-pr-1694-36ce-36ce52c9.zip
> chore: fix lint warnings and fix eslint yarn.lock

- client-app/modules/push-messages/components/vc-push-messages.vue
- client-app/ui-kit/components/molecules/menu-item/vc-menu-item.vue
https://virtocommerce.atlassian.net/browse/VCST-3068
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.20.0-pr-1690-c56e-c56ea38d.zip
> fix: push-messages dropdown-menu

- .github/workflows/theme-release-hotfix.yml
Add a new workflow to create a patch version release. The workflow increments the patch version in the 'package.json' file in the current branch only; no merges to other branches are made automatically. The code changes must be moved to the 'dev' branch manually. The Git Hub release is created as NOT latest.
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.20.0-pr-1698-74af-74af3516.zip
> VCST-2521: Add release-hotfix workflow

- client-app/builder-preview/scroll-to-element.vue
- client-app/shared/catalog/components/configuration/option-none.vue
- client-app/shared/catalog/components/configuration/option-text.vue
- client-app/shared/payment/components/payment-processing-skyflow.vue
Created for patch workflow
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.21.0-pr-1702-a3b4-a3b4eba0.zip
> chore: fix lint warnings

- client-app/shared/ship-to-location/components/ship-to-selector.vue
https://virtocommerce.atlassian.net/browse/VCST-3066
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.21.0-pr-1700-6fce-6fcec0e1.zip
> fix: unexpected 403 page on logout

- client-app/ui-kit/components/molecules/file-picker/vc-file-picker.stories.ts
https://virtocommerce.atlassian.net/browse/VCST-3065
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.20.0-pr-1697-3602-360228c3.zip
> feat: update VcFilePicker stories

- .github/workflows/theme-release-hotfix.yml
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.21.0-pr-1713-7d71-7d711497.zip
> VCST-2521: Patch release workflow

- client-app/shared/catalog/components/product/properties.vue
https://virtocommerce.atlassian.net/browse/VCST-3196
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.21.0-pr-1715-cfd3-cfd3db9b.zip
> fix: property groups

- client-app/pages/company/members.vue
- client-app/shared/layout/components/header/_internal/top-header.vue
https://virtocommerce.atlassian.net/browse/VCST-2657
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.20.0-pr-1693-ef5d-ef5d7042.zip
> fix: long member name styles

- client-app/shared/catalog/components/category/category-controls.vue
- client-app/shared/catalog/components/category/filters-popup-sidebar.vue
- client-app/shared/catalog/components/discount-badge.vue
- client-app/shared/catalog/components/products-filters.vue
- client-app/shared/catalog/components/purchased-before-badge.vue
https://virtocommerce.atlassian.net/browse/VCST-3197
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.22.0-pr-1726-a7bc-a7bc074d.zip
> fix: purchase-before and discount badge size and data-test-ids

- client-app/pages/brands.vue
https://virtocommerce.atlassian.net/browse/VCST-3034
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.22.0-pr-1733-d434-d434f6fa.zip
> fix: featured brand without logo [safari]

- client-app/ui-kit/components/atoms/popover/vc-popover.vue
- client-app/ui-kit/components/molecules/menu-item/vc-menu-item.vue
https://virtocommerce.atlassian.net/browse/VCST-3315
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.22.0-pr-1736-e5f7-e5f7fa24.zip
> fix: blur&click bug on Safari

- client-app/shared/catalog/components/product-card-related.vue
- client-app/shared/static-content/components/related-products.vue
- client-app/shared/wishlists/components/add-to-list.vue
- client-app/ui-kit/components/atoms/product-title/vc-product-title.vue
- client-app/ui-kit/components/atoms/products-grid/vc-products-grid.vue
- client-app/ui-kit/components/molecules/product-button/vc-product-button.vue
- locales/ja.json
https://virtocommerce.atlassian.net/browse/VCST-3115
https://virtocommerce.atlassian.net/browse/VCST-3060
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.23.0-pr-1706-9079-907903ea.zip
> feat: update vc-product-grid && related-products

- client-app/App.vue
- client-app/ui-kit/components/atoms/input-details/vc-input-details.vue
- client-app/ui-kit/components/atoms/popover/vc-popover.vue
https://virtocommerce.atlassian.net/browse/VCST-3333
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.23.0-pr-1737-e37a-e37aef2a.zip
> feat: implement teleport to body to VcPopover

- client-app/ui-kit/components/molecules/button/vc-button.vue
https://virtocommerce.atlassian.net/browse/VCST-3236
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.22.0-pr-1731-8912-891223f1.zip
> fix: console log errors during checkout

- client-app/ui-kit/components/molecules/button/vc-button.vue
https://virtocommerce.atlassian.net/browse/VCST-3236
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.23.0-pr-1742-9025-90256d14.zip
> fix: revert vc-button focus changes

- client-app/pages/search.vue
- locales/de.json
- locales/en.json
- locales/es.json
- locales/fr.json
- locales/it.json
- locales/ja.json
- locales/pl.json
- locales/pt.json
- locales/ru.json
- locales/zh.json
https://virtocommerce.atlassian.net/browse/VCST-3307
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.23.0-pr-1744-13a9-13a9af09.zip
> fix: search page empty title

- client-app/ui-kit/components/organisms/pagination/vc-pagination.vue
https://virtocommerce.atlassian.net/browse/VCST-3166
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.23.0-pr-1748-6bd3-6bd3b64e.zip
> feat: update vc-pagination buttons design

- client-app/shared/account/components/orders.vue
https://virtocommerce.atlassian.net/browse/VCST-3306
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.23.0-pr-1753-8777-8777aa30.zip
> fix: orders filters styles

- client-app/shared/account/components/orders.vue
https://virtocommerce.atlassian.net/browse/VCST-3316
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.23.0-pr-1754-372c-372c6d6a.zip
> fix: disable orders toolbar stick

- client-app/pages/checkout/review.vue
- client-app/shared/checkout/components/billing-details-section.vue
https://virtocommerce.atlassian.net/browse/VCST-3457
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.24.0-pr-1777-494d-494deae6.zip
> feat: change display of payment methods in checkout/ billing & review

- client-app/core/api/graphql/types.ts
- client-app/modules/quotes/api/graphql/types.ts
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.24.0-pr-1782-5ac6-5ac6fe17.zip
> chore: generate GraphQL types

- client-app/shared/layout/components/currency-selector/currency-selector.vue
- client-app/shared/layout/components/header/_internal/top-header-link.vue
- client-app/shared/layout/components/header/_internal/top-header.vue
- client-app/shared/layout/components/language-selector/language-selector.vue
- client-app/shared/ship-to-location/components/ship-to-selector.vue
Add test ids for top header elements
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.25.0-pr-1783-7687-7687e48d.zip
> feat: add test ids for top header elements

- client-app/shared/account/components/sign-in-form.vue
Add test ids for login page elements
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.25.0-pr-1784-b8c3-b8c38a7e.zip
> feat: add test ids for login page elements

- client-app/pages/sign-up.vue
- client-app/ui-kit/components/atoms/radio-button/vc-radio-button.vue
Add test id attributes for sign up page elements
https://virtocommerce.atlassian.net/browse/VCST-3510
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.25.0-pr-1788-fc69-fc692138.zip
> feat: add test id attributes for sign up page elements

- client-app/core/api/graphql/catalog/queries/getProduct/getProductQuery.graphql
- client-app/core/api/graphql/types.ts
- client-app/modules/quotes/api/graphql/types.ts
- client-app/shared/catalog/components/product/properties.vue
https://virtocommerce.atlassian.net/browse/VCST-3388
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.25.0-pr-1785-10d5-10d59b27.zip
> feat: clickable Brand property value on product page

- client-app/shared/layout/components/search-bar/search-bar.vue
https://virtocommerce.atlassian.net/browse/VCST-3531
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.25.0-pr-1793-6a7f-6a7fc35c.zip
> fix: keep filters when search

- client-app/shared/catalog/components/product/variations-default.vue
https://virtocommerce.atlassian.net/browse/VCST-3561
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.25.0-pr-1801-4daf-4daff5f9.zip
> fix: sale price in variations list

- client-app/broadcast.ts
https://virtocommerce.atlassian.net/browse/VCST-2195
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.26.0-pr-1806-3cf1-3cf1bbd5.zip
> fix: display message on grapqhl error

- client-app/core/api/graphql/types.ts
- client-app/shared/cart/composables/useCart.ts
https://virtocommerce.atlassian.net/browse/VCST-3577
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.26.0-pr-1815-2bb7-2bb7bfda.zip
> chore: new user null cart handle

- client-app/shared/catalog/components/category-selector.vue
https://virtocommerce.atlassian.net/browse/VCST-3581
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.26.0-pr-1812-fbed-fbed6b2e.zip
> fix: styles for long category names in category-selector

- package.json
- yarn.lock
https://virtocommerce.atlassian.net/browse/VCST-3170
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.27.0-pr-1824-4956-4956d5f8.zip
> fix: eslint-plugin-storybook version

- client-app/shared/checkout/components/select-address-modal.vue
https://virtocommerce.atlassian.net/browse/VCST-3625
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.27.0-pr-1827-f5ed-f5ed4b5b.zip
> fix: select address modal buttons desktop positioning

- client-app/shared/account/components/sign-in-form.vue
- client-app/shared/layout/components/search-bar/search-bar.vue
https://virtocommerce.atlassian.net/browse/VCST-3598
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.27.0-pr-1828-310d-310d2b11.zip
> fix: improve accessibility

- client-app/config/settings_data.json
- client-app/ui-kit/components/organisms/quantity-stepper/vc-quantity-stepper.vue
https://virtocommerce.atlassian.net/browse/VCST-3475
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.27.0-pr-1837-11cc-11cc95aa.zip
> chore: data-test-ids for vc-quantity-stepper

- client-app/assets/styles/preflight.scss
https://virtocommerce.atlassian.net/browse/VCST-3669
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.27.0-pr-1838-9e3a-9e3a1434.zip
> fix: remove default border-radius for focused elements

- client-app/core/enums/query-param-name.enum.ts
- client-app/shared/catalog/composables/useProducts.ts
https://virtocommerce.atlassian.net/browse/VCST-3516
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.27.0-pr-1843-ba3d-ba3d45e2.zip
> chore: mark keyword search parameter as deprecated

- client-app/shared/files/composables/useFiles.ts
https://virtocommerce.atlassian.net/browse/VCST-3635
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.27.0-pr-1835-891c-891c25de.zip
> fix: save button in quote active after saving

- client-app/shared/layout/components/search-bar/search-bar.vue
https://virtocommerce.atlassian.net/browse/VCST-3673
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.27.0-pr-1842-0d01-0d01f2cf.zip
> fix: search dropdown shown after press enter

- client-app/ui-kit/components/molecules/alert/vc-alert.vue
https://virtocommerce.atlassian.net/browse/VCST-3677
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.27.0-pr-1844-6cfc-6cfcbca8.zip
> fix: text breaking in vc-alert content

- package.json
- yarn.lock
Due to issue with v-bind in 3.5.18
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.28.0-pr-1872-add3-add3f08a.zip
> chore: fix vue version on 3.5.17

- package.json
- yarn.lock
https://virtocommerce.atlassian.net/browse/VCST-3697
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.28.0-pr-1870-5b47-5b472b8e.zip
> fix: revert upgrading vue-tsc

- client-app/core/api/graphql/types.ts
- client-app/core/utilities/search/facets.test.ts
- client-app/shared/catalog/components/facet-filter.vue
- client-app/shared/catalog/components/product/slider-filter.vue
- client-app/shared/catalog/composables/useProducts.test.ts
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.28.0-pr-1876-3fb8-3fb86c4e.zip
> feat: generated types

- client-app/shared/layout/components/header/_internal/mega-menu.vue
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.29.0-pr-1890-d1f4-d1f4fbe9.zip
> fix: mega-menu button focus on Safari

- client-app/shared/catalog/components/active-filter-chips.vue
- client-app/shared/catalog/components/category.vue
- client-app/shared/catalog/composables/useProducts.ts
https://virtocommerce.atlassian.net/browse/VCST-3496
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.30.0-pr-1900-d286-d286e9f6.zip
> fix: hide brand filter on brand page

- .github/workflows/theme-ci.yml
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.30.0-pr-1909-5164-5164552f.zip
> VCST-3838: Use latest version for SonarSource/sonarqube-scan-action

- client-app/broadcast.ts
https://virtocommerce.atlassian.net/browse/VCST-3837
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.30.0-pr-1910-fcb3-fcb34c15.zip
> fix: duplicated error toasts

- client-app/shared/account/components/account-navigation-link-components/link-lists.vue
- client-app/shared/account/components/account-navigation-link-components/link-orders.vue
https://virtocommerce.atlassian.net/browse/VCST-3841
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.30.0-pr-1913-9961-99619f7a.zip
> fix: link-orders & link-lists focus outline clipping

- client-app/pages/product.vue
https://virtocommerce.atlassian.net/browse/VCST-3536
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.31.0-pr-1932-950b-950b9151.zip
> fix: delete lineItemId param if there is no such line item in cart

- client-app/shared/catalog/components/product-card.vue
https://virtocommerce.atlassian.net/browse/VCST-3946
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.31.0-pr-1937-bdf3-bdf38e0d.zip
> fix: promo price in catalog is not shown

- scripts/locale-utils.ts
https://virtocommerce.atlassian.net/browse/VCST-2746
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.31.0-pr-1947-f63c-f63c645f.zip
> fix: fix-locales script unexpected null values

- client-app/ui-kit/components/atoms/product-title/vc-product-title.vue
https://virtocommerce.atlassian.net/browse/VCST-3930
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.31.0-pr-1943-417c-417c6015.zip
> fix: word-break in vc-product-title

- client-app/shared/payment/components/payment-processing-skyflow.vue
- locales/de.json
- locales/en.json
- locales/es.json
- locales/fr.json
- locales/it.json
- locales/ja.json
- locales/pl.json
- locales/pt.json
- locales/ru.json
- locales/zh.json
- scripts/locale-utils.ts
https://virtocommerce.atlassian.net/browse/VCST-3907
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.31.0-pr-1946-2c52-2c52e479.zip
> fix: skyflow security code mask

- client-app/core/constants/modules.ts
- client-app/shared/catalog/composables/useProducts.ts
Description
https://virtocommerce.atlassian.net/browse/VCST-3588
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.32.0-pr-1967-95c7-95c7b2af.zip
> feat(VCST-3910): feature flag for setting preserveUserQuery parameter

- client-app/shared/layout/components/currency-selector/currency-selector.vue
- client-app/shared/layout/components/header/_internal/top-header.vue
- client-app/shared/layout/components/language-selector/language-selector.vue
https://virtocommerce.atlassian.net/browse/VCST-4004
https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-2.32.0-pr-1978-98ff-98ff4448.zip
> fix(VCST-4004): wrong view of currency and language with long address in the header
